# P2 Scratchpad

Things I think will be useful

## Pandas Library

In [2]:
# first we need to import pandas.  Convention is variable pd
import pandas as pd

# make a list and dict to use pandas on
simple_list = ['apples', 'oranges', 'bananas', 'pears']

In [8]:
# print out list
print('First list item (simple_list[0]) is {0}'.format(simple_list[0]))
print('Third list item (simple_list[2]) is {0}'.format(simple_list[2]))
print('Last list item (simple_list[-1]) is {0}'.format(simple_list[-1]))
print('2nd last list item (simple_list[-2]) is {0}'.format(simple_list[-2]))

First list item (simple_list[0]) is apples
Third list item (simple_list[2]) is bananas
Last list item (simple_list[-1]) is pears
2nd last list item (simple_list[-2]) is bananas

Make a simple dictionary

In [9]:
simple_dict = {1:'one', 2:'two', 4:'four', 3:'three'}
print("Item with key (index) '4' has value: {}".format(simple_dict[4]))

Item with key (index) '4' has value: four

We can iterate through all keys using for loop

In [10]:
for key in simple_dict:
    print(simple_dict[key])

one
two
three
four

<span style="color:#3388CC">
Indigo note.
</span>

Or we can use _list comprehension_<span style="color:#3A9C35">
Kuma
</span>
iterm

test

In [14]:
print(list(simple_dict.keys()))
print(list(simple_dict.values()))

[1, 2, 3, 4]
['one', 'two', 'three', 'four']

we can use a list or dict comprehension to filter the contents of an object according to a test condition.

In [15]:
[simple_dict[k] for k in simple_dict if k>2]

['three', 'four']

Simple way to reverse a dictionary using zip()

In [24]:
# zip into a collection of tuples
alt_dict = zip(simple_dict.values(), simple_dict.keys())
for e in alt_dict:
    print(e)

('one', 1)
('two', 2)
('three', 3)
('four', 4)

In [28]:
# concise method:
alternative_dict = dict(zip(simple_dict.values(), simple_dict.keys()))

print(alternative_dict)

{'four': 4, 'two': 2, 'one': 1, 'three': 3}

## Pandas Series and Dataframes

In [30]:
pd.Series( ['one', 'two', 'three', 'four'] )

0      one
1      two
2    three
3     four
dtype: object

In [31]:
# we can simplify the creation of a Series by importingi it from pandas directly
from pandas import Series
simple_series = Series( [101, 102, 103, 104])
simple_series

0    101
1    102
2    103
3    104
dtype: int64

In [32]:
simple_series[1]

102

In [33]:
simple_series[[1, 0, 3]]

1    102
0    101
3    104
dtype: int64

In [34]:
myindex_series = Series( ['apple', 'orange', 'pear', 'plum'],
                       index=['one', 'two', 'three', 'four'])
print(myindex_series.index)
myindex_series

Index(['one', 'two', 'three', 'four'], dtype='object')

one       apple
two      orange
three      pear
four       plum
dtype: object

## Investigating a file

### Take a peak at the firs few lines of a file

In [3]:
!ls 'TM351_part_02_notebooks/data/iwCouncilSpending/'

csvFromWeb.csv	PUBLISHED FORMAT - NOV 2013.csv  sample1.csv  sample2.csv

In [4]:
!head -n 5 TM351_part_02_notebooks/data/iwCouncilSpending/PUBLISHED\ FORMAT\ -\ NOV\ 2013.csv

###Â get a line count
using th -l switch to count lines

This line count is the upper bound as some data may be split over several lines

In [7]:
!wc -l 'TM351_part_02_notebooks/data/iwCouncilSpending/PUBLISHED FORMAT - NOV 2013.csv'

11413 TM351_part_02_notebooks/data/iwCouncilSpending/PUBLISHED FORMAT - NOV 2013.csv

### We can also peak at last few lines
this is useful to check whether there is any blank lines at tthe end of a file

In [8]:
!tail -n 6 'TM351_part_02_notebooks/data/iwCouncilSpending/PUBLISHED FORMAT - NOV 2013.csv'

## Reading in CSV files

_pandas_ provides utilities for reading and writing CSV files so we will use it

In [9]:
import pandas as pd

In [14]:
pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/sample1.csv')

,Capital or Revenue,Directorate,Transaction Number,Date,Service Area,Expenses Type,Amount,Supplier Name
0,Revenue,Community Wellbeing & Social Care,5105636098,13.11.2013,Public Libraries Central,Marketing Costs,200.00,REDACTED PERSONAL DATA
1,Revenue,Community Wellbeing & Social Care,5105635705,08.11.2013,Drug Misuse - Adults,Charges from Independent Providers,120.00,REDACTED PERSONAL DATA
2,Revenue,Childrens Services,5105637261,20.11.2013,Thompson House Tuition Centre (PRU),Professional Services,240.00,* M BOWDERY T/A SPOTLIGHT BOUTIQUE
3,Revenue,Community Wellbeing & Social Care,5105637069,27.11.2013,Safeguarding Adults,Professional Services,"5,285.00",REDACTED PERSONAL DATA
4,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
5,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
6,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
7,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
8,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA

### be careful of encodings

In [15]:
#pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/sample2.csv')
import chardet
testfile = open('TM351_part_02_notebooks/data/iwCouncilSpending/sample2.csv', 'rb').read()
chardet.detect(testfile)

{'confidence': 0.73, 'encoding': 'windows-1252'}

In [16]:
pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/sample2.csv', encoding='windows-1252')

,Revenue,Community Wellbeing & Social Care,GPC,23.11.2013,Training - Childrens,Licences,28.96,SURVEYMONKEY.COM
0,Revenue,Community Wellbeing & Social Care,GPC,27.11.2013,Workforce Development - Early Years,Postage,6.95,POST OFFICE COUNTERS
1,Revenue,Resources,GPC,27.11.2013,Organisational Development â Leadership,Professional Services,28.90,WWW.PRINTEDPAPERPRODUCTS.CO.UK
2,Revenue,Community Wellbeing & Social Care,GPC,27.11.2013,Hub Coordinators,Travel Expenses,25.00,STAGECOACH SOUTH
3,Revenue,Community Wellbeing & Social Care,GPC,27.11.2013,Workforce Development - Westridge Centre,Catering Purchases,30.58,TESCO STORE 5567
4,Revenue,Economy & Environment,GPC,31.10.2013,Play Development,Operational Equipment,127.99,GLENWAY PRODUCTS LTD
5,Revenue,Economy & Environment,GPC,04.11.2013,Play Development,Operational Equipment,91.99,GREENHAM TRADING LTD
6,Revenue,Economy & Environment,GPC,06.11.2013,Play Development,Travel Expenses,470.70,WIGHTLINK
7,Revenue,Economy & Environment,GPC,13.11.2013,Play Development,Operational Equipment,108.42,WWW.SPORTSFRONT.CO.UK
8,Revenue,Economy & Environment,GPC,14.11.2013,Sports Development - Admin,Training,12.50,WWW.RFU.COM

### read in n lines of a file

In [48]:
sample2 = pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/sample2.csv', encoding='windows-1252', nrows=3)

In [49]:
origNames =  sample2.columns.values.tolist()
origNames

['Revenue',
 'Community Wellbeing & Social Care',
 'GPC',
 '23.11.2013',
 'Training - Childrens',
 'Licences',
 '28.96',
 'SURVEYMONKEY.COM']

###Â read file in as chunks

In [25]:
chunks = pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/sample2.csv',encoding='windows-1252',chunksize=4)

In [26]:
for chunk in chunks:
    print("New chunk...")
    print(chunk[['Revenue', 'Licences']])

New chunk...
   Revenue               Licences
0  Revenue                Postage
1  Revenue  Professional Services
2  Revenue        Travel Expenses
3  Revenue     Catering Purchases
New chunk...
   Revenue               Licences
4  Revenue  Operational Equipment
5  Revenue  Operational Equipment
6  Revenue        Travel Expenses
7  Revenue  Operational Equipment
New chunk...
   Revenue  Licences
8  Revenue  Training

### import a csv from a url

In [32]:
url = 'http://www.iwight.com/documentlibrary/download/november-2013-transparency-data-csv'

import requests
resp = requests.get(url)
resp.content[:103]

b'Capital or Revenue,Directorate,Transaction Number,Date,Service Area,Expenses Type,Amount,Supplier Name\r'

In [33]:
# b shows it is a byte object now use chardet to detect
import chardet
chardet.detect(resp.content)

{'confidence': 0.73, 'encoding': 'windows-1252'}

In [35]:
csvfromweb = pd.read_csv(url, encoding = 'windows-1252')
csvfromweb.head(5)

,Capital or Revenue,Directorate,Transaction Number,Date,Service Area,Expenses Type,Amount,Supplier Name
0,Revenue,Community Wellbeing & Social Care,5105636098,13.11.2013,Public Libraries Central,Marketing Costs,200.00,REDACTED PERSONAL DATA
1,Revenue,Community Wellbeing & Social Care,5105635705,08.11.2013,Drug Misuse - Adults,Charges from Independent Providers,120.00,REDACTED PERSONAL DATA
2,Revenue,Childrens Services,5105637261,20.11.2013,Thompson House Tuition Centre (PRU),Professional Services,240.00,* M BOWDERY T/A SPOTLIGHT BOUTIQUE
3,Revenue,Community Wellbeing & Social Care,5105637069,27.11.2013,Safeguarding Adults,Professional Services,"5,285.00",REDACTED PERSONAL DATA
4,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA

## Write DF to CSV files

In [37]:
csvfromweb.to_csv('TM351_part_02_notebooks/data/iwCouncilSpending/csvfromweb_a.csv')
# chow first few lines to prove written
pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/csvfromweb_a.csv', nrows=5)

,Unnamed: 0,Capital or Revenue,Directorate,Transaction Number,Date,Service Area,Expenses Type,Amount,Supplier Name
0,0,Revenue,Community Wellbeing & Social Care,5105636098,13.11.2013,Public Libraries Central,Marketing Costs,200.00,REDACTED PERSONAL DATA
1,1,Revenue,Community Wellbeing & Social Care,5105635705,08.11.2013,Drug Misuse - Adults,Charges from Independent Providers,120.00,REDACTED PERSONAL DATA
2,2,Revenue,Childrens Services,5105637261,20.11.2013,Thompson House Tuition Centre (PRU),Professional Services,240.00,* M BOWDERY T/A SPOTLIGHT BOUTIQUE
3,3,Revenue,Community Wellbeing & Social Care,5105637069,27.11.2013,Safeguarding Adults,Professional Services,"5,285.00",REDACTED PERSONAL DATA
4,4,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA

Files without header rows or index

In [41]:
csvfromweb.to_csv('TM351_part_02_notebooks/data/iwCouncilSpending/csvfromweb_unheaded.csv', index=False, header=False)
pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/csvfromweb_unheaded.csv', header=None)

,0,1,2,3,4,5,6,7
0,Revenue,Community Wellbeing & Social Care,5105636098,13.11.2013,Public Libraries Central,Marketing Costs,200.00,REDACTED PERSONAL DATA
1,Revenue,Community Wellbeing & Social Care,5105635705,08.11.2013,Drug Misuse - Adults,Charges from Independent Providers,120.00,REDACTED PERSONAL DATA
2,Revenue,Childrens Services,5105637261,20.11.2013,Thompson House Tuition Centre (PRU),Professional Services,240.00,* M BOWDERY T/A SPOTLIGHT BOUTIQUE
3,Revenue,Community Wellbeing & Social Care,5105637069,27.11.2013,Safeguarding Adults,Professional Services,"5,285.00",REDACTED PERSONAL DATA
4,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
5,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
6,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
7,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
8,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
9,Revenue,Childrens Services,5105634118,06.11.2013,Duty and Assessment 2,Professional Services,216.90,REDACTED PERSONAL DATA
10,Revenue,Childrens Services,5105636630,13.11.2013,Youth- Newport,General Materials,495.00,REDACTED PERSONAL DATA
11,Revenue,Childrens Services,5105634014,01.11.2013,Pupils with statements - Non-Maintained Schools,Office Equipment,826.50,REDACTED PERSONAL DATA
12,Revenue,Childrens Services,5105634012,01.11.2013,Pupils with statements - Non-Maintained Schools,Transport of Clients,383.50,REDACTED PERSONAL DATA
13,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,120.00,REDACTED PERSONAL DATA
14,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,50.00,REDACTED PERSONAL DATA
15,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,120.00,REDACTED PERSONAL DATA
16,Revenue,Economy & Environment,5105638339,27.11.2013,Love Lane Primary School PO31 7ET,Security of Buildings,30.00,REDACTED PERSONAL DATA
17,Revenue,Economy & Environment,5105638339,27.11.2013,Love Lane Primary School PO31 7ET,Security of Buildings,25.00,REDACTED PERSONAL DATA
18,Revenue,Economy & Environment,5105638339,27.11.2013,Love Lane Primary School PO31 7ET,Security of Buildings,310.00,REDACTED PERSONAL DATA
19,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,65.00,REDACTED PERSONAL DATA
20,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,310.00,REDACTED PERSONAL DATA
21,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,155.00,REDACTED PERSONAL DATA
22,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,25.00,REDACTED PERSONAL DATA
23,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,60.00,REDACTED PERSONAL DATA
24,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,80.00,REDACTED PERSONAL DATA
25,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,620.00,REDACTED PERSONAL DATA
26,Revenue,Resources,5105637961,22.11.2013,Capital Receipts,Capital Contractor Payments,100.00,REDACTED PERSONAL DATA
27,Revenue,Resources,5105637961,22.11.2013,Capital Receipts,Capital Contractor Payments,80.00,REDACTED PERSONAL DATA
28,Revenue,Resources,5105637961,22.11.2013,Capital Receipts,Capital Contractor Payments,100.00,REDACTED PERSONAL DATA
29,Revenue,Resources,5105637961,22.11.2013,Capital Receipts,Capital Contractor Payments,100.00,REDACTED PERSONAL DATA
...,...,...,...,...,...,...,...,...
11382,Revenue,Community Wellbeing & Social Care,GPC,11.11.2013,Workforce Development - Westridge Centre,Catering Purchases,18.05,TESCO STORE 5567
11383,Revenue,Childrens Services,GPC,11.11.2013,Adult Social Care - Workforce Development,Training,5.10,HUNTINGTONS DISEASE ASSOCIATION
11384,Revenue,Community Wellbeing & Social Care,GPC,12.11.2013,Governors Support,Travel Expenses,48.70,WWW.WIGHTLINK.CO.UK
11385,Revenue,Childrens Services,GPC,12.11.2013,LSCB (Local Safeguarding Childrens Board),Travel Expenses,47.60,STAGECOACH SOUTH
11386,Revenue,Community Wellbeing & Social Care,GPC,13.11.2013,Workforce Development - Westridge Centre,Catering Purchases,8.50,TESCO STORE 5567
11387,Revenue,Community Wellbeing & Social Care,GPC,13.11.2013,Workforce Development - Westridge Centre,Catering Purchases,4.00,TESCO STORE 5567
11388,Revenue,Community Wellbeing & Social Care,GPC,14.11.2013,Workforce Development - Westridge Centre,Catering Purchases,39.81,TESCO STORE 5567
11389,Revenue,Community Wellbeing & Social Care,GPC,19.11.2013,Personal & Community Development Learning,General Materials,9.99,AMAZON MARKTEPLACE
11390,Revenue,Community Wellbeing & Social Care,GPC,19.11.2013,Workforce Development - Westridge Centre,Catering Purchases,34.21,TESCO STORE 5567
11391,Revenue,Community Wellbeing & Social Care,GPC,20.11.2013,Personal & Community Development Learning,General Materials,3.96,AMAZON MARKTEPLACE
11392,Revenue,Community Wellbeing & Social Care,GPC,21.11.2013,Personal & Community Development Learning,General Materials,7.07,AMAZON MARKTEPLACE
11393,Revenue,Childrens Services,GPC,21.11.2013,Adult Social Care - Workforce Development,Travel Expenses,48.70,WWW.WIGHTLINK.CO.UK
11394,Revenue,Community Wellbeing & Social Care,GPC,21.11.2013,Workforce Development - Early Years,Travel Expenses,32.00,RED FUNNEL BOOKIT
11395,Revenue,Community Wellbeing & Social Care,GPC,21.11.2013,Workforce Development - Early Years,Travel Expenses,157.80,STAGECOACH SOUTH
11396,Revenue,Community Wellbeing & Social Care,GPC,21.11.2013,Workforce Development - Westridge Centre,Catering Purchases,4.00,TESCO STORE 5567
11397,Revenue,Community Wellbeing & Social Care,GPC,23.11.2013,Workforce Development - Westridge Centre,Licences,28.99,SURVEYMONKEY.COM
11398,Revenue,Community Wellbeing & Social Care,GPC,23.11.2013,Workforce Development Schools,Licences,28.99,SURVEYMONKEY.COM
11399,Revenue,Community Wellbeing & Social Care,GPC,23.11.2013,Core Programmes,Licences,28.99,SURVEYMONKEY.COM
11400,Revenue,Community Wellbeing & Social Care,GPC,23.11.2013,Workforce Development - Early Years,Licences,28.99,SURVEYMONKEY.COM
11401,Revenue,Childrens Services,GPC,23.11.2013,Adult Social Care - Workforce Development,Licences,28.99,SURVEYMONKEY.COM
11402,Revenue,Community Wellbeing & Social Care,GPC,23.11.2013,Training - Childrens,Licences,28.96,SURVEYMONKEY.COM
11403,Revenue,Community Wellbeing & Social Care,GPC,27.11.2013,Workforce Development - Early Years,Postage,6.95,POST OFFICE COUNTERS
11404,Revenue,Resources,GPC,27.11.2013,Organisational Development â Leadership,Professional Services,28.90,WWW.PRINTEDPAPERPRODUCTS.CO.UK
11405,Revenue,Community Wellbeing & Social Care,GPC,27.11.2013,Hub Coordinators,Travel Expenses,25.00,STAGECOACH SOUTH
11406,Revenue,Community Wellbeing & Social Care,GPC,27.11.2013,Workforce Development - Westridge Centre,Catering Purchases,30.58,TESCO STORE 5567
11407,Revenue,Economy & Environment,GPC,31.10.2013,Play Development,Operational Equipment,127.99,GLENWAY PRODUCTS LTD
11408,Revenue,Economy & Environment,GPC,04.11.2013,Play Development,Operational Equipment,91.99,GREENHAM TRADING LTD
11409,Revenue,Economy & Environment,GPC,06.11.2013,Play Development,Travel Expenses,470.70,WIGHTLINK
11410,Revenue,Economy & Environment,GPC,13.11.2013,Play Development,Operational Equipment,108.42,WWW.SPORTSFRONT.CO.UK
11411,Revenue,Economy & Environment,GPC,14.11.2013,Sports Development - Admin,Training,12.50,WWW.RFU.COM

get original column names

In [51]:
origNames = csvfromweb.columns.values.tolist()
origNames

['Capital or Revenue',
 'Directorate',
 'Transaction Number',
 'Date',
 'Service Area',
 'Expenses Type',
 'Amount',
 'Supplier Name']

In [54]:
pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/csvfromweb_unheaded.csv', nrows=5, header=None, names=origNames)

,Capital or Revenue,Directorate,Transaction Number,Date,Service Area,Expenses Type,Amount,Supplier Name
0,Revenue,Community Wellbeing & Social Care,5105636098,13.11.2013,Public Libraries Central,Marketing Costs,200.00,REDACTED PERSONAL DATA
1,Revenue,Community Wellbeing & Social Care,5105635705,08.11.2013,Drug Misuse - Adults,Charges from Independent Providers,120.00,REDACTED PERSONAL DATA
2,Revenue,Childrens Services,5105637261,20.11.2013,Thompson House Tuition Centre (PRU),Professional Services,240.00,* M BOWDERY T/A SPOTLIGHT BOUTIQUE
3,Revenue,Community Wellbeing & Social Care,5105637069,27.11.2013,Safeguarding Adults,Professional Services,"5,285.00",REDACTED PERSONAL DATA
4,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA

read in only certain columns

In [57]:
tmp = pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/sample1.csv', nrows=3, usecols=['Date','Expenses Type','Amount'])
tmp

         Date                       Expenses Type  Amount
0  13.11.2013                     Marketing Costs   200.0
1  08.11.2013  Charges from Independent Providers   120.0
2  20.11.2013               Professional Services   240.0

## Pandas Library

In [ ]:
# Pandas Library

## Notebook 2.2.2 - JSON

In [2]:
import requests # http library to get data from url
import json
import pandas as pd

url = 'http://data.ordnancesurvey.co.uk/datasets/os-linked-data/apis/reconciliation?query=MK7&type=http%3A%2F%2Fdata.ordnancesurvey.co.uk%2Fontology%2Fpostcode%2FPostcodeSector&type_strict=any&limit=10'
response = requests.get(url)
response.content

b'{"result":[{"id":"http:\\/\\/data.ordnancesurvey.co.uk\\/id\\/postcodesector\\/MK76","name":"MK7 6","score":1,"match":true,"type":["http:\\/\\/data.ordnancesurvey.co.uk\\/ontology\\/postcode\\/PostcodeSector"]},{"id":"http:\\/\\/data.ordnancesurvey.co.uk\\/id\\/postcodesector\\/MK77","name":"MK7 7","score":1,"match":false,"type":["http:\\/\\/data.ordnancesurvey.co.uk\\/ontology\\/postcode\\/PostcodeSector"]},{"id":"http:\\/\\/data.ordnancesurvey.co.uk\\/id\\/postcodesector\\/MK78","name":"MK7 8","score":1,"match":false,"type":["http:\\/\\/data.ordnancesurvey.co.uk\\/ontology\\/postcode\\/PostcodeSector"]}]}'

response starts with b so needs to be converted from bytes to string

In [3]:
data = json.loads(response.content.decode('UTF8'))
data

{'result': [{'id': 'http://data.ordnancesurvey.co.uk/id/postcodesector/MK76',
   'match': True,
   'name': 'MK7 6',
   'score': 1,
   'type': ['http://data.ordnancesurvey.co.uk/ontology/postcode/PostcodeSector']},
  {'id': 'http://data.ordnancesurvey.co.uk/id/postcodesector/MK77',
   'match': False,
   'name': 'MK7 7',
   'score': 1,
   'type': ['http://data.ordnancesurvey.co.uk/ontology/postcode/PostcodeSector']},
  {'id': 'http://data.ordnancesurvey.co.uk/id/postcodesector/MK78',
   'match': False,
   'name': 'MK7 8',
   'score': 1,
   'type': ['http://data.ordnancesurvey.co.uk/ontology/postcode/PostcodeSector']}]}

In [4]:
# use the json_normalize function to create DF from data
from pandas.io.json import json_normalize

json_normalize(data['result'])

,id,match,name,score,type
0,http://data.ordnancesurvey.co.uk/id/postcodese...,True,MK7 6,1,[http://data.ordnancesurvey.co.uk/ontology/pos...
1,http://data.ordnancesurvey.co.uk/id/postcodese...,False,MK7 7,1,[http://data.ordnancesurvey.co.uk/ontology/pos...
2,http://data.ordnancesurvey.co.uk/id/postcodese...,False,MK7 8,1,[http://data.ordnancesurvey.co.uk/ontology/pos...

### Pandas read_json

In [9]:
rows = ['pid', 'title', 'short_synopsis', 'long_synopsis', 'first_broadcast_data']
tmp = pd.io.json.read_json('http://www.bbc.co.uk/programmes/p01ztvcp.json').loc[rows]
tmp

                                                              programme
pid                                                            p01ztvcp
title                                     Privacy or Freedom of Speech?
short_synopsis        The Court of Justice of the European Union rul...
long_synopsis         The case of Mario Costeja Gonzalez, a Spaniard...
first_broadcast_data                                                NaN

### Save to JSON

In [11]:
tmp.to_json('data/tmp_snowkuma.json')
# !head data/tmp_snowkuma.json
pd.io.json.read_json('data/tmp_snowkuma.json')

                                                              programme
first_broadcast_data                                               None
long_synopsis         The case of Mario Costeja Gonzalez, a Spaniard...
pid                                                            p01ztvcp
short_synopsis        The Court of Justice of the European Union rul...
title                                     Privacy or Freedom of Speech?

## Other file formats
### Spreadsheet files (XLS / XLSX)

In [12]:
import pandas as pd
# try reading in directly
xl = pd.read_excel('data/tfl-buses-type.xls', sheetname=None) # sheetname none means we get all sheets
xl.keys()

odict_keys(['Metadata', 'Data'])

In [13]:
xl['Data'][:3]

,,Number of buses,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
Bus Type,Drive train type,2010.0,2011.0,2012.0,2013.0,2014.0
New Routemaster,Hybrid,0.0,0.0,5.0,8.0,168.0
Routemaster,Diesel,18.0,18.0,19.0,20.0,19.0

Or we can read in by  sheetname

In [15]:
pd.read_excel('data/tfl-buses-type.xls', sheetname='Data')[:3]

,,Number of buses,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
Bus Type,Drive train type,2010.0,2011.0,2012.0,2013.0,2014.0
New Routemaster,Hybrid,0.0,0.0,5.0,8.0,168.0
Routemaster,Diesel,18.0,18.0,19.0,20.0,19.0

It looks ok so get whole sheet

In [16]:
data = pd.read_excel('data/tfl-buses-type.xls', sheetname='Data')
data

                                                                     Number of buses  \
Bus Type                                           Drive train type           2010.0
New Routemaster                                    Hybrid                        0.0
Routemaster                                        Diesel                       18.0
Artic                                              Diesel                      320.0
Single deck                                        Diesel                     2676.0
NaN                                                Fuel Cell/Hybrid              0.0
                                                   Hybrid                       27.0
                                                   Electric                      0.0
Double deck                                        Diesel                     5554.0
NaN                                                Hybrid                       29.0
TOTAL                                              NaN                        8624.0
NaN                                                NaN                           NaN
                                                   NaN                           NaN
Commentary: The figures supplied reflect the fl... NaN                           NaN

                                                                     Unnamed: 1  \
Bus Type                                           Drive train type      2011.0
New Routemaster                                    Hybrid                   0.0
Routemaster                                        Diesel                  18.0
Artic                                              Diesel                 260.0
Single deck                                        Diesel                2670.0
NaN                                                Fuel Cell/Hybrid         5.0
                                                   Hybrid                  27.0
                                                   Electric                 0.0
Double deck                                        Diesel                5487.0
NaN                                                Hybrid                  79.0
TOTAL                                              NaN                   8546.0
NaN                                                NaN                      NaN
                                                   NaN                      NaN
Commentary: The figures supplied reflect the fl... NaN                      NaN

                                                                     Unnamed: 2  \
Bus Type                                           Drive train type      2012.0
New Routemaster                                    Hybrid                   5.0
Routemaster                                        Diesel                  19.0
Artic                                              Diesel                   0.0
Single deck                                        Diesel                2661.0
NaN                                                Fuel Cell/Hybrid         5.0
                                                   Hybrid                  33.0
                                                   Electric                 0.0
Double deck                                        Diesel                5787.0
NaN                                                Hybrid                 233.0
TOTAL                                              NaN                   8743.0
NaN                                                NaN                      NaN
                                                   NaN                      NaN
Commentary: The figures supplied reflect the fl... NaN                      NaN

                                                                     Unnamed: 3  \
Bus Type                                           Drive train type      2013.0
New Routemaster                                    Hybrid                   8.0
Routemaster                                        Diesel                  20.0
Artic                                              Diesel                   0.0
Single deck                                        Diesel                2608.0
NaN                                                Fuel Cell/Hybrid         5.0
                                                   Hybrid                  28.0
                                                   Electric                 0.0
Double deck                                        Diesel                5696.0
NaN                                                Hybrid                 352.0
TOTAL                                              NaN                   8717.0
NaN                                                NaN                      NaN
                                                   NaN                      NaN
Commentary: The figures supplied reflect the fl... NaN                      NaN

                                                                     Unnamed: 4
Bus Type                                           Drive train type      2014.0
New Routemaster                                    Hybrid                 168.0
Routemaster                                        Diesel                  19.0
Artic                                              Diesel                   0.0
Single deck                                        Diesel                2606.0
NaN                                                Fuel Cell/Hybrid         8.0
                                                   Hybrid                  23.0
                                                   Electric                 2.0
Double deck                                        Diesel                5296.0
NaN                                                Hybrid                 643.0
TOTAL                                              NaN                   8765.0
NaN                                                NaN                      NaN
                                                   NaN                      NaN
Commentary: The figures supplied reflect the fl... NaN                      NaN

### xlrd

provides lower level access to excel file contents

For more details see: http://xlrd.readthedocs.io/en/latest/

In [20]:
import xlrd

workbook = xlrd.open_workbook('data/tfl-buses-type.xls')
# allows us to preview
print(workbook.sheet_names())

['Metadata', 'Data']

In [21]:
sheet = workbook.sheet_by_name('Data')
sheet.cell_value(rowx=14, colx=0)

'Commentary: The figures supplied reflect the fleet as of March 31, 2014. The number of hybrid buses in the fleet which is tracked through the year, unlike other statistics, now stands at around 860 and is projected to rise to 1,700 (of which 600 will be NBfLs) by 2016.'

### XML

Needs to be parsed individually then converted into panda frame.  Can be useful to use openrefien or find a good python Library for parsing.

- lxml
- fastkml

### KML - mapping locations

In [27]:
from fastkml import kml
k = kml.KML()

# open bytestream of carpark data
doc = open('data/CarParks.kml','rb').read()
k.from_string(doc)

# parse the locations of carparks from the file
locations = dict()
for feature in k.features():
    for placemark in feature.features():
        locations.update({placemark.name: (placemark.geometry.y, placemark.geometry.x)})
list(locations)

['Station Avenue, Sandown',
 'New Street, Newport',
 'Vernon Meadow, Shanklin',
 'Fort Street, Sandown',
 'Market Street, Ventnor',
 'St Johns Road, Sandown',
 'Esplanade Gardens, Shanklin',
 'Maresfield Road, East Cowes',
 'Moa place, Freshwater',
 'The Grove, Ventnor',
 'Yaverland, Sandown',
 'Quay Road, Ryde',
 'Sea Street, Newport',
 'County Hall Complex, Newport (Weekends Only)',
 'Lane End, Bembridge',
 'Green Street, Ryde',
 'Spa, Shanklin',
 'Winchester House, Shanklin',
 'St Thomas Street Upper/Lower, Ryde',
 'Newport Harbour, Newport',
 'Colwell Bay, Colwell',
 'Victoria Street, Ryde',
 'Lind Place, Ryde',
 'Seaclose Recreation Ground, Newport',
 'Coppins Bridge, Newport',
 'Pound Lane, Ventnor',
 'La Falaise, Ventnor',
 'Cross Street, Cowes',
 'Atherley Road, Shanklin',
 'Orchardleigh Road, Shanklin',
 'Medina Avenue, Newport',
 'The Duver, Seaview',
 'New Road, Lake',
 'Lugley Street, Newport',
 'River Road, Yarmouth',
 'Chapel Street, Newport',
 'The Duver, St Helens',
 'Shore Road, Bonchurch',
 'Little London, Newport',
 'Brunswick Road, Cowes',
 'Dudley Road, Ventnor',
 'Avenue Road, Freshwater',
 'Church Litten, Newport ',
 'Garfield Road, Ryde',
 'Central (High Street), Ventnor',
 'Freshwater Bay, Freshwater',
 'Mornington Road, Cowes',
 'Eastern Esplanade, Ventnor',
 'Hope Road, Shanklin',
 'Landguard Road, Shanklin']

In [29]:
# now lets quickly map the markers - req internet
import folium # we will look at more in p5

carparks = folium.Map(location=[50.68, -1.2667], width=960, height=500, zoom_start=11)

for name, location in locations.items():
    folium.CircleMarker(location=location,
                       popup=name,
                       radius = 20,
                       fill_color='green',
                       fill_opacity=0.2
                       ).add_to(carparks)
# display the map
carparks

In [30]:
# create an html file for the map
carparks.save('data/snowkuma_carparks.html')

### YAML
No direct support but can use _PyYaml_ to load in file and convert to pydict then DF.

WARNING use safe_load() safe_load_all() to avoid executables

http://pyyaml.org/wiki/PyYAMLDocumentation.

In [31]:
import yaml
# yaml.load() will accept a single document string, and parse it to generate
# a Python dict, so will yaml.safe_load():
document = """
image:
    width: 800
    height: 600
    title:  View from 15th Floor
    thumbnail:
        url: http://www.example.com/image/481989943
        height: 125
        width:  100
        animated : false
    IDs:
        - 116
        - 943
        - 234
        - 38793
"""
parsedYAML = yaml.safe_load(document)
parsedYAML

{'image': {'IDs': [116, 943, 234, 38793],
  'height': 600,
  'thumbnail': {'animated': False,
   'height': 125,
   'url': 'http://www.example.com/image/481989943',
   'width': 100},
  'title': 'View from 15th Floor',
  'width': 800}}

In [32]:
# Here 'document.yaml' contains a single YAML document.
stream = open('data/document.yaml', 'r') 
yaml.safe_load(stream)

{'image': {'IDs': [116, 943, 234, 38793],
  'height': 600,
  'thumbnail': {'animated': False,
   'height': 125,
   'url': 'http://www.example.com/image/481989943',
   'width': 100},
  'title': 'View from 15th Floor',
  'width': 800}}

In [33]:
# We can also cast a dict to YAML using the yaml.dump() function applied to a dict:
print(yaml.dump(parsedYAML))

image:
  IDs: [116, 943, 234, 38793]
  height: 600
  thumbnail: {animated: false, height: 125, url: 'http://www.example.com/image/481989943',
    width: 100}
  title: View from 15th Floor
  width: 800