# EMA Project Notebook
__Name:__ Daniel Smith

__PI:__ A7603242

In [1]:
# import the required libraries
import pandas as pd
import scipy.stats
import numpy as np
import pymongo
import bson
import collections
from matplotlib import pyplot
import seaborn as sns

In [2]:
# make a folder for storing my working files as I go along.
!mkdir -p data/dcs283

In [3]:
!ls data/dcs283

ks2_cleaned.csv

# Contents

Use these links to jump to a section.

[Setting up mongo](#mongo)
[Data preparation](#preparation)
 - [Importing the KS2 data](#importing_ks2)
 - [Importing the KS4 data](#importing_ks4)
 - [OpenRefine](#openrefine)

[Q1, KS4 Investigation](#q1)

[Application of Machine Learning](#machine_learning)

[Q2, KS2 - KS4 Investigation](#q2)

[Cleanup remove the database](#cleanup)

# Setting up mongo
<a name="mongo"></a>

In [4]:
# set up a connection to mongodb server
client = pymongo.MongoClient('mongodb://localhost:27351')

In [5]:
# uncomment to remove the database if needed
client.drop_database('schools_db')
client.database_names()

['accidents', 'admin', 'local']

In [6]:
# setup a schools_db database on mongo
db = client.schools_db

# Data preparation
<a name="preparation"></a>

Before we can investigate the data we will need to have a quick look at it, determine what cleaning, if any, is needed.  Carry out the cleaning and store it for access in tn appropriate form.  

However before doing anything I will import the KS2 data in the same way as was done in `dcs283_TMA02_Question2b-pd`  I will then store the resultant dataframe into mongo for analysis later on.

## Importing the KS2 data
<a name="importing_ks2"></a>

All of this section is the same as in the `TMA02_Question2b-pd` notebook.

***
__ ----------- Beginning of TMA02 code -----------  __

### Import the LEA data

In [7]:
leas_df = pd.read_csv('data/2015-2016/la_and_region_codes_meta.csv')
leas_df.head()

   LEA               LA Name  REGION   REGION NAME
0  841            Darlington       1  North East A
1  840         County Durham       1  North East A
2  805            Hartlepool       1  North East A
3  806         Middlesbrough       1  North East A
4  807  Redcar and Cleveland       1  North East A

### Import the KS2 data
Most of the field names are given in the `ks2_meta` file, so we'll use that to keep track of the types of various columns.

In [8]:
ks2cols = pd.read_csv('data/2015-2016/ks2_meta.csv')
ks2cols['Field Name'] = ks2cols['Field Name'].apply(lambda r: r.strip(),)
ks2cols

,Column,Field Name,Label/Description
0,1,RECTYPE,Record type (1=mainstream school; 2=special sc...
1,2,ALPHAIND,Alphabetic index
2,3,LEA,Local authority number
3,4,ESTAB,Establishment number
4,5,URN,School unique reference number
5,6,SCHNAME,School/Local authority name
6,7,ADDRESS1,School address (1)
7,8,ADDRESS2,School address (2)
8,9,ADDRESS3,School address (3)
9,10,TOWN,School town
10,11,PCODE,School postcode
11,12,TELNUM,School telephone number
12,13,URN_AC,Converter academy: URN
13,14,SCHNAME_AC,Converter academy: name
14,15,OPEN_AC,Converter academy: open date
15,16,NFTYPE,School type
16,17,ICLOSE,Closed Flag
17,18,RELDENOM,Religious denomination
18,19,AGERANGE,Age range
19,20,CONFEXAM,Confirmation flag that core performance inform...
20,21,TAB15,School published in secondary school (key stag...
21,22,TAB1618,School published in school and college (key st...
22,23,TOTPUPS,Total number of pupils (including part-time pu...
23,24,TPUPYEAR,Number of pupils aged 11
24,25,TELIG,Published eligible pupil number
25,26,BELIG,Eligible boys on school roll at time of tests
26,27,GELIG,Eligible girls on school roll at time of tests
27,28,PBELIG,Percentage of eligible boys on school roll at ...
28,29,PGELIG,Percentage of eligible girls on school roll at...
29,30,TKS1AVERAGE,Cohort level key stage 1 average points score
...,...,...,...
229,230,PTGPS_HIGH_M,Percentage of pupils with medium prior attainm...
230,231,PTGPS_HIGH_H,Percentage of pupils with high prior attainmen...
231,232,PTGPS_HIGH_FSM6CLA1A,Percentage of disadvantaged pupils achieving a...
232,233,PTGPS_HIGH_NotFSM6CLA1A,Percentage of non-disadvantaged pupils achievi...
233,234,PTMAT_HIGH_L,Percentage of pupils with low prior attainment...
234,235,PTMAT_HIGH_M,Percentage of pupils with medium prior attainm...
235,236,PTMAT_HIGH_H,Percentage of pupils with high prior attainmen...
236,237,PTMAT_HIGH_FSM6CLA1A,Percentage of disadvantaged pupils achieving a...
237,238,PTMAT_HIGH_NotFSM6CLA1A,Percentage of non-disadvantaged pupils achievi...
238,239,PTWRITTA_HIGH_L,Percentage of pupils with low prior attainment...
239,240,PTWRITTA_HIGH_M,Percentage of pupils with medium prior attainm...
240,241,PTWRITTA_HIGH_H,Percentage of pupils with high prior attainmen...
241,242,PTWRITTA_HIGH_FSM6CLA1A,Percentage of disadvantaged pupils working at ...
242,243,PTWRITTA_HIGH_NotFSM6CLA1A,Percentage of non-disadvantaged pupils working...
243,244,TEALGRP1,Number of eligible pupils with English as firs...
244,245,PTEALGRP1,Percentage of eligible pupils with English as ...
245,246,TEALGRP3,Number of eligible pupils with unclassified la...
246,247,PTEALGRP3,Percentage of eligible pupils with unclassifie...
247,248,TSENELAPK,Number of eligible pupils with SEN without sta...
248,249,PSENELSAPK,Percentage of eligible pupils with SEN without...
249,250,TSENELE,Number of eligible pupils with EHC plan
250,251,PSENELE,Percentage of eligible pupils with EHC plan
251,252,TSENELK,Number of eligible pupils with SEN support
252,253,PSENELK,Percentage of eligible pupils with SEN support
253,254,TSENELST,Number of eligible pupils with SEN (Special Ed...
254,255,PSENELST,Percentage of eligible pupils with SEN (Specia...
255,256,TSENELSAP,Number of eligible pupils with School Action Plus
256,257,PSENELSAP,Percentage of eligible pupils with School Acti...
257,258,SENELN,Number of eligible pupils with SEN (Special Ed...
258,259,PSENELN,Percentage of eligible pupils with SEN (Specia...

Some columns contain integers, but _**pandas**_ will treat any numeric column with `na` values as `float64`, due to NumPy's number type hierarchy.

In [9]:
int_cols = [c for c in ks2cols['Field Name'] 
            if c.startswith('T')
            if c not in ['TOWN', 'TELNUM', 'TKS1AVERAGE']]
int_cols += ['RECTYPE', 'ALPHAIND', 'LEA', 'ESTAB', 'URN', 'URN_AC', 'ICLOSE']
int_cols += ['READ_AVERAGE', 'GPS_AVERAGE', 'MAT_AVERAGE']

Some columns contain percentages. We'll convert these to floating point numbers on import.

Note that we also need to handle the case of `SUPP` and `NEW` in the data.

In [10]:
def p2f(x):
    if x.strip('%').isnumeric():
        return float(x.strip('%'))/100
    elif x in ['SUPP', 'NEW', 'LOWCOV', 'NA', '']:
        return 0.0
    else:
        return x

These are the columns to try to convert from percentages. Note that we can be generous here, as columns like PCODE (postcode) will return the original value if the conversion fails.

In [11]:
percent_cols = [f for f in ks2cols['Field Name'] if f.startswith('P')]
percent_cols += ['WRITCOV', 'MATCOV', 'READCOV'] 
percent_cols += ['PTMAT_HIGH', 'PTREAD_HIGH', 'PSENELSAPK', 'PSENELK', 'PTGPS_HIGH']
percent_converters = {c: p2f for c in percent_cols}

In [12]:
ks2_df = pd.read_csv('data/2015-2016/england_ks2final.csv', 
                   na_values=['SUPP', 'NEW', 'LOWCOV', 'NA', ''],
                   converters=percent_converters)

Drop the summary rows, keeping just the rows for mainstream and special schools.

In [13]:
ks2_df = ks2_df[(ks2_df['RECTYPE'] == 1) | (ks2_df['RECTYPE'] == 2)]

Convert everything to numbers, if possible.

In [14]:
ks2_df = ks2_df.apply(pd.to_numeric, errors='ignore')

Merge the LEA data into the school data

In [15]:
ks2_df = pd.merge(ks2_df, leas_df, on=['LEA'])
ks2_df.head().T

,0,1,2,3,4
RECTYPE,1,1,1,1,1
ALPHAIND,53372,11156,11160,11256,16366
LEA,201,202,202,202,202
ESTAB,3614,3323,3327,2842,2184
URN,100000,100028,100029,130342,100013
SCHNAME,Sir John Cass's Foundation Primary School,"Christ Church Primary School, Hampstead",Christ Church School,Christopher Hatton Primary School,Edith Neville Primary School
ADDRESS1,St James's Passage,Christ Church Hill,Redhill Street,38 Laystall Street,174 Ossulston Street
ADDRESS2,Duke's Place,NaN,Camden,NaN,NaN
ADDRESS3,NaN,NaN,NaN,NaN,NaN
TOWN,London,London,London,London,London
PCODE,EC3A 5DE,NW3 1JH,NW1 4BD,EC1R 4PQ,NW1 1DN
TELNUM,0207 2831147,0207 4351361,0207 3877881,0207 2784500,0207 3877158
URN_AC,0,0,0,0,0
SCHNAME_AC,NaN,NaN,NaN,NaN,NaN
OPEN_AC,NaN,NaN,NaN,NaN,NaN
NFTYPE,VA,VA,VA,CY,CY
ICLOSE,0,0,0,0,0
RELDENOM,Church of England,Church of England,Church of England,Does not apply,Does not apply
AGERANGE,3-11,4-11,3-11,3-11,3-11
CONFEXAM,NaN,NaN,NaN,NaN,NaN
TAB15,0,0,0,0,0
TAB1618,0,0,0,0,0
TOTPUPS,250,181,229,233,221
TPUPYEAR,28,23,29,28,29
TELIG,28,21,28,28,29
BELIG,16,16,17,16,9
GELIG,12,5,11,12,20
PBELIG,0.57,0.76,0.61,0.57,0.31
PGELIG,0.43,0.24,0.39,0.43,0.69
TKS1AVERAGE,16,16.7,14,16,14.5
...,...,...,...,...,...
PTGPS_HIGH_NotFSM6CLA1A,0.31,0,0.27,0.5,0.56
PTMAT_HIGH_L,0,0,0,0,0
PTMAT_HIGH_M,0.15,0.25,0.16,0.12,0.32
PTMAT_HIGH_H,0.33,0.83,0,0.29,0
PTMAT_HIGH_FSM6CLA1A,0.08,0,0.12,0.17,0.25
PTMAT_HIGH_NotFSM6CLA1A,0.25,0,0.18,0.25,0.44
PTWRITTA_HIGH_L,0,0,0,0,0
PTWRITTA_HIGH_M,0.05,0.33,0.11,0.06,0.09
PTWRITTA_HIGH_H,0.5,0.83,0,0.57,0
PTWRITTA_HIGH_FSM6CLA1A,0,0,0.18,0.17,0.1
PTWRITTA_HIGH_NotFSM6CLA1A,0.25,0,0.09,0.19,0.11
TEALGRP1,10,7,13,11,0
PTEALGRP1,0.36,0.33,0.46,0.39,0
TEALGRP3,0,0,0,0,0
PTEALGRP3,0,0,0,0,0
TSENELAPK,5,2,6,5,11
PSENELSAPK,0.18,0.1,0.21,0.18,0.38
TSENELE,0,0,1,0,0
PSENELE,0,0,0.04,0,0
TSENELK,5,2,6,5,11
PSENELK,0.18,0.1,0.21,0.18,0.38
TSENELST,0,0,0,0,0
PSENELST,0,0,0,0,0
TSENELSAP,0,0,0,0,0
PSENELSAP,0,0,0,0,0
SENELN,0,0,0,0,0
PSENELN,0,0,0,0,0
LA Name,City of London,Camden,Camden,Camden,Camden
REGION,32,31,31,31,31
REGION NAME,London East,London Central,London Central,London Central,London Central

__ ----------- END of TMA02 code -----------  __
***

### Convert and store the KS2 dataframe into Mongo for use later

In [16]:
# set up a collection for the ks2 results dataframe
ks2 = db.ks2_results

In [17]:
# convert the dataframe into a list of dicts and store in Mongo

# the 'results' argument is needed to get a list of dicts
ks2.insert_many(ks2_df.to_dict('records'))

# snippet reference is from:
# https://stackoverflow.com/questions/33979983/insert-rows-from-pandas-dataframe-into-mongodb-collection-as-individual-document

In [18]:
# check we got them all
ks2.find().count(), len(ks2_df)

(16162, 16162)

In [19]:
ks2.find_one()

{'ADDRESS1': "St James's Passage",
 'ADDRESS2': "Duke's Place",
 'ADDRESS3': nan,
 'AGERANGE': '3-11',
 'ALPHAIND': 53372.0,
 'BELIG': 16.0,
 'CONFEXAM': nan,
 'DIFFN_MATPROG': 2.7,
 'DIFFN_READPROG': 0.6,
 'DIFFN_RWM_EXP': 23.0,
 'DIFFN_RWM_HIGH': -7.0,
 'DIFFN_WRITPROG': 0.2,
 'ESTAB': 3614.0,
 'GELIG': 12.0,
 'GPS_AVERAGE': 106.0,
 'GPS_AVERAGE_FSM6CLA1A': 105.0,
 'GPS_AVERAGE_H': 110.0,
 'GPS_AVERAGE_L': nan,
 'GPS_AVERAGE_M': 105.0,
 'GPS_AVERAGE_NotFSM6CLA1A': 107.0,
 'ICLOSE': 0.0,
 'LA Name': 'City of London',
 'LEA': 201.0,
 'MATCOV': 1.0,
 'MATPROG': 3.0,
 'MATPROG_B': 2.9,
 'MATPROG_B_LOWER': 0.3,
 'MATPROG_B_UPPER': 5.5,
 'MATPROG_EAL': 3.1,
 'MATPROG_EAL_LOWER': 0.6,
 'MATPROG_EAL_UPPER': 5.6,
 'MATPROG_FSM6CLA1A': 2.9,
 'MATPROG_FSM6CLA1A_LOWER': -0.1,
 'MATPROG_FSM6CLA1A_UPPER': 5.9,
 'MATPROG_G': 3.1,
 'MATPROG_G_LOWER': 0.1,
 'MATPROG_G_UPPER': 6.1,
 'MATPROG_H': 0.4,
 'MATPROG_H_LOWER': -3.9,
 'MATPROG_H_UPPER': 4.7,
 'MATPROG_L': nan,
 'MATPROG_LOWER': 1.0,
 'MATPROG_L_LOWER': nan,
 'MATPROG_L_UPPER': nan,
 'MATPROG_M': 3.3,
 'MATPROG_MOBN': 3.0,
 'MATPROG_MOBN_LOWER': 1.0,
 'MATPROG_MOBN_UPPER': 5.0,
 'MATPROG_M_LOWER': 1.0,
 'MATPROG_M_UPPER': 5.6,
 'MATPROG_NotFSM6CLA1A': 3.0,
 'MATPROG_NotFSM6CLA1A_LOWER': 0.4,
 'MATPROG_NotFSM6CLA1A_UPPER': 5.6,
 'MATPROG_UPPER': 5.0,
 'MAT_AVERAGE': 106.0,
 'MAT_AVERAGE_FSM6CLA1A': 106.0,
 'MAT_AVERAGE_H': 108.0,
 'MAT_AVERAGE_L': nan,
 'MAT_AVERAGE_M': 106.0,
 'MAT_AVERAGE_NotFSM6CLA1A': 107.0,
 'NFTYPE': 'VA',
 'OPEN_AC': nan,
 'PBELIG': 0.57,
 'PCODE': 'EC3A 5DE',
 'PGELIG': 0.43,
 'PSENELE': 0.0,
 'PSENELK': 0.18,
 'PSENELN': 0.0,
 'PSENELSAP': 0.0,
 'PSENELSAPK': 0.18,
 'PSENELSE': 0.0,
 'PSENELST': 0.0,
 'PTEALGRP1': 0.36,
 'PTEALGRP2': 0.64,
 'PTEALGRP3': 0.0,
 'PTFSM6CLA1A': 0.43,
 'PTGPS_AT': 0.0,
 'PTGPS_EXP': 0.96,
 'PTGPS_EXP_FSM6CLA1A': 1.0,
 'PTGPS_EXP_H': 1.0,
 'PTGPS_EXP_L': 0.0,
 'PTGPS_EXP_M': 0.95,
 'PTGPS_EXP_NotFSM6CLA1A': 0.94,
 'PTGPS_HIGH': 0.18,
 'PTGPS_HIGH_FSM6CLA1A': 0.0,
 'PTGPS_HIGH_H': 0.33,
 'PTGPS_HIGH_L': 0.0,
 'PTGPS_HIGH_M': 0.15,
 'PTGPS_HIGH_NotFSM6CLA1A': 0.31,
 'PTKS1GROUP_H': 0.21,
 'PTKS1GROUP_L': 0.07,
 'PTKS1GROUP_M': 0.71,
 'PTKS1GROUP_NA': 0.0,
 'PTMATTA_AD': 0.0,
 'PTMATTA_EXP': 0.96,
 'PTMAT_AT': 0.0,
 'PTMAT_EXP': 1.0,
 'PTMAT_EXP_FSM6CLA1A': 1.0,
 'PTMAT_EXP_H': 1.0,
 'PTMAT_EXP_L': 0.0,
 'PTMAT_EXP_M': 1.0,
 'PTMAT_EXP_NotFSM6CLA1A': 1.0,
 'PTMAT_HIGH': 0.18,
 'PTMAT_HIGH_FSM6CLA1A': 0.08,
 'PTMAT_HIGH_H': 0.33,
 'PTMAT_HIGH_L': 0.0,
 'PTMAT_HIGH_M': 0.15,
 'PTMAT_HIGH_NotFSM6CLA1A': 0.25,
 'PTMOBN': 1.0,
 'PTNotFSM6CLA1A': 0.57,
 'PTREADTA_AD': 0.0,
 'PTREADTA_EXP': 0.93,
 'PTREAD_AT': 0.0,
 'PTREAD_EXP': 0.93,
 'PTREAD_EXP_FSM6CLA1A': 0.92,
 'PTREAD_EXP_H': 1.0,
 'PTREAD_EXP_L': 0.0,
 'PTREAD_EXP_M': 0.9,
 'PTREAD_EXP_NotFSM6CLA1A': 0.94,
 'PTREAD_HIGH': 0.18,
 'PTREAD_HIGH_FSM6CLA1A': 0.08,
 'PTREAD_HIGH_H': 0.67,
 'PTREAD_HIGH_L': 0.0,
 'PTREAD_HIGH_M': 0.05,
 'PTREAD_HIGH_NotFSM6CLA1A': 0.25,
 'PTRWM_EXP': 0.89,
 'PTRWM_EXP_B': 0.88,
 'PTRWM_EXP_EAL': 0.83,
 'PTRWM_EXP_FSM6CLA1A': 0.83,
 'PTRWM_EXP_G': 0.92,
 'PTRWM_EXP_H': 1.0,
 'PTRWM_EXP_L': 0.0,
 'PTRWM_EXP_M': 0.9,
 'PTRWM_EXP_MOBN': 0.89,
 'PTRWM_EXP_NotFSM6CLA1A': 0.94,
 'PTRWM_HIGH': 0.07,
 'PTRWM_HIGH_B': 0.06,
 'PTRWM_HIGH_EAL': 0.11,
 'PTRWM_HIGH_FSM6CLA1A': 0.0,
 'PTRWM_HIGH_G': 0.08,
 'PTRWM_HIGH_H': 0.33,
 'PTRWM_HIGH_L': 0.0,
 'PTRWM_HIGH_M': 0.0,
 'PTRWM_HIGH_MOBN': 0.07,
 'PTRWM_HIGH_NotFSM6CLA1A': 0.13,
 'PTSCITA_AD': 0.0,
 'PTSCITA_EXP': 1.0,
 'PTWRITTA_AD': 0.0,
 'PTWRITTA_EXP': 0.96,
 'PTWRITTA_EXP_FSM6CLA1A': 0.92,
 'PTWRITTA_EXP_H': 1.0,
 'PTWRITTA_EXP_L': 0.0,
 'PTWRITTA_EXP_M': 1.0,
 'PTWRITTA_EXP_NotFSM6CLA1A': 1.0,
 'PTWRITTA_HIGH': 0.14,
 'PTWRITTA_HIGH_FSM6CLA1A': 0.0,
 'PTWRITTA_HIGH_H': 0.5,
 'PTWRITTA_HIGH_L': 0.0,
 'PTWRITTA_HIGH_M': 0.05,
 'PTWRITTA_HIGH_NotFSM6CLA1A': 0.25,
 'PTWRITTA_WTS': 0.04,
 'READCOV': 1.0,
 'READPROG': 2.7,
 'READPROG_B': 1.0,
 'READPROG_B_LOWER': -2.1,
 'READPROG_B_UPPER': 4.1,
 'READPROG_EAL': 2.5,
 'READPROG_EAL_LOWER': -0.4,
 'READPROG_EAL_UPPER': 5.4,
 'READPROG_FSM6CLA1A': 0.9,
 'READPROG_FSM6CLA1A_LOWER': -2.7,
 'READPROG_FSM6CLA1A_UPPER': 4.5,
 'READPROG_G': 4.9,
 'READPROG_G_LOWER': 1.3,
 'READPROG_G_UPPER': 8.5,
 'READPROG_H': 2.8,
 'READPROG_H_LOWER': -2.2,
 'READPROG_H_UPPER': 7.8,
 'READPROG_L': nan,
 'READPROG_LOWER': 0.4,
 'READPROG_L_LOWER': nan,
 'READPROG_L_UPPER': nan,
 'READPROG_M': 1.9,
 'READPROG_MOBN': 2.7,
 'READPROG_MOBN_LOWER': 0.4,
 'READPROG_MOBN_UPPER': 5.0,
 'READPROG_M_LOWER': -0.9,
 'READPROG_M_UPPER': 4.7,
 'READPROG_NotFSM6CLA1A': 4.0,
 'READPROG_NotFSM6CLA1A_LOWER': 0.9,
 'READPROG_NotFSM6CLA1A_UPPER': 7.1,
 'READPROG_UPPER': 5.0,
 'READ_AVERAGE': 106.0,
 'READ_AVERAGE_FSM6CLA1A': 104.0,
 'READ_AVERAGE_H': 111.0,
 'READ_AVERAGE_L': nan,
 'READ_AVERAGE_M': 104.0,
 'READ_AVERAGE_NotFSM6CLA1A': 107.0,
 'RECTYPE': 1,
 'REGION': 32,
 'REGION NAME': 'London East',
 'RELDENOM': 'Church of England',
 'SCHNAME': "Sir John Cass's Foundation Primary School",
 'SCHNAME_AC': nan,
 'SENELN': 0.0,
 'TAB15': 0.0,
 'TAB1618': 0.0,
 'TEALGRP1': 10.0,
 'TEALGRP2': 18.0,
 'TEALGRP3': 0.0,
 'TELIG': 28.0,
 'TELNUM': '0207 2831147',
 'TFSM6CLA1A': 12.0,
 'TKS1AVERAGE': 16.0,
 'TKS1GROUP_H': 6.0,
 'TKS1GROUP_L': 2.0,
 'TKS1GROUP_M': 20.0,
 'TKS1GROUP_NA': 0.0,
 'TMOBN': 28.0,
 'TNotFSM6CLA1A': 16.0,
 'TOTPUPS': 250.0,
 'TOWN': 'London',
 'TPUPYEAR': 28.0,
 'TSENELAPK': 5.0,
 'TSENELE': 0.0,
 'TSENELK': 5.0,
 'TSENELSAP': 0.0,
 'TSENELSE': 0.0,
 'TSENELST': 0.0,
 'URN': 100000.0,
 'URN_AC': 0.0,
 'WRITCOV': 1.0,
 'WRITPROG': 2.2,
 'WRITPROG_B': 1.3,
 'WRITPROG_B_LOWER': -1.8,
 'WRITPROG_B_UPPER': 4.4,
 'WRITPROG_EAL': 2.3,
 'WRITPROG_EAL_LOWER': -0.6,
 'WRITPROG_EAL_UPPER': 5.2,
 'WRITPROG_FSM6CLA1A': 0.3,
 'WRITPROG_FSM6CLA1A_LOWER': -3.3,
 'WRITPROG_FSM6CLA1A_UPPER': 3.9,
 'WRITPROG_G': 3.4,
 'WRITPROG_G_LOWER': -0.2,
 'WRITPROG_G_UPPER': 7.0,
 'WRITPROG_H': 2.2,
 'WRITPROG_H_LOWER': -2.8,
 'WRITPROG_H_UPPER': 7.2,
 'WRITPROG_L': nan,
 'WRITPROG_LOWER': -0.1,
 'WRITPROG_L_LOWER': nan,
 'WRITPROG_L_UPPER': nan,
 'WRITPROG_M': 2.0,
 'WRITPROG_MOBN': 2.2,
 'WRITPROG_MOBN_LOWER': -0.1,
 'WRITPROG_MOBN_UPPER': 4.5,
 'WRITPROG_M_LOWER': -0.8,
 'WRITPROG_M_UPPER': 4.8,
 'WRITPROG_NotFSM6CLA1A': 3.6,
 'WRITPROG_NotFSM6CLA1A_LOWER': 0.5,
 'WRITPROG_NotFSM6CLA1A_UPPER': 6.7,
 'WRITPROG_UPPER': 4.5,
 '_id': ObjectId('5b0c7ee60fd01f09d8fcaf6e')}

In [20]:
## Initial look at the KS4 results dataset

In [21]:
ks2.find_one()['GPS_AVERAGE_L']

nan

In [22]:
ks2.find({'GPS_AVERAGE_L': np.nan}).count()

11940

Looks good.  We will need to watch out for the NaN values though.

In [23]:
ks2.find({'GPS_AVERAGE_L': np.nan}).count()

11940

In [24]:
ks2.find_one()

{'ADDRESS1': "St James's Passage",
 'ADDRESS2': "Duke's Place",
 'ADDRESS3': nan,
 'AGERANGE': '3-11',
 'ALPHAIND': 53372.0,
 'BELIG': 16.0,
 'CONFEXAM': nan,
 'DIFFN_MATPROG': 2.7,
 'DIFFN_READPROG': 0.6,
 'DIFFN_RWM_EXP': 23.0,
 'DIFFN_RWM_HIGH': -7.0,
 'DIFFN_WRITPROG': 0.2,
 'ESTAB': 3614.0,
 'GELIG': 12.0,
 'GPS_AVERAGE': 106.0,
 'GPS_AVERAGE_FSM6CLA1A': 105.0,
 'GPS_AVERAGE_H': 110.0,
 'GPS_AVERAGE_L': nan,
 'GPS_AVERAGE_M': 105.0,
 'GPS_AVERAGE_NotFSM6CLA1A': 107.0,
 'ICLOSE': 0.0,
 'LA Name': 'City of London',
 'LEA': 201.0,
 'MATCOV': 1.0,
 'MATPROG': 3.0,
 'MATPROG_B': 2.9,
 'MATPROG_B_LOWER': 0.3,
 'MATPROG_B_UPPER': 5.5,
 'MATPROG_EAL': 3.1,
 'MATPROG_EAL_LOWER': 0.6,
 'MATPROG_EAL_UPPER': 5.6,
 'MATPROG_FSM6CLA1A': 2.9,
 'MATPROG_FSM6CLA1A_LOWER': -0.1,
 'MATPROG_FSM6CLA1A_UPPER': 5.9,
 'MATPROG_G': 3.1,
 'MATPROG_G_LOWER': 0.1,
 'MATPROG_G_UPPER': 6.1,
 'MATPROG_H': 0.4,
 'MATPROG_H_LOWER': -3.9,
 'MATPROG_H_UPPER': 4.7,
 'MATPROG_L': nan,
 'MATPROG_LOWER': 1.0,
 'MATPROG_L_LOWER': nan,
 'MATPROG_L_UPPER': nan,
 'MATPROG_M': 3.3,
 'MATPROG_MOBN': 3.0,
 'MATPROG_MOBN_LOWER': 1.0,
 'MATPROG_MOBN_UPPER': 5.0,
 'MATPROG_M_LOWER': 1.0,
 'MATPROG_M_UPPER': 5.6,
 'MATPROG_NotFSM6CLA1A': 3.0,
 'MATPROG_NotFSM6CLA1A_LOWER': 0.4,
 'MATPROG_NotFSM6CLA1A_UPPER': 5.6,
 'MATPROG_UPPER': 5.0,
 'MAT_AVERAGE': 106.0,
 'MAT_AVERAGE_FSM6CLA1A': 106.0,
 'MAT_AVERAGE_H': 108.0,
 'MAT_AVERAGE_L': nan,
 'MAT_AVERAGE_M': 106.0,
 'MAT_AVERAGE_NotFSM6CLA1A': 107.0,
 'NFTYPE': 'VA',
 'OPEN_AC': nan,
 'PBELIG': 0.57,
 'PCODE': 'EC3A 5DE',
 'PGELIG': 0.43,
 'PSENELE': 0.0,
 'PSENELK': 0.18,
 'PSENELN': 0.0,
 'PSENELSAP': 0.0,
 'PSENELSAPK': 0.18,
 'PSENELSE': 0.0,
 'PSENELST': 0.0,
 'PTEALGRP1': 0.36,
 'PTEALGRP2': 0.64,
 'PTEALGRP3': 0.0,
 'PTFSM6CLA1A': 0.43,
 'PTGPS_AT': 0.0,
 'PTGPS_EXP': 0.96,
 'PTGPS_EXP_FSM6CLA1A': 1.0,
 'PTGPS_EXP_H': 1.0,
 'PTGPS_EXP_L': 0.0,
 'PTGPS_EXP_M': 0.95,
 'PTGPS_EXP_NotFSM6CLA1A': 0.94,
 'PTGPS_HIGH': 0.18,
 'PTGPS_HIGH_FSM6CLA1A': 0.0,
 'PTGPS_HIGH_H': 0.33,
 'PTGPS_HIGH_L': 0.0,
 'PTGPS_HIGH_M': 0.15,
 'PTGPS_HIGH_NotFSM6CLA1A': 0.31,
 'PTKS1GROUP_H': 0.21,
 'PTKS1GROUP_L': 0.07,
 'PTKS1GROUP_M': 0.71,
 'PTKS1GROUP_NA': 0.0,
 'PTMATTA_AD': 0.0,
 'PTMATTA_EXP': 0.96,
 'PTMAT_AT': 0.0,
 'PTMAT_EXP': 1.0,
 'PTMAT_EXP_FSM6CLA1A': 1.0,
 'PTMAT_EXP_H': 1.0,
 'PTMAT_EXP_L': 0.0,
 'PTMAT_EXP_M': 1.0,
 'PTMAT_EXP_NotFSM6CLA1A': 1.0,
 'PTMAT_HIGH': 0.18,
 'PTMAT_HIGH_FSM6CLA1A': 0.08,
 'PTMAT_HIGH_H': 0.33,
 'PTMAT_HIGH_L': 0.0,
 'PTMAT_HIGH_M': 0.15,
 'PTMAT_HIGH_NotFSM6CLA1A': 0.25,
 'PTMOBN': 1.0,
 'PTNotFSM6CLA1A': 0.57,
 'PTREADTA_AD': 0.0,
 'PTREADTA_EXP': 0.93,
 'PTREAD_AT': 0.0,
 'PTREAD_EXP': 0.93,
 'PTREAD_EXP_FSM6CLA1A': 0.92,
 'PTREAD_EXP_H': 1.0,
 'PTREAD_EXP_L': 0.0,
 'PTREAD_EXP_M': 0.9,
 'PTREAD_EXP_NotFSM6CLA1A': 0.94,
 'PTREAD_HIGH': 0.18,
 'PTREAD_HIGH_FSM6CLA1A': 0.08,
 'PTREAD_HIGH_H': 0.67,
 'PTREAD_HIGH_L': 0.0,
 'PTREAD_HIGH_M': 0.05,
 'PTREAD_HIGH_NotFSM6CLA1A': 0.25,
 'PTRWM_EXP': 0.89,
 'PTRWM_EXP_B': 0.88,
 'PTRWM_EXP_EAL': 0.83,
 'PTRWM_EXP_FSM6CLA1A': 0.83,
 'PTRWM_EXP_G': 0.92,
 'PTRWM_EXP_H': 1.0,
 'PTRWM_EXP_L': 0.0,
 'PTRWM_EXP_M': 0.9,
 'PTRWM_EXP_MOBN': 0.89,
 'PTRWM_EXP_NotFSM6CLA1A': 0.94,
 'PTRWM_HIGH': 0.07,
 'PTRWM_HIGH_B': 0.06,
 'PTRWM_HIGH_EAL': 0.11,
 'PTRWM_HIGH_FSM6CLA1A': 0.0,
 'PTRWM_HIGH_G': 0.08,
 'PTRWM_HIGH_H': 0.33,
 'PTRWM_HIGH_L': 0.0,
 'PTRWM_HIGH_M': 0.0,
 'PTRWM_HIGH_MOBN': 0.07,
 'PTRWM_HIGH_NotFSM6CLA1A': 0.13,
 'PTSCITA_AD': 0.0,
 'PTSCITA_EXP': 1.0,
 'PTWRITTA_AD': 0.0,
 'PTWRITTA_EXP': 0.96,
 'PTWRITTA_EXP_FSM6CLA1A': 0.92,
 'PTWRITTA_EXP_H': 1.0,
 'PTWRITTA_EXP_L': 0.0,
 'PTWRITTA_EXP_M': 1.0,
 'PTWRITTA_EXP_NotFSM6CLA1A': 1.0,
 'PTWRITTA_HIGH': 0.14,
 'PTWRITTA_HIGH_FSM6CLA1A': 0.0,
 'PTWRITTA_HIGH_H': 0.5,
 'PTWRITTA_HIGH_L': 0.0,
 'PTWRITTA_HIGH_M': 0.05,
 'PTWRITTA_HIGH_NotFSM6CLA1A': 0.25,
 'PTWRITTA_WTS': 0.04,
 'READCOV': 1.0,
 'READPROG': 2.7,
 'READPROG_B': 1.0,
 'READPROG_B_LOWER': -2.1,
 'READPROG_B_UPPER': 4.1,
 'READPROG_EAL': 2.5,
 'READPROG_EAL_LOWER': -0.4,
 'READPROG_EAL_UPPER': 5.4,
 'READPROG_FSM6CLA1A': 0.9,
 'READPROG_FSM6CLA1A_LOWER': -2.7,
 'READPROG_FSM6CLA1A_UPPER': 4.5,
 'READPROG_G': 4.9,
 'READPROG_G_LOWER': 1.3,
 'READPROG_G_UPPER': 8.5,
 'READPROG_H': 2.8,
 'READPROG_H_LOWER': -2.2,
 'READPROG_H_UPPER': 7.8,
 'READPROG_L': nan,
 'READPROG_LOWER': 0.4,
 'READPROG_L_LOWER': nan,
 'READPROG_L_UPPER': nan,
 'READPROG_M': 1.9,
 'READPROG_MOBN': 2.7,
 'READPROG_MOBN_LOWER': 0.4,
 'READPROG_MOBN_UPPER': 5.0,
 'READPROG_M_LOWER': -0.9,
 'READPROG_M_UPPER': 4.7,
 'READPROG_NotFSM6CLA1A': 4.0,
 'READPROG_NotFSM6CLA1A_LOWER': 0.9,
 'READPROG_NotFSM6CLA1A_UPPER': 7.1,
 'READPROG_UPPER': 5.0,
 'READ_AVERAGE': 106.0,
 'READ_AVERAGE_FSM6CLA1A': 104.0,
 'READ_AVERAGE_H': 111.0,
 'READ_AVERAGE_L': nan,
 'READ_AVERAGE_M': 104.0,
 'READ_AVERAGE_NotFSM6CLA1A': 107.0,
 'RECTYPE': 1,
 'REGION': 32,
 'REGION NAME': 'London East',
 'RELDENOM': 'Church of England',
 'SCHNAME': "Sir John Cass's Foundation Primary School",
 'SCHNAME_AC': nan,
 'SENELN': 0.0,
 'TAB15': 0.0,
 'TAB1618': 0.0,
 'TEALGRP1': 10.0,
 'TEALGRP2': 18.0,
 'TEALGRP3': 0.0,
 'TELIG': 28.0,
 'TELNUM': '0207 2831147',
 'TFSM6CLA1A': 12.0,
 'TKS1AVERAGE': 16.0,
 'TKS1GROUP_H': 6.0,
 'TKS1GROUP_L': 2.0,
 'TKS1GROUP_M': 20.0,
 'TKS1GROUP_NA': 0.0,
 'TMOBN': 28.0,
 'TNotFSM6CLA1A': 16.0,
 'TOTPUPS': 250.0,
 'TOWN': 'London',
 'TPUPYEAR': 28.0,
 'TSENELAPK': 5.0,
 'TSENELE': 0.0,
 'TSENELK': 5.0,
 'TSENELSAP': 0.0,
 'TSENELSE': 0.0,
 'TSENELST': 0.0,
 'URN': 100000.0,
 'URN_AC': 0.0,
 'WRITCOV': 1.0,
 'WRITPROG': 2.2,
 'WRITPROG_B': 1.3,
 'WRITPROG_B_LOWER': -1.8,
 'WRITPROG_B_UPPER': 4.4,
 'WRITPROG_EAL': 2.3,
 'WRITPROG_EAL_LOWER': -0.6,
 'WRITPROG_EAL_UPPER': 5.2,
 'WRITPROG_FSM6CLA1A': 0.3,
 'WRITPROG_FSM6CLA1A_LOWER': -3.3,
 'WRITPROG_FSM6CLA1A_UPPER': 3.9,
 'WRITPROG_G': 3.4,
 'WRITPROG_G_LOWER': -0.2,
 'WRITPROG_G_UPPER': 7.0,
 'WRITPROG_H': 2.2,
 'WRITPROG_H_LOWER': -2.8,
 'WRITPROG_H_UPPER': 7.2,
 'WRITPROG_L': nan,
 'WRITPROG_LOWER': -0.1,
 'WRITPROG_L_LOWER': nan,
 'WRITPROG_L_UPPER': nan,
 'WRITPROG_M': 2.0,
 'WRITPROG_MOBN': 2.2,
 'WRITPROG_MOBN_LOWER': -0.1,
 'WRITPROG_MOBN_UPPER': 4.5,
 'WRITPROG_M_LOWER': -0.8,
 'WRITPROG_M_UPPER': 4.8,
 'WRITPROG_NotFSM6CLA1A': 3.6,
 'WRITPROG_NotFSM6CLA1A_LOWER': 0.5,
 'WRITPROG_NotFSM6CLA1A_UPPER': 6.7,
 'WRITPROG_UPPER': 4.5,
 '_id': ObjectId('5b0c7ee60fd01f09d8fcaf6e')}

In [25]:
# to save resources we can now remove delete the ks2_df
del ks2_df

## Importing the KS4 results dataset
<a name="importing_ks4"></a>

Before we can investigate the data we will need to have a look at it, determine what cleaning if any needs to be done, and store it for access in an appropriate form.

### Initial look at the KS4 results dataset
Let's have a quick look at the data we will be looking at for the EMA.

In [26]:
!head -5 'data/2015-2016/england_ks4final.csv'

In [27]:
!wc -l 'data/2015-2016/england_ks4final.csv'

5489 data/2015-2016/england_ks4final.csv

The dataset has 5489 rows of data, there appears to be a large number of columns and a lot of codes that I'll need to look up.  There are a also a number of `NA` and `NP` values that could be missing data.  As well as this results data I will need to find and import the relevent metadata file.

Looking through the data/2015-2016 folder there are a number of files that have information on these codes.

In [28]:
!ls data/2015-2016/

abbreviations.xlsx	    england_swf.csv
abs_meta.csv		    england_vaqual.csv
census_meta.csv		    england_vasubj.csv
england_abs.csv		    keto_setup.xlsx
england_census.csv	    ks2_meta.csv
england_cfrfull.xlsx	    ks4_meta.csv
england_ks2final.csv	    ks4_meta_methodology.csv
england_ks4final.csv	    ks4-pupdest_meta.csv
england_ks4-pupdest.csv     ks5_meta.csv
england_ks4underlying.xlsx  ks5-studest_meta.csv
england_ks5final.csv	    la_and_region_codes_meta.csv
england_ks5-studest.csv     sixth_form_centres_and_consortia_meta.xlsx
england_ks5underlying.xlsx  spine_meta.csv
england_spine.csv	    swf_meta.csv

There is an abbreviations file, stored as an xlsx file.  I'll have a quick glance at it in excel.  Having looked the abbreviation up in the abbreviations file we can see that they have the following meanings:

- _NA_: Not applicable
- _NP_: Not Published
- _NE_: No entries
- _SUPP_: Suppressed (5 or fewer in cohort)
- _LOWCOV_: Low coverage (less than 50% of the cohort
- _NEW_: New institution

The abbreviations file also has listings of all the school types (NFTYPE) that I will need.  I'll grab that for use later on.

## Importing the abbreviations file

In [29]:
# read in the abbreviations file
abbr_df = pd.read_excel('data/2015-2016/abbreviations.xlsx')
abbr_df

,2016 KS4 and KS5/16-18 Performance Tables,Unnamed: 1,Unnamed: 2
0,Abbreviations used in the csv and excel Downlo...,NaN,NaN
1,NaN,NaN,NaN
2,Institution type (NFTYPE):,NaN,NaN
3,AC,Sponsored academy,NaN
4,ACC,Academy converter - mainstream,NaN
5,AC1619,Academy 16-19 sponsor led,NaN
6,ACC1619,Academy 16-19 converter,NaN
7,ACCS,Academy converter - special school,NaN
8,ACS,Sponsored special academy,NaN
9,CTC,City technology college,NaN
10,CY,Community school,NaN
11,CYS,Community special school,NaN
12,F,Free school - mainstream,NaN
13,FESI,Further Education Sector Institution,NaN
14,FD,Foundation school,NaN
15,FDS,Foundation special school,NaN
16,FS,Free school - special,NaN
17,FSS,Studio school,NaN
18,FUTC,UTC (university technical college),NaN
19,F1619,Free school - 16-19,NaN
20,IND,Independent school,NaN
21,INDSPEC,Independent special school,NaN
22,MODFC,College funded by Ministry of Defence,NaN
23,NMSS,Non-maintained special school,NaN
24,VA,Voluntary aided school,NaN
25,VC,Voluntary controlled school,NaN
26,NaN,NaN,NaN
27,Types of further education (FE) institutions:,NaN,NaN
28,Agriculture and horticultural college,NaN,NaN
29,"Art, design and performing arts college",NaN,NaN
30,General further education college,NaN,NaN
31,General further education college (special),NaN,NaN
32,Sixth form college,NaN,NaN
33,Specialist designated college,NaN,NaN
34,Tertiary college,NaN,NaN
35,NaN,NaN,NaN
36,Admissions policy (ADMPOL):,NaN,NaN
37,COMP,Comprehensive,NaN
38,MOD,Modern,NaN
39,SEL,Selective,NaN
40,NA,Not applicable: figures are either not availab...,NaN
41,UK,Unknown,NaN
42,<blank>,Admissions policy information is not available...,NaN
43,NaN,NaN,NaN
44,General abbreviations:,NaN,NaN
45,NEW,New institution,NaN
46,NE,No entries,NaN
47,NaN,Not applicable: figures are either not availab...,NaN
48,SUPP,Indicates that a school or college's figures h...,NaN
49,NP,Not published - for example we do not publish ...,NaN
50,LOWCOV,Low coverage: indicates that a school’s Progre...,NaN
51,NaN,NaN,NaN
52,Notes:,NaN,NaN
53,The 2016 secondary and 16-18 performance table...,NaN,NaN
54,If a school converted to an academy during the...,NaN,NaN
55,The KS4 and KS5 metadata files provide descrip...,NaN,NaN

We can see that the school types are rows 2-25, I'll store them as a dict for reference later on.

In [30]:
# relabel the columns
abbr_df.columns = ['label', 'expanded', 'not_needed']

In [31]:
nftypes = {}
for index, row in abbr_df[3:26].iterrows():
    nftypes[row['label'].strip()] = row['expanded'].strip()
    
nftypes

{'AC': 'Sponsored academy',
 'AC1619': 'Academy 16-19 sponsor led',
 'ACC': 'Academy converter - mainstream',
 'ACC1619': 'Academy 16-19 converter',
 'ACCS': 'Academy converter - special school',
 'ACS': 'Sponsored special academy',
 'CTC': 'City technology college',
 'CY': 'Community school',
 'CYS': 'Community special school',
 'F': 'Free school - mainstream',
 'F1619': 'Free school - 16-19',
 'FD': 'Foundation school',
 'FDS': 'Foundation special school',
 'FESI': 'Further Education Sector Institution',
 'FS': 'Free school - special',
 'FSS': 'Studio school',
 'FUTC': 'UTC (university technical college)',
 'IND': 'Independent school',
 'INDSPEC': 'Independent special school',
 'MODFC': 'College funded by Ministry of Defence',
 'NMSS': 'Non-maintained special school',
 'VA': 'Voluntary aided school',
 'VC': 'Voluntary controlled school'}

And, while we have the abbreviations available I'll store the missing value types for reference later on if needed.

In [32]:
missing_types = {}
for i, r in abbr_df[45:51].iterrows():
    missing_types[r['label']] = r['expanded']

missing_types

{'NEW': 'New institution',
 'NE': 'No entries',
 'SUPP': "Indicates that a school or college's figures have been suppressed because there are 5 or fewer pupils in the cohort",
 'LOWCOV': 'Low coverage: indicates that a school’s Progress 8 or value added measures have been suppressed because coverage is less than 50% of the cohort',
 'NP': 'Not published - for example we do not publish Progress 8 data for independent schools and independent special schools, or breakdowns by disadvantaged and non-disadvantaged pupils for independent schools, independent special schools and non-maintained special schools.',
 nan: 'Not applicable: figures are either not available for the year in question, or the data field is not applicable to this school or college'}

I can now delete the abbr_df as it won't be needed.

In [33]:
del abbr_df

## Importing the KS4 Metadata file

In order to analyse the data we need to be able to reference the columns and the codes they represent.  I'll import the KS4_meta.csv file into the database and use it to help me understand the data in the KS4 results dataset.

In [34]:
!head -5 data/2015-2016/ks4_meta.csv

372,TAVENT_GNFSM6CLA1A_15_PTQ_EE,Average number of GCSE entries per non-disadvantaged pupil in 2015,,,,Yes,,,

In [35]:
!wc -l data/2015-2016/ks4_meta.csv

0 data/2015-2016/ks4_meta.csv

0 lines.. I'll try loding directly into Mongo

In [36]:
!/usr/bin/mongoimport --port 27351 --drop --db schools_db --collection ks4_meta \
    --type csv --headerline --ignoreBlanks \
    --file data/2015-2016/ks4_meta.csv

2018-05-28T22:12:58.545+0000	Failed: fields cannot be identical: '' and ''
2018-05-28T22:12:58.545+0000	imported 0 documents

Clearly there is an issue with the import.  I'll try importing it into a dataframe.

In [37]:
ks4_meta_df = pd.read_csv('data/2015-2016/ks4_meta.csv')
ks4_meta_df.head()

,Column,Metafile heading,Metafile description,Methodology changes,Null field for special schools,Null field for local authority records,Null field for National (all schools) records,Null field for National (maintained schools) records,Unnamed: 8,Unnamed: 9
0,1,RECTYPE,Record type (1=mainstream school; 2=special sc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,ALPHAIND,Alphabetic sorting index,NaN,NaN,Yes,Yes,Yes,NaN,NaN
2,3,LEA,Local authority code (see separate list of loc...,NaN,NaN,NaN,Yes,Yes,NaN,NaN
3,4,ESTAB,Establishment number,NaN,NaN,Yes,Yes,Yes,NaN,NaN
4,5,URN,School Unique Reference Number,NaN,NaN,Yes,Yes,Yes,NaN,NaN

That imported ok.  But there are a few extra columns for my needs (I only need it to look up the description for a given term)

In [38]:
# reduce the dataframe to the columns of interest
ks4_meta_df = ks4_meta_df[['Metafile heading', 'Metafile description']]
# relabel them to match my target format
ks4_meta_df.columns = ['label', 'expanded']
# check it looks ok
ks4_meta_df

,label,expanded
0,RECTYPE,Record type (1=mainstream school; 2=special sc...
1,ALPHAIND,Alphabetic sorting index
2,LEA,Local authority code (see separate list of loc...
3,ESTAB,Establishment number
4,URN,School Unique Reference Number
5,SCHNAME,School name
6,SCHNAME_AC,School now known as (used if the school has co...
7,ADDRESS1,School address (1)
8,ADDRESS2,School address (2)
9,ADDRESS3,School address (3)
10,TOWN,School town
11,PCODE,School postcode
12,TELNUM,School telephone number
13,CONTFLAG,Contingency flag - school results 'significant...
14,ICLOSE,Closed school flag (0=open; 1=closed)
15,NFTYPE,School type (see separate list of abbreviation...
16,RELDENOM,School religious character
17,ADMPOL,School admissions policy (self-declared by sch...
18,EGENDER,School gender of entry
19,FEEDER,Indicates whether school is a feeder school fo...
20,TABKS2,Indicates whether school is published in the p...
21,TAB1618,Indicates whether school is published in the s...
22,AGERANGE,Age range
23,CONFEXAM,Indicates whether the school has checked its r...
24,TOTPUPS,Number of pupils on roll (all ages)
25,NUMBOYS,Total boys on roll (including part-time pupils)
26,NUMGIRLS,Total girls on roll (including part-time pupils)
27,TPUP,Number of pupils at the end of key stage 4
28,BPUP,Number of boys at the end of key stage 4
29,PBPUP,Percentage of pupils at the end of key stage 4...
...,...,...
342,TNOTFSMCLA_14,Number of non-disadvantaged pupils at the end ...
343,PTNOTFSMCLA_14,Percentage of pupils at the end of key stage 4...
344,TFSM6CLA1A_15,Number of disadvantaged pupils at the end of k...
345,PTFSM6CLA1A_15,Percentage of pupils at the end of key stage 4...
346,TNOTFSM6CLA1A_15,Number of non-disadvantaged pupils at the end ...
347,PTNOTFSM6CLA1A_15,Percentage of pupils at the end of key stage 4...
348,TAVENT_E_3NG_PTQ_EE,Average number of GCSE and equivalents entries...
349,TAVENT_E_3NG_LO_PTQ_EE,Average number of GCSE and equivalents entries...
350,TAVENT_E_3NG_AV_PTQ_EE,Average number of GCSE and equivalents entries...
351,TAVENT_E_3NG_HI_PTQ_EE,Average number of GCSE and equivalents entries...
352,TAVENT_E_3NG_FSM6CLA1A_PTQ_EE,Average number of GCSE and equivalents entries...
353,TAVENT_E_3NG_NFSM6CLA1A_PTQ_EE,Average number of GCSE and equivalents entries...
354,TAVENT_EFSM_13,Average number of GCSE and equivalents entries...
355,TAVENT_ENFSM_13,Average number of GCSE and equivalents entries...
356,TAVENT_EFSM_14_PTQ,Average number of GCSE and equivalents entries...
357,TAVENT_ENFSM_14_PTQ,Average number of GCSE and equivalents entries...
358,TAVENT_EFSM6CLA1A_15_PTQ_EE,Average number of GCSE and equivalents entries...
359,TAVENT_ENFSM6CLA1A_15_PTQ_EE,Average number of GCSE and equivalents entries...
360,TAVENT_G_PTQ_EE,Average number of GCSE entries per pupil
361,TAVENT_GLO_PTQ_EE,Average number of GCSE entries per pupil with ...
362,TAVENT_GAV_PTQ_EE,Average number of GCSE entries per pupil with ...
363,TAVENT_GHI_PTQ_EE,Average number of GCSE entries per pupil with ...
364,TAVENT_GFSM6CLA1A_PTQ_EE,Average number of GCSE entries per disadvantag...
365,TAVENT_GNFSM6CLA1A_PTQ_EE,Average number of GCSE entries per non-disadva...
366,TAVENT_GFSM_13,Average number of GCSE entries per disadvantag...
367,TAVENT_GNFSM_13,Average number of GCSE entries per non-disadva...
368,TAVENT_GFSM_14_PTQ,Average number of GCSE entries per disadvantag...
369,TAVENT_GNFSM_14_PTQ,Average number of GCSE entries per non-disadva...
370,TAVENT_GFSM6CLA1A_15_PTQ_EE,Average number of GCSE entries per disadvantag...
371,TAVENT_GNFSM6CLA1A_15_PTQ_EE,Average number of GCSE entries per non-disadva...

In [39]:
# set up a reference to the db.collection 
ks4_meta = db.ks4_meta

In [40]:
ks4_meta.insert_many(ks4_meta_df.to_dict('records'))
# snippet reference is from:
# https://stackoverflow.com/questions/33979983/insert-rows-from-pandas-dataframe-into-mongodb-collection-as-individual-document

In [41]:
ks4_meta.find_one({'label': 'NFTYPE'})

{'_id': ObjectId('5b0c7eea0fd01f09d8fcee9f'),
 'expanded': 'School type (see separate list of abbreviations used in the tables)',
 'label': 'NFTYPE'}

I want to add the codes from the abbreviations dictionary to this document since it is one of the backdones to my investigation.

In [42]:
ks4_meta.update_one({'label': 'NFTYPE'}, 
                    {'$set': {'codes': nftypes}})

ks4_meta.find_one({'label': 'NFTYPE'})

{'_id': ObjectId('5b0c7eea0fd01f09d8fcee9f'),
 'codes': {'AC': 'Sponsored academy',
  'AC1619': 'Academy 16-19 sponsor led',
  'ACC': 'Academy converter - mainstream',
  'ACC1619': 'Academy 16-19 converter',
  'ACCS': 'Academy converter - special school',
  'ACS': 'Sponsored special academy',
  'CTC': 'City technology college',
  'CY': 'Community school',
  'CYS': 'Community special school',
  'F': 'Free school - mainstream',
  'F1619': 'Free school - 16-19',
  'FD': 'Foundation school',
  'FDS': 'Foundation special school',
  'FESI': 'Further Education Sector Institution',
  'FS': 'Free school - special',
  'FSS': 'Studio school',
  'FUTC': 'UTC (university technical college)',
  'IND': 'Independent school',
  'INDSPEC': 'Independent special school',
  'MODFC': 'College funded by Ministry of Defence',
  'NMSS': 'Non-maintained special school',
  'VA': 'Voluntary aided school',
  'VC': 'Voluntary controlled school'},
 'expanded': 'School type (see separate list of abbreviations used in the tables)',
 'label': 'NFTYPE'}

I'll do the same for the `RECTYPE` label by splitting the description.

In [43]:
# select the correct document
r = ks4_meta.find_one({'label': 'RECTYPE'})

# checks that we haven't already updated the document
# then if not splits the description string, adding a code key
# to reference each school type
if 'codes' not in r.keys():
    expanded = r['expanded']
    e = expanded[:11]
    codelist = expanded[13:-1].split('; ')
    keys = [c[:1] for c in codelist]
    values = [c[2:] for c in codelist]
    codes = (dict(list(zip(keys, values))))
    ks4_meta.update_one({'_id': r['_id']},
                        {'$set': {'expanded': e,
                                  'codes': codes}})

# check that it was processed correctly
ks4_meta.find_one({'label': 'RECTYPE'})

{'_id': ObjectId('5b0c7eea0fd01f09d8fcee90'),
 'codes': {'1': 'mainstream school',
  '2': 'special school',
  '4': 'local authority',
  '5': 'National (all schools)',
  '7': 'National (maintained schools)'},
 'expanded': 'Record type',
 'label': 'RECTYPE'}

Great.  That is most of the cleaning I need to do for the ks4_meta file.  If I were to be doing a different investigation I would consider merging in the LEA data here, but we already have it stored from earlier on (importing ks2) as a dataframe which we can reference if needed.

Great.  Now in the tm351 module materials we had some handy collections provided by the module team that enabled us to quickly look up the labels and codes of a given accident.  I'll borrow that idea here for my purposes.  Because, I will need to do the same for the KS2 dataset, I'll wrap them in a function.

In [44]:
# code adapted from the p14 accidents dataset notebooks

def expanded_label(meta):
    # Load the expanded names of keys and human-readable codes into memory
    expanded_name = collections.defaultdict(str)
    for e in meta.find({'expanded': {"$exists": True}}):
        expanded_name[e['label']] = e['expanded']

    label_of = collections.defaultdict(str)
    for l in meta.find({'codes': {"$exists": True}}):
        for c in l['codes']:
            try:
                label_of[l['label'], int(c)] = l['codes'][c]
            except ValueError: 
                label_of[l['label'], c] = l['codes'][c]
    # return both as a tuple
    return (expanded_name, label_of)

In [45]:
# Set up the expanded_name and label_of for ks4_meta
ks4_expanded_name, ks4_label_of = expanded_label(ks4_meta)

In [46]:
# test it works
[(c, ks4_label_of['RECTYPE', c]) for k, c in ks4_label_of if k == 'RECTYPE']

[(1, 'mainstream school'),
 (4, 'local authority'),
 (2, 'special school'),
 (7, 'National (maintained schools)'),
 (5, 'National (all schools)')]

In [47]:
ks4_expanded_name['NFTYPE']

'School type (see separate list of abbreviations used in the tables)'

In [48]:
ks4_label_of['NFTYPE', 'AC']

'Sponsored academy'

Great that all is working.  I'll quickly repeat the same steps for KS2_meta data

In [49]:
# relabel the columns of ks2cols
ks2cols.columns = ['not_needed', 'label', 'expanded']

# create a collection in the database
ks2_meta = db.ks2_meta

In [50]:
# store them into the database
ks2_meta.insert_many(ks2cols[['label', 'expanded']].to_dict('records'))

In [51]:
ks2_meta.find_one()

{'_id': ObjectId('5b0c7eea0fd01f09d8fcf004'),
 'expanded': 'Record type (1=mainstream school; 2=special school; 3=Local Authority; 4=National (all schools); 5=National (maintained schools))',
 'label': 'RECTYPE'}

In [52]:
# repeat the splitting of the `RECTYPE`
# select the correct document
r = ks2_meta.find_one({'label': 'RECTYPE'})

# checks that we haven't already updated the document
# then if not splits the description string, adding a code key
# to reference each school type
if 'codes' not in r.keys():
    expanded = r['expanded']
    e = expanded[:11]
    codelist = expanded[13:-1].split('; ')
    keys = [c[:1] for c in codelist]
    values = [c[2:] for c in codelist]
    codes = (dict(list(zip(keys, values))))
    ks2_meta.update_one({'_id': r['_id']},
                        {'$set': {'expanded': e,
                                  'codes': codes}})

# check that it was processed correctly
ks2_meta.find_one({'label': 'RECTYPE'})

{'_id': ObjectId('5b0c7eea0fd01f09d8fcf004'),
 'codes': {'1': 'mainstream school',
  '2': 'special school',
  '3': 'Local Authority',
  '4': 'National (all schools)',
  '5': 'National (maintained schools)'},
 'expanded': 'Record type',
 'label': 'RECTYPE'}

In [53]:
# And add the nftype to the meta collection
ks2_meta.update_one({'label': 'NFTYPE'}, 
                    {'$set': {'codes': nftypes}})

ks2_meta.find_one({'label': 'NFTYPE'})

{'_id': ObjectId('5b0c7eea0fd01f09d8fcf013'),
 'codes': {'AC': 'Sponsored academy',
  'AC1619': 'Academy 16-19 sponsor led',
  'ACC': 'Academy converter - mainstream',
  'ACC1619': 'Academy 16-19 converter',
  'ACCS': 'Academy converter - special school',
  'ACS': 'Sponsored special academy',
  'CTC': 'City technology college',
  'CY': 'Community school',
  'CYS': 'Community special school',
  'F': 'Free school - mainstream',
  'F1619': 'Free school - 16-19',
  'FD': 'Foundation school',
  'FDS': 'Foundation special school',
  'FESI': 'Further Education Sector Institution',
  'FS': 'Free school - special',
  'FSS': 'Studio school',
  'FUTC': 'UTC (university technical college)',
  'IND': 'Independent school',
  'INDSPEC': 'Independent special school',
  'MODFC': 'College funded by Ministry of Defence',
  'NMSS': 'Non-maintained special school',
  'VA': 'Voluntary aided school',
  'VC': 'Voluntary controlled school'},
 'expanded': 'School type',
 'label': 'NFTYPE'}

In [54]:
# finally, set up the expanded_name and label_of for ks4_meta
ks2_expanded_name, ks2_label_of = expanded_label(ks2_meta)

check they work ok

In [55]:
# test it works
[(c, ks4_label_of['RECTYPE', c]) for k, c in ks4_label_of if k == 'RECTYPE']

[(1, 'mainstream school'),
 (4, 'local authority'),
 (2, 'special school'),
 (7, 'National (maintained schools)'),
 (5, 'National (all schools)')]

In [56]:
ks4_label_of['NFTYPE', 'IND']

'Independent school'

Great that is all the meta data handled, and we can now go about importing the KS4 data into the database and cleaning it.

## Importing the KS4 dataset

In [57]:
!/usr/bin/mongoimport --port 27351 --drop --db schools_db --collection ks4 \
    --type csv --headerline --ignoreBlanks \
    --file data/2015-2016/england_ks4final.csv

2018-05-28T22:12:59.001+0000	connected to: localhost:27351
2018-05-28T22:12:59.001+0000	dropping: schools_db.ks4
2018-05-28T22:13:01.065+0000	imported 5489 documents

In [58]:
ks4 = db.ks4
ks4.find_one()

{'AC5EM13': '0%',
 'AC5EM14_PTQ': '0%',
 'AC5EM15_PTQ_EE': '0%',
 'AC5EM16_PTQ_EE': '0%',
 'ADDRESS1': 'Queen Victoria Street',
 'AGERANGE': '10-18',
 'ALPHAIND': 11828,
 'ATT8SCR': 42.1,
 'ATT8SCREBAC': 22.2,
 'ATT8SCREBAC_FSM6CLA1A': 'NP',
 'ATT8SCREBAC_NFSM6CLA1A': 'NP',
 'ATT8SCRENG': 7.3,
 'ATT8SCRENG_FSM6CLA1A': 'NP',
 'ATT8SCRENG_NFSM6CLA1A': 'NP',
 'ATT8SCRMAT': 0,
 'ATT8SCRMAT_FSM6CLA1A': 'NP',
 'ATT8SCRMAT_NFSM6CLA1A': 'NP',
 'ATT8SCROPEN': 12.6,
 'ATT8SCROPENG': 10.4,
 'ATT8SCROPENG_FSM6CLA1A': 'NP',
 'ATT8SCROPENG_NFSM6CLA1A': 'NP',
 'ATT8SCROPENNG': 2.2,
 'ATT8SCROPENNG_FSM6CLA1A': 'NP',
 'ATT8SCROPENNG_NFSM6CLA1A': 'NP',
 'ATT8SCROPEN_FSM6CLA1A': 'NP',
 'ATT8SCROPEN_NFSM6CLA1A': 'NP',
 'ATT8SCR_15': 'NA',
 'ATT8SCR_AV': 'NP',
 'ATT8SCR_BOYS': 42.1,
 'ATT8SCR_EAL': 'NP',
 'ATT8SCR_FSM6CLA1A': 'NP',
 'ATT8SCR_GIRLS': 'NA',
 'ATT8SCR_HI': 'NP',
 'ATT8SCR_LO': 'NP',
 'ATT8SCR_NFSM6CLA1A': 'NP',
 'ATT8SCR_NMOB': 'NP',
 'BPUP': 139,
 'CONTFLAG': 0,
 'DIFFN_ATT8': 'NP',
 'DIFFN_P8MEA': 'NP',
 'EGENDER': 'BOYS',
 'ESTAB': 6007,
 'FEEDER': 0,
 'GPUP': 'NA',
 'HUMVACOV_PTQ_EE': 'NP',
 'HUMVALOW_AV_PTQ_EE': 'NP',
 'HUMVALOW_FSM6CLA1A_PTQ_EE': 'NP',
 'HUMVALOW_HI_PTQ_EE': 'NP',
 'HUMVALOW_LO_PTQ_EE': 'NP',
 'HUMVALOW_NFSM6CLA1A_PTQ_EE': 'NP',
 'HUMVALOW_PTQ_EE': 'NP',
 'HUMVAMEA_AV_PTQ_EE': 'NP',
 'HUMVAMEA_FSM6CLA1A_PTQ_EE': 'NP',
 'HUMVAMEA_HI_PTQ_EE': 'NP',
 'HUMVAMEA_LO_PTQ_EE': 'NP',
 'HUMVAMEA_NFSM6CLA1A_PTQ_EE': 'NP',
 'HUMVAMEA_PTQ_EE': 'NP',
 'HUMVAUPP_AV_PTQ_EE': 'NP',
 'HUMVAUPP_FSM6CLA1A_PTQ_EE': 'NP',
 'HUMVAUPP_HI_PTQ_EE': 'NP',
 'HUMVAUPP_LO_PTQ_EE': 'NP',
 'HUMVAUPP_NFSM6CLA1A_PTQ_EE': 'NP',
 'HUMVAUPP_PTQ_EE': 'NP',
 'ICLOSE': 0,
 'KS2APS': 'NP',
 'LANVACOV_PTQ_EE': 'NP',
 'LANVALOW_AV_PTQ_EE': 'NP',
 'LANVALOW_FSM6CLA1A_PTQ_EE': 'NP',
 'LANVALOW_HI_PTQ_EE': 'NP',
 'LANVALOW_LO_PTQ_EE': 'NP',
 'LANVALOW_NFSM6CLA1A_PTQ_EE': 'NP',
 'LANVALOW_PTQ_EE': 'NP',
 'LANVAMEA_AV_PTQ_EE': 'NP',
 'LANVAMEA_FSM6CLA1A_PTQ_EE': 'NP',
 'LANVAMEA_HI_PTQ_EE': 'NP',
 'LANVAMEA_LO_PTQ_EE': 'NP',
 'LANVAMEA_NFSM6CLA1A_PTQ_EE': 'NP',
 'LANVAMEA_PTQ_EE': 'NP',
 'LANVAUPP_AV_PTQ_EE': 'NP',
 'LANVAUPP_FSM6CLA1A_PTQ_EE': 'NP',
 'LANVAUPP_HI_PTQ_EE': 'NP',
 'LANVAUPP_LO_PTQ_EE': 'NP',
 'LANVAUPP_NFSM6CLA1A_PTQ_EE': 'NP',
 'LANVAUPP_PTQ_EE': 'NP',
 'LEA': 201,
 'NFTYPE': 'IND',
 'NUMBOYS': 918,
 'NUMGIRLS': 'NA',
 'P8CILOW': 'NP',
 'P8CILOW_15': 'NA',
 'P8CILOW_AV': 'NP',
 'P8CILOW_BOYS': 'NP',
 'P8CILOW_EAL': 'NP',
 'P8CILOW_FSM6CLA1A': 'NP',
 'P8CILOW_GIRLS': 'NA',
 'P8CILOW_HI': 'NP',
 'P8CILOW_LO': 'NP',
 'P8CILOW_NFSM6CLA1A': 'NP',
 'P8CILOW_NMOB': 'NP',
 'P8CIUPP': 'NP',
 'P8CIUPP_15': 'NA',
 'P8CIUPP_AV': 'NP',
 'P8CIUPP_BOYS': 'NP',
 'P8CIUPP_EAL': 'NP',
 'P8CIUPP_FSM6CLA1A': 'NP',
 'P8CIUPP_GIRLS': 'NA',
 'P8CIUPP_HI': 'NP',
 'P8CIUPP_LO': 'NP',
 'P8CIUPP_NFSM6CLA1A': 'NP',
 'P8CIUPP_NMOB': 'NP',
 'P8MEA': 'NP',
 'P8MEACOV': 'NP',
 'P8MEAEBAC': 'NP',
 'P8MEAEBAC_CILOW': 'NP',
 'P8MEAEBAC_CILOW_FSM6CLA1A': 'NP',
 'P8MEAEBAC_CILOW_NFSM6CLA1A': 'NP',
 'P8MEAEBAC_CIUPP': 'NP',
 'P8MEAEBAC_CIUPP_FSM6CLA1A': 'NP',
 'P8MEAEBAC_CIUPP_NFSM6CLA1A': 'NP',
 'P8MEAEBAC_FSM6CLA1A': 'NP',
 'P8MEAEBAC_NFSM6CLA1A': 'NP',
 'P8MEAENG': 'NP',
 'P8MEAENG_CILOW': 'NP',
 'P8MEAENG_CILOW_FSM6CLA1A': 'NP',
 'P8MEAENG_CILOW_NFSM6CLA1A': 'NP',
 'P8MEAENG_CIUPP': 'NP',
 'P8MEAENG_CIUPP_FSM6CLA1A': 'NP',
 'P8MEAENG_CIUPP_NFSM6CLA1A': 'NP',
 'P8MEAENG_FSM6CLA1A': 'NP',
 'P8MEAENG_NFSM6CLA1A': 'NP',
 'P8MEAMAT': 'NP',
 'P8MEAMAT_CILOW': 'NP',
 'P8MEAMAT_CILOW_FSM6CLA1A': 'NP',
 'P8MEAMAT_CILOW_NFSM6CLA1A': 'NP',
 'P8MEAMAT_CIUPP': 'NP',
 'P8MEAMAT_CIUPP_FSM6CLA1A': 'NP',
 'P8MEAMAT_CIUPP_NFSM6CLA1A': 'NP',
 'P8MEAMAT_FSM6CLA1A': 'NP',
 'P8MEAMAT_NFSM6CLA1A': 'NP',
 'P8MEAOPEN': 'NP',
 'P8MEAOPEN_CILOW': 'NP',
 'P8MEAOPEN_CILOW_FSM6CLA1A': 'NP',
 'P8MEAOPEN_CILOW_NFSM6CLA1A': 'NP',
 'P8MEAOPEN_CIUPP': 'NP',
 'P8MEAOPEN_CIUPP_FSM6CLA1A': 'NP',
 'P8MEAOPEN_CIUPP_NFSM6CLA1A': 'NP',
 'P8MEAOPEN_FSM6CLA1A': 'NP',
 'P8MEAOPEN_NFSM6CLA1A': 'NP',
 'P8MEA_15': 'NA',
 'P8MEA_AV': 'NP',
 'P8MEA_BOYS': 'NP',
 'P8MEA_EAL': 'NP',
 'P8MEA_FSM6CLA1A': 'NP',
 'P8MEA_GIRLS': 'NA',
 'P8MEA_HI': 'NP',
 'P8MEA_LO': 'NP',
 'P8MEA_NFSM6CLA1A': 'NP',
 'P8MEA_NMOB': 'NP',
 'P8PUP': 'NP',
 'P8PUP_15': 'NA',
 'P8PUP_AV': 'NP',
 'P8PUP_BOYS': 'NP',
 'P8PUP_EAL': 'NP',
 'P8PUP_FSM6CLA1A': 'NP',
 'P8PUP_GIRLS': 'NA',
 'P8PUP_HI': 'NP',
 'P8PUP_LO': 'NP',
 'P8PUP_NFSM6CLA1A': 'NP',
 'P8PUP_NMOB': 'NP',
 'PBEBACC_E_PTQ_EE': '0%',
 'PBEBACC_PTQ_EE': '0%',
 'PBL2BASICS_LL_PTQ_EE': '0%',
 'PBPUP': '100%',
 'PCODE': 'EC4V 3AL',
 'PGEBACC_E_PTQ_EE': 'NE',
 'PGEBACC_PTQ_EE': 'NE',
 'PGL2BASICS_LL_PTQ_EE': 'NE',
 'PGPUP': 'NA',
 'PSENAPK4': 'NA',
 'PSENSE4': 'NA',
 'PTAC5EM_PTQ_EE': '0%',
 'PTANYQ_PTQ_EE': '100%',
 'PTBASICS_LL_AV_PTQ_EE': 'NP',
 'PTBASICS_LL_HI_PTQ_EE': 'NP',
 'PTBASICS_LL_LO_PTQ_EE': 'NP',
 'PTEALGRP1': 'NP',
 'PTEALGRP2': 'NP',
 'PTEALGRP3': 'NP',
 'PTEBAC2SCIAG_PTQ_EE': 'NE',
 'PTEBAC2SCI_E_PTQ_EE': '0%',
 'PTEBAC2SCI_PTQ_EE': 'NE',
 'PTEBACCAG_PTQ_EE': '0%',
 'PTEBACCAV_PTQ_EE': 'NP',
 'PTEBACCEAL_PTQ_EE': 'NP',
 'PTEBACCHI_PTQ_EE': 'NP',
 'PTEBACCLO_PTQ_EE': 'NP',
 'PTEBACCNMOB_PTQ_EE': 'NP',
 'PTEBACC_13': '0%',
 'PTEBACC_14_PTQ': '0%',
 'PTEBACC_15_PTQ_EE': '0%',
 'PTEBACC_EAV_PTQ_EE': 'NP',
 'PTEBACC_EEAL_PTQ_EE': 'NP',
 'PTEBACC_EFSM6CLA1A_15_PTQ_EE': 'NA',
 'PTEBACC_EFSM6CLA1A_PTQ_EE': 'NP',
 'PTEBACC_EFSM_13': 'NA',
 'PTEBACC_EFSM_14_PTQ': 'NA',
 'PTEBACC_EHI_PTQ_EE': 'NP',
 'PTEBACC_ELO_PTQ_EE': 'NP',
 'PTEBACC_ENFSM6CLA1A_15_PTQ_EE': 'NA',
 'PTEBACC_ENFSM6CLA1A_PTQ_EE': 'NP',
 'PTEBACC_ENFSM_13': 'NA',
 'PTEBACC_ENFSM_14_PTQ': 'NA',
 'PTEBACC_ENMOB_PTQ_EE': 'NP',
 'PTEBACC_E_13': '0%',
 'PTEBACC_E_14_PTQ': '0%',
 'PTEBACC_E_15_PTQ_EE': '0%',
 'PTEBACC_E_PTQ_EE': '0%',
 'PTEBACC_FSM6CLA1A_15_PTQ_EE': 'NA',
 'PTEBACC_FSM6CLA1A_PTQ_EE': 'NP',
 'PTEBACC_FSM_13': 'NA',
 'PTEBACC_FSM_14_PTQ': 'NA',
 'PTEBACC_NFSM6CLA1A_15_PTQ_EE': 'NA',
 'PTEBACC_NFSM6CLA1A_PTQ_EE': 'NP',
 'PTEBACC_NFSM_13': 'NA',
 'PTEBACC_NFSM_14_PTQ': 'NA',
 'PTEBACC_PTQ_EE': '0%',
 'PTEBACENGAG_LL_PTQ_EE': '0%',
 'PTEBACENG_E_PTQ_EE': '0%',
 'PTEBACENG_LL_PTQ_EE': '0%',
 'PTEBACHUMAG_PTQ_EE': '100%',
 'PTEBACHUM_E_PTQ_EE': '97%',
 'PTEBACHUM_PTQ_EE': '100%',
 'PTEBACLANAG_PTQ_EE': '100%',
 'PTEBACLAN_E_PTQ_EE': '100%',
 'PTEBACLAN_PTQ_EE': '100%',
 'PTEBACMATAG_PTQ_EE': '0%',
 'PTEBACMAT_E_PTQ_EE': '0%',
 'PTEBACMAT_PTQ_EE': '0%',
 'PTFSM6CLA1A': 'NP',
 'PTFSM6CLA1ABASICS_15_PTQ_EE': 'NA',
 'PTFSM6CLA1ABASICS_LL_PTQ_EE': 'NP',
 'PTFSM6CLA1A_15': 'NA',
 'PTFSMBASICS_13': 'NA',
 'PTFSMBASICS_14_PTQ': 'NA',
 'PTFSMCLA_13': 'NA',
 'PTFSMCLA_14': 'NA',
 'PTL2BASICS_13': '0%',
 'PTL2BASICS_14_PTQ': '0%',
 'PTL2BASICS_15_PTQ_EE': '0%',
 'PTL2BASICS_3YR_PTQ_EE': '0%',
 'PTL2BASICS_LL_EAL_PTQ_EE': 'NP',
 'PTL2BASICS_LL_NMOB_PTQ_EE': 'NP',
 'PTL2BASICS_LL_PTQ_EE': '0%',
 'PTNMOB': 'NP',
 'PTNOTFSM6CLA1A': 'NP',
 'PTNOTFSM6CLA1ABASICS_15_PTQ_EE': 'NA',
 'PTNOTFSM6CLA1ABASICS_LL_PTQ_EE': 'NP',
 'PTNOTFSM6CLA1A_15': 'NA',
 'PTNOTFSMBASICS_13': 'NA',
 'PTNOTFSMBASICS_14_PTQ': 'NA',
 'PTNOTFSMCLA_13': 'NA',
 'PTNOTFSMCLA_14': 'NA',
 'PTPRIORAV': 'NP',
 'PTPRIORHI': 'NP',
 'PTPRIORLO': 'NP',
 'PTmultiLan_E': '68%',
 'PTtripleSci_E': '0%',
 'RECTYPE': 1,
 'RELDENOM': 'None',
 'SCHNAME': 'City of London School',
 'SCIVACOV_PTQ_EE': 'NP',
 'SCIVALOW_AV_PTQ_EE': 'NP',
 'SCIVALOW_FSM6CLA1A_PTQ_EE': 'NP',
 'SCIVALOW_HI_PTQ_EE': 'NP',
 'SCIVALOW_LO_PTQ_EE': 'NP',
 'SCIVALOW_NFSM6CLA1A_PTQ_EE': 'NP',
 'SCIVALOW_PTQ_EE': 'NP',
 'SCIVAMEA_AV_PTQ_EE': 'NP',
 'SCIVAMEA_FSM6CLA1A_PTQ_EE': 'NP',
 'SCIVAMEA_HI_PTQ_EE': 'NP',
 'SCIVAMEA_LO_PTQ_EE': 'NP',
 'SCIVAMEA_NFSM6CLA1A_PTQ_EE': 'NP',
 'SCIVAMEA_PTQ_EE': 'NP',
 'SCIVAUPP_AV_PTQ_EE': 'NP',
 'SCIVAUPP_FSM6CLA1A_PTQ_EE': 'NP',
 'SCIVAUPP_HI_PTQ_EE': 'NP',
 'SCIVAUPP_LO_PTQ_EE': 'NP',
 'SCIVAUPP_NFSM6CLA1A_PTQ_EE': 'NP',
 'SCIVAUPP_PTQ_EE': 'NP',
 'SENAPK4': 'NA',
 'SENSE4': 'NA',
 'TAB1618': 1,
 'TABKS2': 0,
 'TAVENT_EFSM6CLA1A_15_PTQ_EE': 'NA',
 'TAVENT_EFSM_13': 'NA',
 'TAVENT_EFSM_14_PTQ': 'NA',
 'TAVENT_ENFSM6CLA1A_15_PTQ_EE': 'NA',
 'TAVENT_ENFSM_13': 'NA',
 'TAVENT_ENFSM_14_PTQ': 'NA',
 'TAVENT_E_3NG_AV_PTQ_EE': 'NP',
 'TAVENT_E_3NG_FSM6CLA1A_PTQ_EE': 'NP',
 'TAVENT_E_3NG_HI_PTQ_EE': 'NP',
 'TAVENT_E_3NG_LO_PTQ_EE': 'NP',
 'TAVENT_E_3NG_NFSM6CLA1A_PTQ_EE': 'NP',
 'TAVENT_E_3NG_PTQ_EE': 5.6,
 'TAVENT_GAV_PTQ_EE': 'NP',
 'TAVENT_GFSM6CLA1A_15_PTQ_EE': 'NA',
 'TAVENT_GFSM6CLA1A_PTQ_EE': 'NP',
 'TAVENT_GFSM_13': 'NA',
 'TAVENT_GFSM_14_PTQ': 'NA',
 'TAVENT_GHI_PTQ_EE': 'NP',
 'TAVENT_GLO_PTQ_EE': 'NP',
 'TAVENT_GNFSM6CLA1A_15_PTQ_EE': 'NA',
 'TAVENT_GNFSM6CLA1A_PTQ_EE': 'NP',
 'TAVENT_GNFSM_13': 'NA',
 'TAVENT_GNFSM_14_PTQ': 'NA',
 'TAVENT_G_PTQ_EE': 5.3,
 'TBASICS_LL_AV_PTQ_EE': 'NP',
 'TBASICS_LL_HI_PTQ_EE': 'NP',
 'TBASICS_LL_LO_PTQ_EE': 'NP',
 'TEALGRP1': 'NP',
 'TEALGRP2': 'NP',
 'TEALGRP3': 'NP',
 'TEBAC2SCIAG_PTQ_EE': 'NE',
 'TEBAC2SCI_E_PTQ_EE': 0,
 'TEBAC2SCI_PTQ_EE': 'NE',
 'TEBACCAG_PTQ_EE': 0,
 'TEBACC_EAV_PTQ_EE': 'NP',
 'TEBACC_EHI_PTQ_EE': 'NP',
 'TEBACC_ELO_PTQ_EE': 'NP',
 'TEBACC_E_PTQ_EE': 0,
 'TEBACENGAG_LL_PTQ_EE': 0,
 'TEBACENG_E_PTQ_EE': 0,
 'TEBACENG_LL_PTQ_EE': 0,
 'TEBACHUMAG_PTQ_EE': 135,
 'TEBACHUM_E_PTQ_EE': 135,
 'TEBACHUM_PTQ_EE': 135,
 'TEBACLANAG_PTQ_EE': 139,
 'TEBACLAN_E_PTQ_EE': 139,
 'TEBACLAN_PTQ_EE': 139,
 'TEBACMATAG_PTQ_EE': 0,
 'TEBACMAT_E_PTQ_EE': 0,
 'TEBACMAT_PTQ_EE': 0,
 'TELNUM': '0207 4890291',
 'TFSM6CLA1A': 'NP',
 'TFSM6CLA1A_15': 'NA',
 'TFSMCLA_13': 'NA',
 'TFSMCLA_14': 'NA',
 'TNMOB': 'NP',
 'TNOTFSM6CLA1A': 'NP',
 'TNOTFSM6CLA1A_15': 'NA',
 'TNOTFSMCLA_13': 'NA',
 'TNOTFSMCLA_14': 'NA',
 'TOTATT8': 5849,
 'TOTATT8EBAC': 3085.3,
 'TOTATT8ENG': 1012,
 'TOTATT8MAT': 0,
 'TOTATT8OPEN': 1751.8,
 'TOTATT8OPENG': 1452.5,
 'TOTATT8OPENNG': 299.3,
 'TOTPUPS': 918,
 'TOWN': 'London',
 'TPRIORAV': 'NP',
 'TPRIORHI': 'NP',
 'TPRIORLO': 'NP',
 'TPUP': 139,
 'URN': 100003,
 '_id': ObjectId('5b0c7eeb0210e25ef051cd0d')}

# Cleanup/remove the database
<a name="cleanup"></a>

Uncomment the lines below to remove the MongoDB created in the investigation.

In [59]:
# uncomment to remove the database if needed
# client.drop_database('schools_db')
# client.database_names()

['accidents', 'admin', 'local']