# EMA Project Notebook
__Name:__ Daniel Smith

__PI:__ A7603242

In [1]:
# import the required libraries
import pandas as pd
import scipy.stats
import numpy as np
import pymongo
import bson
import collections
from matplotlib import pyplot
import seaborn as sns

In [96]:
# make a folder for storing my working files as I go along.
# not used in the end.
# !mkdir -p data/dcs283

In [3]:
# !ls data/dcs283

# Contents

[TODO](#todo)


Use these links to jump to a section.

[Initial look at the ks4 dataset](#initial_look)

[Choosing MongoDB](#mongo)

[Data preparation](#preparation)
 - [Importing the KS2 data](#importing_ks2)
 - [Importing the KS4 data](#importing_ks4)

[Q1, KS4 Investigation](#q1)

[Q2, KS2 - KS4 Investigation](#q2)

[Application of Machine Learning](#machine_learning)

[Cleanup - remove the database](#cleanup)

<a name="initial_look"></a>

# Initial look at the KS4 results dataset
Let's have a quick look at the data we will be looking at for the EMA.

In [4]:
!head -5 'data/2015-2016/england_ks4final.csv'

In [5]:
!wc -l 'data/2015-2016/england_ks4final.csv'

5489 data/2015-2016/england_ks4final.csv

The dataset has 5489 rows of data, there appears to be a large number of columns and a lot of codes that I'll need to look up.  There are a also a number of `NA` and `NP` values that could be missing data.  As well as this results data I will need to find and import the relevent metadata file.

Before importing the dataset I will need to decide which storage method to use.

<a name="mongo"></a>

# Choosing MongoDB

With so many columns to investigate I am leaning towards using a DBMS to make the querying of the data more efficient than in a pandas dataframe.  Therefore, I will import the data into MongoDB.  I chose a document database system as they are far more flexible than a relational database.  In this investigation it may become necessary to add fields to certain documents for example.

In [6]:
# set up a connection to mongodb server
client = pymongo.MongoClient('mongodb://localhost:27351')

In [7]:
# uncomment to remove the database if needed
client.drop_database('schools_db')
client.database_names()

['accidents', 'admin', 'local']

In [8]:
# setup a schools_db database on mongo
db = client.schools_db

<a name="preparation"></a>

# Data preparation

Before we can investigate the data we will need to have a quick look at it, determine what cleaning, if any, is needed.  Carry out the cleaning and store it for access in tn appropriate form.  

However before doing anything I will import the KS2 data in the same way as was done in `dcs283_TMA02_Question2b-pd`  I will then store the resultant dataframe into mongo for analysis later on.

<a name="importing_ks2"></a>

## Importing the KS2 data


All of this section is the same as in the `TMA02_Question2b-pd` notebook.

***
__ ----------- Beginning of TMA02 code -----------  __

### Import the LEA data

In [9]:
leas_df = pd.read_csv('data/2015-2016/la_and_region_codes_meta.csv')
leas_df.head()

   LEA               LA Name  REGION   REGION NAME
0  841            Darlington       1  North East A
1  840         County Durham       1  North East A
2  805            Hartlepool       1  North East A
3  806         Middlesbrough       1  North East A
4  807  Redcar and Cleveland       1  North East A

### Import the KS2 data
Most of the field names are given in the `ks2_meta` file, so we'll use that to keep track of the types of various columns.

In [10]:
ks2cols = pd.read_csv('data/2015-2016/ks2_meta.csv')
ks2cols['Field Name'] = ks2cols['Field Name'].apply(lambda r: r.strip(),)
ks2cols

,Column,Field Name,Label/Description
0,1,RECTYPE,Record type (1=mainstream school; 2=special sc...
1,2,ALPHAIND,Alphabetic index
2,3,LEA,Local authority number
3,4,ESTAB,Establishment number
4,5,URN,School unique reference number
5,6,SCHNAME,School/Local authority name
6,7,ADDRESS1,School address (1)
7,8,ADDRESS2,School address (2)
8,9,ADDRESS3,School address (3)
9,10,TOWN,School town
10,11,PCODE,School postcode
11,12,TELNUM,School telephone number
12,13,URN_AC,Converter academy: URN
13,14,SCHNAME_AC,Converter academy: name
14,15,OPEN_AC,Converter academy: open date
15,16,NFTYPE,School type
16,17,ICLOSE,Closed Flag
17,18,RELDENOM,Religious denomination
18,19,AGERANGE,Age range
19,20,CONFEXAM,Confirmation flag that core performance inform...
20,21,TAB15,School published in secondary school (key stag...
21,22,TAB1618,School published in school and college (key st...
22,23,TOTPUPS,Total number of pupils (including part-time pu...
23,24,TPUPYEAR,Number of pupils aged 11
24,25,TELIG,Published eligible pupil number
25,26,BELIG,Eligible boys on school roll at time of tests
26,27,GELIG,Eligible girls on school roll at time of tests
27,28,PBELIG,Percentage of eligible boys on school roll at ...
28,29,PGELIG,Percentage of eligible girls on school roll at...
29,30,TKS1AVERAGE,Cohort level key stage 1 average points score
...,...,...,...
229,230,PTGPS_HIGH_M,Percentage of pupils with medium prior attainm...
230,231,PTGPS_HIGH_H,Percentage of pupils with high prior attainmen...
231,232,PTGPS_HIGH_FSM6CLA1A,Percentage of disadvantaged pupils achieving a...
232,233,PTGPS_HIGH_NotFSM6CLA1A,Percentage of non-disadvantaged pupils achievi...
233,234,PTMAT_HIGH_L,Percentage of pupils with low prior attainment...
234,235,PTMAT_HIGH_M,Percentage of pupils with medium prior attainm...
235,236,PTMAT_HIGH_H,Percentage of pupils with high prior attainmen...
236,237,PTMAT_HIGH_FSM6CLA1A,Percentage of disadvantaged pupils achieving a...
237,238,PTMAT_HIGH_NotFSM6CLA1A,Percentage of non-disadvantaged pupils achievi...
238,239,PTWRITTA_HIGH_L,Percentage of pupils with low prior attainment...
239,240,PTWRITTA_HIGH_M,Percentage of pupils with medium prior attainm...
240,241,PTWRITTA_HIGH_H,Percentage of pupils with high prior attainmen...
241,242,PTWRITTA_HIGH_FSM6CLA1A,Percentage of disadvantaged pupils working at ...
242,243,PTWRITTA_HIGH_NotFSM6CLA1A,Percentage of non-disadvantaged pupils working...
243,244,TEALGRP1,Number of eligible pupils with English as firs...
244,245,PTEALGRP1,Percentage of eligible pupils with English as ...
245,246,TEALGRP3,Number of eligible pupils with unclassified la...
246,247,PTEALGRP3,Percentage of eligible pupils with unclassifie...
247,248,TSENELAPK,Number of eligible pupils with SEN without sta...
248,249,PSENELSAPK,Percentage of eligible pupils with SEN without...
249,250,TSENELE,Number of eligible pupils with EHC plan
250,251,PSENELE,Percentage of eligible pupils with EHC plan
251,252,TSENELK,Number of eligible pupils with SEN support
252,253,PSENELK,Percentage of eligible pupils with SEN support
253,254,TSENELST,Number of eligible pupils with SEN (Special Ed...
254,255,PSENELST,Percentage of eligible pupils with SEN (Specia...
255,256,TSENELSAP,Number of eligible pupils with School Action Plus
256,257,PSENELSAP,Percentage of eligible pupils with School Acti...
257,258,SENELN,Number of eligible pupils with SEN (Special Ed...
258,259,PSENELN,Percentage of eligible pupils with SEN (Specia...

Some columns contain integers, but _**pandas**_ will treat any numeric column with `na` values as `float64`, due to NumPy's number type hierarchy.

In [11]:
int_cols = [c for c in ks2cols['Field Name'] 
            if c.startswith('T')
            if c not in ['TOWN', 'TELNUM', 'TKS1AVERAGE']]
int_cols += ['RECTYPE', 'ALPHAIND', 'LEA', 'ESTAB', 'URN', 'URN_AC', 'ICLOSE']
int_cols += ['READ_AVERAGE', 'GPS_AVERAGE', 'MAT_AVERAGE']

Some columns contain percentages. We'll convert these to floating point numbers on import.

Note that we also need to handle the case of `SUPP` and `NEW` in the data.

In [12]:
def p2f(x):
    if x.strip('%').isnumeric():
        return float(x.strip('%'))/100
    elif x in ['SUPP', 'NEW', 'LOWCOV', 'NA', '']:
        return 0.0
    else:
        return x

These are the columns to try to convert from percentages. Note that we can be generous here, as columns like PCODE (postcode) will return the original value if the conversion fails.

In [13]:
percent_cols = [f for f in ks2cols['Field Name'] if f.startswith('P')]
percent_cols += ['WRITCOV', 'MATCOV', 'READCOV'] 
percent_cols += ['PTMAT_HIGH', 'PTREAD_HIGH', 'PSENELSAPK', 'PSENELK', 'PTGPS_HIGH']
percent_converters = {c: p2f for c in percent_cols}

In [14]:
ks2_df = pd.read_csv('data/2015-2016/england_ks2final.csv', 
                   na_values=['SUPP', 'NEW', 'LOWCOV', 'NA', ''],
                   converters=percent_converters)

Drop the summary rows, keeping just the rows for mainstream and special schools.

In [15]:
ks2_df = ks2_df[(ks2_df['RECTYPE'] == 1) | (ks2_df['RECTYPE'] == 2)]

Convert everything to numbers, if possible.

In [16]:
ks2_df = ks2_df.apply(pd.to_numeric, errors='ignore')

Merge the LEA data into the school data

In [17]:
ks2_df = pd.merge(ks2_df, leas_df, on=['LEA'])
ks2_df.head().T

,0,1,2,3,4
RECTYPE,1,1,1,1,1
ALPHAIND,53372,11156,11160,11256,16366
LEA,201,202,202,202,202
ESTAB,3614,3323,3327,2842,2184
URN,100000,100028,100029,130342,100013
SCHNAME,Sir John Cass's Foundation Primary School,"Christ Church Primary School, Hampstead",Christ Church School,Christopher Hatton Primary School,Edith Neville Primary School
ADDRESS1,St James's Passage,Christ Church Hill,Redhill Street,38 Laystall Street,174 Ossulston Street
ADDRESS2,Duke's Place,NaN,Camden,NaN,NaN
ADDRESS3,NaN,NaN,NaN,NaN,NaN
TOWN,London,London,London,London,London
PCODE,EC3A 5DE,NW3 1JH,NW1 4BD,EC1R 4PQ,NW1 1DN
TELNUM,0207 2831147,0207 4351361,0207 3877881,0207 2784500,0207 3877158
URN_AC,0,0,0,0,0
SCHNAME_AC,NaN,NaN,NaN,NaN,NaN
OPEN_AC,NaN,NaN,NaN,NaN,NaN
NFTYPE,VA,VA,VA,CY,CY
ICLOSE,0,0,0,0,0
RELDENOM,Church of England,Church of England,Church of England,Does not apply,Does not apply
AGERANGE,3-11,4-11,3-11,3-11,3-11
CONFEXAM,NaN,NaN,NaN,NaN,NaN
TAB15,0,0,0,0,0
TAB1618,0,0,0,0,0
TOTPUPS,250,181,229,233,221
TPUPYEAR,28,23,29,28,29
TELIG,28,21,28,28,29
BELIG,16,16,17,16,9
GELIG,12,5,11,12,20
PBELIG,0.57,0.76,0.61,0.57,0.31
PGELIG,0.43,0.24,0.39,0.43,0.69
TKS1AVERAGE,16,16.7,14,16,14.5
...,...,...,...,...,...
PTGPS_HIGH_NotFSM6CLA1A,0.31,0,0.27,0.5,0.56
PTMAT_HIGH_L,0,0,0,0,0
PTMAT_HIGH_M,0.15,0.25,0.16,0.12,0.32
PTMAT_HIGH_H,0.33,0.83,0,0.29,0
PTMAT_HIGH_FSM6CLA1A,0.08,0,0.12,0.17,0.25
PTMAT_HIGH_NotFSM6CLA1A,0.25,0,0.18,0.25,0.44
PTWRITTA_HIGH_L,0,0,0,0,0
PTWRITTA_HIGH_M,0.05,0.33,0.11,0.06,0.09
PTWRITTA_HIGH_H,0.5,0.83,0,0.57,0
PTWRITTA_HIGH_FSM6CLA1A,0,0,0.18,0.17,0.1
PTWRITTA_HIGH_NotFSM6CLA1A,0.25,0,0.09,0.19,0.11
TEALGRP1,10,7,13,11,0
PTEALGRP1,0.36,0.33,0.46,0.39,0
TEALGRP3,0,0,0,0,0
PTEALGRP3,0,0,0,0,0
TSENELAPK,5,2,6,5,11
PSENELSAPK,0.18,0.1,0.21,0.18,0.38
TSENELE,0,0,1,0,0
PSENELE,0,0,0.04,0,0
TSENELK,5,2,6,5,11
PSENELK,0.18,0.1,0.21,0.18,0.38
TSENELST,0,0,0,0,0
PSENELST,0,0,0,0,0
TSENELSAP,0,0,0,0,0
PSENELSAP,0,0,0,0,0
SENELN,0,0,0,0,0
PSENELN,0,0,0,0,0
LA Name,City of London,Camden,Camden,Camden,Camden
REGION,32,31,31,31,31
REGION NAME,London East,London Central,London Central,London Central,London Central

__ ----------- END of TMA02 code -----------  __
***

### Convert and store the KS2 dataframe into Mongo for use later

In [18]:
# set up a collection for the ks2 results dataframe
ks2 = db.ks2_results

In [19]:
# convert the dataframe into a list of dicts and store in Mongo

# the 'results' argument is needed to get a list of dicts
ks2.insert_many(ks2_df.to_dict('records'))

# snippet reference is from:
# https://stackoverflow.com/questions/33979983/insert-rows-from-pandas-dataframe-into-mongodb-collection-as-individual-document

In [20]:
# check we got them all
ks2.find().count(), len(ks2_df)

(16162, 16162)

In [21]:
ks2.find_one()

{'ADDRESS1': "St James's Passage",
 'ADDRESS2': "Duke's Place",
 'ADDRESS3': nan,
 'AGERANGE': '3-11',
 'ALPHAIND': 53372.0,
 'BELIG': 16.0,
 'CONFEXAM': nan,
 'DIFFN_MATPROG': 2.7,
 'DIFFN_READPROG': 0.6,
 'DIFFN_RWM_EXP': 23.0,
 'DIFFN_RWM_HIGH': -7.0,
 'DIFFN_WRITPROG': 0.2,
 'ESTAB': 3614.0,
 'GELIG': 12.0,
 'GPS_AVERAGE': 106.0,
 'GPS_AVERAGE_FSM6CLA1A': 105.0,
 'GPS_AVERAGE_H': 110.0,
 'GPS_AVERAGE_L': nan,
 'GPS_AVERAGE_M': 105.0,
 'GPS_AVERAGE_NotFSM6CLA1A': 107.0,
 'ICLOSE': 0.0,
 'LA Name': 'City of London',
 'LEA': 201.0,
 'MATCOV': 1.0,
 'MATPROG': 3.0,
 'MATPROG_B': 2.9,
 'MATPROG_B_LOWER': 0.3,
 'MATPROG_B_UPPER': 5.5,
 'MATPROG_EAL': 3.1,
 'MATPROG_EAL_LOWER': 0.6,
 'MATPROG_EAL_UPPER': 5.6,
 'MATPROG_FSM6CLA1A': 2.9,
 'MATPROG_FSM6CLA1A_LOWER': -0.1,
 'MATPROG_FSM6CLA1A_UPPER': 5.9,
 'MATPROG_G': 3.1,
 'MATPROG_G_LOWER': 0.1,
 'MATPROG_G_UPPER': 6.1,
 'MATPROG_H': 0.4,
 'MATPROG_H_LOWER': -3.9,
 'MATPROG_H_UPPER': 4.7,
 'MATPROG_L': nan,
 'MATPROG_LOWER': 1.0,
 'MATPROG_L_LOWER': nan,
 'MATPROG_L_UPPER': nan,
 'MATPROG_M': 3.3,
 'MATPROG_MOBN': 3.0,
 'MATPROG_MOBN_LOWER': 1.0,
 'MATPROG_MOBN_UPPER': 5.0,
 'MATPROG_M_LOWER': 1.0,
 'MATPROG_M_UPPER': 5.6,
 'MATPROG_NotFSM6CLA1A': 3.0,
 'MATPROG_NotFSM6CLA1A_LOWER': 0.4,
 'MATPROG_NotFSM6CLA1A_UPPER': 5.6,
 'MATPROG_UPPER': 5.0,
 'MAT_AVERAGE': 106.0,
 'MAT_AVERAGE_FSM6CLA1A': 106.0,
 'MAT_AVERAGE_H': 108.0,
 'MAT_AVERAGE_L': nan,
 'MAT_AVERAGE_M': 106.0,
 'MAT_AVERAGE_NotFSM6CLA1A': 107.0,
 'NFTYPE': 'VA',
 'OPEN_AC': nan,
 'PBELIG': 0.57,
 'PCODE': 'EC3A 5DE',
 'PGELIG': 0.43,
 'PSENELE': 0.0,
 'PSENELK': 0.18,
 'PSENELN': 0.0,
 'PSENELSAP': 0.0,
 'PSENELSAPK': 0.18,
 'PSENELSE': 0.0,
 'PSENELST': 0.0,
 'PTEALGRP1': 0.36,
 'PTEALGRP2': 0.64,
 'PTEALGRP3': 0.0,
 'PTFSM6CLA1A': 0.43,
 'PTGPS_AT': 0.0,
 'PTGPS_EXP': 0.96,
 'PTGPS_EXP_FSM6CLA1A': 1.0,
 'PTGPS_EXP_H': 1.0,
 'PTGPS_EXP_L': 0.0,
 'PTGPS_EXP_M': 0.95,
 'PTGPS_EXP_NotFSM6CLA1A': 0.94,
 'PTGPS_HIGH': 0.18,
 'PTGPS_HIGH_FSM6CLA1A': 0.0,
 'PTGPS_HIGH_H': 0.33,
 'PTGPS_HIGH_L': 0.0,
 'PTGPS_HIGH_M': 0.15,
 'PTGPS_HIGH_NotFSM6CLA1A': 0.31,
 'PTKS1GROUP_H': 0.21,
 'PTKS1GROUP_L': 0.07,
 'PTKS1GROUP_M': 0.71,
 'PTKS1GROUP_NA': 0.0,
 'PTMATTA_AD': 0.0,
 'PTMATTA_EXP': 0.96,
 'PTMAT_AT': 0.0,
 'PTMAT_EXP': 1.0,
 'PTMAT_EXP_FSM6CLA1A': 1.0,
 'PTMAT_EXP_H': 1.0,
 'PTMAT_EXP_L': 0.0,
 'PTMAT_EXP_M': 1.0,
 'PTMAT_EXP_NotFSM6CLA1A': 1.0,
 'PTMAT_HIGH': 0.18,
 'PTMAT_HIGH_FSM6CLA1A': 0.08,
 'PTMAT_HIGH_H': 0.33,
 'PTMAT_HIGH_L': 0.0,
 'PTMAT_HIGH_M': 0.15,
 'PTMAT_HIGH_NotFSM6CLA1A': 0.25,
 'PTMOBN': 1.0,
 'PTNotFSM6CLA1A': 0.57,
 'PTREADTA_AD': 0.0,
 'PTREADTA_EXP': 0.93,
 'PTREAD_AT': 0.0,
 'PTREAD_EXP': 0.93,
 'PTREAD_EXP_FSM6CLA1A': 0.92,
 'PTREAD_EXP_H': 1.0,
 'PTREAD_EXP_L': 0.0,
 'PTREAD_EXP_M': 0.9,
 'PTREAD_EXP_NotFSM6CLA1A': 0.94,
 'PTREAD_HIGH': 0.18,
 'PTREAD_HIGH_FSM6CLA1A': 0.08,
 'PTREAD_HIGH_H': 0.67,
 'PTREAD_HIGH_L': 0.0,
 'PTREAD_HIGH_M': 0.05,
 'PTREAD_HIGH_NotFSM6CLA1A': 0.25,
 'PTRWM_EXP': 0.89,
 'PTRWM_EXP_B': 0.88,
 'PTRWM_EXP_EAL': 0.83,
 'PTRWM_EXP_FSM6CLA1A': 0.83,
 'PTRWM_EXP_G': 0.92,
 'PTRWM_EXP_H': 1.0,
 'PTRWM_EXP_L': 0.0,
 'PTRWM_EXP_M': 0.9,
 'PTRWM_EXP_MOBN': 0.89,
 'PTRWM_EXP_NotFSM6CLA1A': 0.94,
 'PTRWM_HIGH': 0.07,
 'PTRWM_HIGH_B': 0.06,
 'PTRWM_HIGH_EAL': 0.11,
 'PTRWM_HIGH_FSM6CLA1A': 0.0,
 'PTRWM_HIGH_G': 0.08,
 'PTRWM_HIGH_H': 0.33,
 'PTRWM_HIGH_L': 0.0,
 'PTRWM_HIGH_M': 0.0,
 'PTRWM_HIGH_MOBN': 0.07,
 'PTRWM_HIGH_NotFSM6CLA1A': 0.13,
 'PTSCITA_AD': 0.0,
 'PTSCITA_EXP': 1.0,
 'PTWRITTA_AD': 0.0,
 'PTWRITTA_EXP': 0.96,
 'PTWRITTA_EXP_FSM6CLA1A': 0.92,
 'PTWRITTA_EXP_H': 1.0,
 'PTWRITTA_EXP_L': 0.0,
 'PTWRITTA_EXP_M': 1.0,
 'PTWRITTA_EXP_NotFSM6CLA1A': 1.0,
 'PTWRITTA_HIGH': 0.14,
 'PTWRITTA_HIGH_FSM6CLA1A': 0.0,
 'PTWRITTA_HIGH_H': 0.5,
 'PTWRITTA_HIGH_L': 0.0,
 'PTWRITTA_HIGH_M': 0.05,
 'PTWRITTA_HIGH_NotFSM6CLA1A': 0.25,
 'PTWRITTA_WTS': 0.04,
 'READCOV': 1.0,
 'READPROG': 2.7,
 'READPROG_B': 1.0,
 'READPROG_B_LOWER': -2.1,
 'READPROG_B_UPPER': 4.1,
 'READPROG_EAL': 2.5,
 'READPROG_EAL_LOWER': -0.4,
 'READPROG_EAL_UPPER': 5.4,
 'READPROG_FSM6CLA1A': 0.9,
 'READPROG_FSM6CLA1A_LOWER': -2.7,
 'READPROG_FSM6CLA1A_UPPER': 4.5,
 'READPROG_G': 4.9,
 'READPROG_G_LOWER': 1.3,
 'READPROG_G_UPPER': 8.5,
 'READPROG_H': 2.8,
 'READPROG_H_LOWER': -2.2,
 'READPROG_H_UPPER': 7.8,
 'READPROG_L': nan,
 'READPROG_LOWER': 0.4,
 'READPROG_L_LOWER': nan,
 'READPROG_L_UPPER': nan,
 'READPROG_M': 1.9,
 'READPROG_MOBN': 2.7,
 'READPROG_MOBN_LOWER': 0.4,
 'READPROG_MOBN_UPPER': 5.0,
 'READPROG_M_LOWER': -0.9,
 'READPROG_M_UPPER': 4.7,
 'READPROG_NotFSM6CLA1A': 4.0,
 'READPROG_NotFSM6CLA1A_LOWER': 0.9,
 'READPROG_NotFSM6CLA1A_UPPER': 7.1,
 'READPROG_UPPER': 5.0,
 'READ_AVERAGE': 106.0,
 'READ_AVERAGE_FSM6CLA1A': 104.0,
 'READ_AVERAGE_H': 111.0,
 'READ_AVERAGE_L': nan,
 'READ_AVERAGE_M': 104.0,
 'READ_AVERAGE_NotFSM6CLA1A': 107.0,
 'RECTYPE': 1,
 'REGION': 32,
 'REGION NAME': 'London East',
 'RELDENOM': 'Church of England',
 'SCHNAME': "Sir John Cass's Foundation Primary School",
 'SCHNAME_AC': nan,
 'SENELN': 0.0,
 'TAB15': 0.0,
 'TAB1618': 0.0,
 'TEALGRP1': 10.0,
 'TEALGRP2': 18.0,
 'TEALGRP3': 0.0,
 'TELIG': 28.0,
 'TELNUM': '0207 2831147',
 'TFSM6CLA1A': 12.0,
 'TKS1AVERAGE': 16.0,
 'TKS1GROUP_H': 6.0,
 'TKS1GROUP_L': 2.0,
 'TKS1GROUP_M': 20.0,
 'TKS1GROUP_NA': 0.0,
 'TMOBN': 28.0,
 'TNotFSM6CLA1A': 16.0,
 'TOTPUPS': 250.0,
 'TOWN': 'London',
 'TPUPYEAR': 28.0,
 'TSENELAPK': 5.0,
 'TSENELE': 0.0,
 'TSENELK': 5.0,
 'TSENELSAP': 0.0,
 'TSENELSE': 0.0,
 'TSENELST': 0.0,
 'URN': 100000.0,
 'URN_AC': 0.0,
 'WRITCOV': 1.0,
 'WRITPROG': 2.2,
 'WRITPROG_B': 1.3,
 'WRITPROG_B_LOWER': -1.8,
 'WRITPROG_B_UPPER': 4.4,
 'WRITPROG_EAL': 2.3,
 'WRITPROG_EAL_LOWER': -0.6,
 'WRITPROG_EAL_UPPER': 5.2,
 'WRITPROG_FSM6CLA1A': 0.3,
 'WRITPROG_FSM6CLA1A_LOWER': -3.3,
 'WRITPROG_FSM6CLA1A_UPPER': 3.9,
 'WRITPROG_G': 3.4,
 'WRITPROG_G_LOWER': -0.2,
 'WRITPROG_G_UPPER': 7.0,
 'WRITPROG_H': 2.2,
 'WRITPROG_H_LOWER': -2.8,
 'WRITPROG_H_UPPER': 7.2,
 'WRITPROG_L': nan,
 'WRITPROG_LOWER': -0.1,
 'WRITPROG_L_LOWER': nan,
 'WRITPROG_L_UPPER': nan,
 'WRITPROG_M': 2.0,
 'WRITPROG_MOBN': 2.2,
 'WRITPROG_MOBN_LOWER': -0.1,
 'WRITPROG_MOBN_UPPER': 4.5,
 'WRITPROG_M_LOWER': -0.8,
 'WRITPROG_M_UPPER': 4.8,
 'WRITPROG_NotFSM6CLA1A': 3.6,
 'WRITPROG_NotFSM6CLA1A_LOWER': 0.5,
 'WRITPROG_NotFSM6CLA1A_UPPER': 6.7,
 'WRITPROG_UPPER': 4.5,
 '_id': ObjectId('5b10f2bf0fd01f08fa645404')}

In [22]:
## Initial look at the KS4 results dataset

In [23]:
ks2.find_one()['GPS_AVERAGE_L']

nan

In [24]:
ks2.find({'GPS_AVERAGE_L': np.nan}).count()

11940

Looks good.  We will need to watch out for the NaN values though.

In [25]:
ks2.find({'GPS_AVERAGE_L': np.nan}).count()

11940

In [26]:
ks2.find_one()

{'ADDRESS1': "St James's Passage",
 'ADDRESS2': "Duke's Place",
 'ADDRESS3': nan,
 'AGERANGE': '3-11',
 'ALPHAIND': 53372.0,
 'BELIG': 16.0,
 'CONFEXAM': nan,
 'DIFFN_MATPROG': 2.7,
 'DIFFN_READPROG': 0.6,
 'DIFFN_RWM_EXP': 23.0,
 'DIFFN_RWM_HIGH': -7.0,
 'DIFFN_WRITPROG': 0.2,
 'ESTAB': 3614.0,
 'GELIG': 12.0,
 'GPS_AVERAGE': 106.0,
 'GPS_AVERAGE_FSM6CLA1A': 105.0,
 'GPS_AVERAGE_H': 110.0,
 'GPS_AVERAGE_L': nan,
 'GPS_AVERAGE_M': 105.0,
 'GPS_AVERAGE_NotFSM6CLA1A': 107.0,
 'ICLOSE': 0.0,
 'LA Name': 'City of London',
 'LEA': 201.0,
 'MATCOV': 1.0,
 'MATPROG': 3.0,
 'MATPROG_B': 2.9,
 'MATPROG_B_LOWER': 0.3,
 'MATPROG_B_UPPER': 5.5,
 'MATPROG_EAL': 3.1,
 'MATPROG_EAL_LOWER': 0.6,
 'MATPROG_EAL_UPPER': 5.6,
 'MATPROG_FSM6CLA1A': 2.9,
 'MATPROG_FSM6CLA1A_LOWER': -0.1,
 'MATPROG_FSM6CLA1A_UPPER': 5.9,
 'MATPROG_G': 3.1,
 'MATPROG_G_LOWER': 0.1,
 'MATPROG_G_UPPER': 6.1,
 'MATPROG_H': 0.4,
 'MATPROG_H_LOWER': -3.9,
 'MATPROG_H_UPPER': 4.7,
 'MATPROG_L': nan,
 'MATPROG_LOWER': 1.0,
 'MATPROG_L_LOWER': nan,
 'MATPROG_L_UPPER': nan,
 'MATPROG_M': 3.3,
 'MATPROG_MOBN': 3.0,
 'MATPROG_MOBN_LOWER': 1.0,
 'MATPROG_MOBN_UPPER': 5.0,
 'MATPROG_M_LOWER': 1.0,
 'MATPROG_M_UPPER': 5.6,
 'MATPROG_NotFSM6CLA1A': 3.0,
 'MATPROG_NotFSM6CLA1A_LOWER': 0.4,
 'MATPROG_NotFSM6CLA1A_UPPER': 5.6,
 'MATPROG_UPPER': 5.0,
 'MAT_AVERAGE': 106.0,
 'MAT_AVERAGE_FSM6CLA1A': 106.0,
 'MAT_AVERAGE_H': 108.0,
 'MAT_AVERAGE_L': nan,
 'MAT_AVERAGE_M': 106.0,
 'MAT_AVERAGE_NotFSM6CLA1A': 107.0,
 'NFTYPE': 'VA',
 'OPEN_AC': nan,
 'PBELIG': 0.57,
 'PCODE': 'EC3A 5DE',
 'PGELIG': 0.43,
 'PSENELE': 0.0,
 'PSENELK': 0.18,
 'PSENELN': 0.0,
 'PSENELSAP': 0.0,
 'PSENELSAPK': 0.18,
 'PSENELSE': 0.0,
 'PSENELST': 0.0,
 'PTEALGRP1': 0.36,
 'PTEALGRP2': 0.64,
 'PTEALGRP3': 0.0,
 'PTFSM6CLA1A': 0.43,
 'PTGPS_AT': 0.0,
 'PTGPS_EXP': 0.96,
 'PTGPS_EXP_FSM6CLA1A': 1.0,
 'PTGPS_EXP_H': 1.0,
 'PTGPS_EXP_L': 0.0,
 'PTGPS_EXP_M': 0.95,
 'PTGPS_EXP_NotFSM6CLA1A': 0.94,
 'PTGPS_HIGH': 0.18,
 'PTGPS_HIGH_FSM6CLA1A': 0.0,
 'PTGPS_HIGH_H': 0.33,
 'PTGPS_HIGH_L': 0.0,
 'PTGPS_HIGH_M': 0.15,
 'PTGPS_HIGH_NotFSM6CLA1A': 0.31,
 'PTKS1GROUP_H': 0.21,
 'PTKS1GROUP_L': 0.07,
 'PTKS1GROUP_M': 0.71,
 'PTKS1GROUP_NA': 0.0,
 'PTMATTA_AD': 0.0,
 'PTMATTA_EXP': 0.96,
 'PTMAT_AT': 0.0,
 'PTMAT_EXP': 1.0,
 'PTMAT_EXP_FSM6CLA1A': 1.0,
 'PTMAT_EXP_H': 1.0,
 'PTMAT_EXP_L': 0.0,
 'PTMAT_EXP_M': 1.0,
 'PTMAT_EXP_NotFSM6CLA1A': 1.0,
 'PTMAT_HIGH': 0.18,
 'PTMAT_HIGH_FSM6CLA1A': 0.08,
 'PTMAT_HIGH_H': 0.33,
 'PTMAT_HIGH_L': 0.0,
 'PTMAT_HIGH_M': 0.15,
 'PTMAT_HIGH_NotFSM6CLA1A': 0.25,
 'PTMOBN': 1.0,
 'PTNotFSM6CLA1A': 0.57,
 'PTREADTA_AD': 0.0,
 'PTREADTA_EXP': 0.93,
 'PTREAD_AT': 0.0,
 'PTREAD_EXP': 0.93,
 'PTREAD_EXP_FSM6CLA1A': 0.92,
 'PTREAD_EXP_H': 1.0,
 'PTREAD_EXP_L': 0.0,
 'PTREAD_EXP_M': 0.9,
 'PTREAD_EXP_NotFSM6CLA1A': 0.94,
 'PTREAD_HIGH': 0.18,
 'PTREAD_HIGH_FSM6CLA1A': 0.08,
 'PTREAD_HIGH_H': 0.67,
 'PTREAD_HIGH_L': 0.0,
 'PTREAD_HIGH_M': 0.05,
 'PTREAD_HIGH_NotFSM6CLA1A': 0.25,
 'PTRWM_EXP': 0.89,
 'PTRWM_EXP_B': 0.88,
 'PTRWM_EXP_EAL': 0.83,
 'PTRWM_EXP_FSM6CLA1A': 0.83,
 'PTRWM_EXP_G': 0.92,
 'PTRWM_EXP_H': 1.0,
 'PTRWM_EXP_L': 0.0,
 'PTRWM_EXP_M': 0.9,
 'PTRWM_EXP_MOBN': 0.89,
 'PTRWM_EXP_NotFSM6CLA1A': 0.94,
 'PTRWM_HIGH': 0.07,
 'PTRWM_HIGH_B': 0.06,
 'PTRWM_HIGH_EAL': 0.11,
 'PTRWM_HIGH_FSM6CLA1A': 0.0,
 'PTRWM_HIGH_G': 0.08,
 'PTRWM_HIGH_H': 0.33,
 'PTRWM_HIGH_L': 0.0,
 'PTRWM_HIGH_M': 0.0,
 'PTRWM_HIGH_MOBN': 0.07,
 'PTRWM_HIGH_NotFSM6CLA1A': 0.13,
 'PTSCITA_AD': 0.0,
 'PTSCITA_EXP': 1.0,
 'PTWRITTA_AD': 0.0,
 'PTWRITTA_EXP': 0.96,
 'PTWRITTA_EXP_FSM6CLA1A': 0.92,
 'PTWRITTA_EXP_H': 1.0,
 'PTWRITTA_EXP_L': 0.0,
 'PTWRITTA_EXP_M': 1.0,
 'PTWRITTA_EXP_NotFSM6CLA1A': 1.0,
 'PTWRITTA_HIGH': 0.14,
 'PTWRITTA_HIGH_FSM6CLA1A': 0.0,
 'PTWRITTA_HIGH_H': 0.5,
 'PTWRITTA_HIGH_L': 0.0,
 'PTWRITTA_HIGH_M': 0.05,
 'PTWRITTA_HIGH_NotFSM6CLA1A': 0.25,
 'PTWRITTA_WTS': 0.04,
 'READCOV': 1.0,
 'READPROG': 2.7,
 'READPROG_B': 1.0,
 'READPROG_B_LOWER': -2.1,
 'READPROG_B_UPPER': 4.1,
 'READPROG_EAL': 2.5,
 'READPROG_EAL_LOWER': -0.4,
 'READPROG_EAL_UPPER': 5.4,
 'READPROG_FSM6CLA1A': 0.9,
 'READPROG_FSM6CLA1A_LOWER': -2.7,
 'READPROG_FSM6CLA1A_UPPER': 4.5,
 'READPROG_G': 4.9,
 'READPROG_G_LOWER': 1.3,
 'READPROG_G_UPPER': 8.5,
 'READPROG_H': 2.8,
 'READPROG_H_LOWER': -2.2,
 'READPROG_H_UPPER': 7.8,
 'READPROG_L': nan,
 'READPROG_LOWER': 0.4,
 'READPROG_L_LOWER': nan,
 'READPROG_L_UPPER': nan,
 'READPROG_M': 1.9,
 'READPROG_MOBN': 2.7,
 'READPROG_MOBN_LOWER': 0.4,
 'READPROG_MOBN_UPPER': 5.0,
 'READPROG_M_LOWER': -0.9,
 'READPROG_M_UPPER': 4.7,
 'READPROG_NotFSM6CLA1A': 4.0,
 'READPROG_NotFSM6CLA1A_LOWER': 0.9,
 'READPROG_NotFSM6CLA1A_UPPER': 7.1,
 'READPROG_UPPER': 5.0,
 'READ_AVERAGE': 106.0,
 'READ_AVERAGE_FSM6CLA1A': 104.0,
 'READ_AVERAGE_H': 111.0,
 'READ_AVERAGE_L': nan,
 'READ_AVERAGE_M': 104.0,
 'READ_AVERAGE_NotFSM6CLA1A': 107.0,
 'RECTYPE': 1,
 'REGION': 32,
 'REGION NAME': 'London East',
 'RELDENOM': 'Church of England',
 'SCHNAME': "Sir John Cass's Foundation Primary School",
 'SCHNAME_AC': nan,
 'SENELN': 0.0,
 'TAB15': 0.0,
 'TAB1618': 0.0,
 'TEALGRP1': 10.0,
 'TEALGRP2': 18.0,
 'TEALGRP3': 0.0,
 'TELIG': 28.0,
 'TELNUM': '0207 2831147',
 'TFSM6CLA1A': 12.0,
 'TKS1AVERAGE': 16.0,
 'TKS1GROUP_H': 6.0,
 'TKS1GROUP_L': 2.0,
 'TKS1GROUP_M': 20.0,
 'TKS1GROUP_NA': 0.0,
 'TMOBN': 28.0,
 'TNotFSM6CLA1A': 16.0,
 'TOTPUPS': 250.0,
 'TOWN': 'London',
 'TPUPYEAR': 28.0,
 'TSENELAPK': 5.0,
 'TSENELE': 0.0,
 'TSENELK': 5.0,
 'TSENELSAP': 0.0,
 'TSENELSE': 0.0,
 'TSENELST': 0.0,
 'URN': 100000.0,
 'URN_AC': 0.0,
 'WRITCOV': 1.0,
 'WRITPROG': 2.2,
 'WRITPROG_B': 1.3,
 'WRITPROG_B_LOWER': -1.8,
 'WRITPROG_B_UPPER': 4.4,
 'WRITPROG_EAL': 2.3,
 'WRITPROG_EAL_LOWER': -0.6,
 'WRITPROG_EAL_UPPER': 5.2,
 'WRITPROG_FSM6CLA1A': 0.3,
 'WRITPROG_FSM6CLA1A_LOWER': -3.3,
 'WRITPROG_FSM6CLA1A_UPPER': 3.9,
 'WRITPROG_G': 3.4,
 'WRITPROG_G_LOWER': -0.2,
 'WRITPROG_G_UPPER': 7.0,
 'WRITPROG_H': 2.2,
 'WRITPROG_H_LOWER': -2.8,
 'WRITPROG_H_UPPER': 7.2,
 'WRITPROG_L': nan,
 'WRITPROG_LOWER': -0.1,
 'WRITPROG_L_LOWER': nan,
 'WRITPROG_L_UPPER': nan,
 'WRITPROG_M': 2.0,
 'WRITPROG_MOBN': 2.2,
 'WRITPROG_MOBN_LOWER': -0.1,
 'WRITPROG_MOBN_UPPER': 4.5,
 'WRITPROG_M_LOWER': -0.8,
 'WRITPROG_M_UPPER': 4.8,
 'WRITPROG_NotFSM6CLA1A': 3.6,
 'WRITPROG_NotFSM6CLA1A_LOWER': 0.5,
 'WRITPROG_NotFSM6CLA1A_UPPER': 6.7,
 'WRITPROG_UPPER': 4.5,
 '_id': ObjectId('5b10f2bf0fd01f08fa645404')}

In [27]:
# to save resources we can now remove delete the ks2_df
del ks2_df

<a name="importing_ks4"></a>

## Importing the KS4 results dataset

Before we can investigate the data we will need to have a look at it, determine what cleaning if any needs to be done, and store it for access in an appropriate form.

### Look at the KS4 results dataset
Let's have a quick look at the data we will be looking at for the EMA.

In [28]:
!head -5 'data/2015-2016/england_ks4final.csv'

In [29]:
!wc -l 'data/2015-2016/england_ks4final.csv'

5489 data/2015-2016/england_ks4final.csv

The dataset has 5489 rows of data, there appears to be a large number of columns and a lot of codes that I'll need to look up.  There are a also a number of `NA` and `NP` values that could be missing data.  As well as this results data I will need to find and import the relevent metadata file.

Looking through the data/2015-2016 folder there are a number of files that have information on these codes.

In [30]:
!ls data/2015-2016/

abbreviations.xlsx	    england_swf.csv
abs_meta.csv		    england_vaqual.csv
census_meta.csv		    england_vasubj.csv
england_abs.csv		    keto_setup.xlsx
england_census.csv	    ks2_meta.csv
england_cfrfull.xlsx	    ks4_meta.csv
england_ks2final.csv	    ks4_meta_methodology.csv
england_ks4final.csv	    ks4-pupdest_meta.csv
england_ks4-pupdest.csv     ks5_meta.csv
england_ks4underlying.xlsx  ks5-studest_meta.csv
england_ks5final.csv	    la_and_region_codes_meta.csv
england_ks5-studest.csv     sixth_form_centres_and_consortia_meta.xlsx
england_ks5underlying.xlsx  spine_meta.csv
england_spine.csv	    swf_meta.csv

There is an abbreviations file, stored as an xlsx file.  I'll have a quick glance at it in excel.  Having looked the abbreviation up in the abbreviations file we can see that they have the following meanings:

- _NA_: Not applicable
- _NP_: Not Published
- _NE_: No entries
- _SUPP_: Suppressed (5 or fewer in cohort)
- _LOWCOV_: Low coverage (less than 50% of the cohort
- _NEW_: New institution

The abbreviations file also has listings of all the school types (NFTYPE) that I will need.  I'll grab that for use later on.

## Importing the abbreviations file

In [31]:
# read in the abbreviations file
abbr_df = pd.read_excel('data/2015-2016/abbreviations.xlsx')
abbr_df

,2016 KS4 and KS5/16-18 Performance Tables,Unnamed: 1,Unnamed: 2
0,Abbreviations used in the csv and excel Downlo...,NaN,NaN
1,NaN,NaN,NaN
2,Institution type (NFTYPE):,NaN,NaN
3,AC,Sponsored academy,NaN
4,ACC,Academy converter - mainstream,NaN
5,AC1619,Academy 16-19 sponsor led,NaN
6,ACC1619,Academy 16-19 converter,NaN
7,ACCS,Academy converter - special school,NaN
8,ACS,Sponsored special academy,NaN
9,CTC,City technology college,NaN
10,CY,Community school,NaN
11,CYS,Community special school,NaN
12,F,Free school - mainstream,NaN
13,FESI,Further Education Sector Institution,NaN
14,FD,Foundation school,NaN
15,FDS,Foundation special school,NaN
16,FS,Free school - special,NaN
17,FSS,Studio school,NaN
18,FUTC,UTC (university technical college),NaN
19,F1619,Free school - 16-19,NaN
20,IND,Independent school,NaN
21,INDSPEC,Independent special school,NaN
22,MODFC,College funded by Ministry of Defence,NaN
23,NMSS,Non-maintained special school,NaN
24,VA,Voluntary aided school,NaN
25,VC,Voluntary controlled school,NaN
26,NaN,NaN,NaN
27,Types of further education (FE) institutions:,NaN,NaN
28,Agriculture and horticultural college,NaN,NaN
29,"Art, design and performing arts college",NaN,NaN
30,General further education college,NaN,NaN
31,General further education college (special),NaN,NaN
32,Sixth form college,NaN,NaN
33,Specialist designated college,NaN,NaN
34,Tertiary college,NaN,NaN
35,NaN,NaN,NaN
36,Admissions policy (ADMPOL):,NaN,NaN
37,COMP,Comprehensive,NaN
38,MOD,Modern,NaN
39,SEL,Selective,NaN
40,NA,Not applicable: figures are either not availab...,NaN
41,UK,Unknown,NaN
42,<blank>,Admissions policy information is not available...,NaN
43,NaN,NaN,NaN
44,General abbreviations:,NaN,NaN
45,NEW,New institution,NaN
46,NE,No entries,NaN
47,NaN,Not applicable: figures are either not availab...,NaN
48,SUPP,Indicates that a school or college's figures h...,NaN
49,NP,Not published - for example we do not publish ...,NaN
50,LOWCOV,Low coverage: indicates that a schoolâs Progre...,NaN
51,NaN,NaN,NaN
52,Notes:,NaN,NaN
53,The 2016 secondary and 16-18 performance table...,NaN,NaN
54,If a school converted to an academy during the...,NaN,NaN
55,The KS4 and KS5 metadata files provide descrip...,NaN,NaN

We can see that the school types are rows 2-25, I'll store them as a dict for reference later on.

In [32]:
# relabel the columns
abbr_df.columns = ['label', 'expanded', 'not_needed']

In [33]:
nftypes = {}
for index, row in abbr_df[3:26].iterrows():
    nftypes[row['label'].strip()] = row['expanded'].strip()
    
nftypes

{'AC': 'Sponsored academy',
 'AC1619': 'Academy 16-19 sponsor led',
 'ACC': 'Academy converter - mainstream',
 'ACC1619': 'Academy 16-19 converter',
 'ACCS': 'Academy converter - special school',
 'ACS': 'Sponsored special academy',
 'CTC': 'City technology college',
 'CY': 'Community school',
 'CYS': 'Community special school',
 'F': 'Free school - mainstream',
 'F1619': 'Free school - 16-19',
 'FD': 'Foundation school',
 'FDS': 'Foundation special school',
 'FESI': 'Further Education Sector Institution',
 'FS': 'Free school - special',
 'FSS': 'Studio school',
 'FUTC': 'UTC (university technical college)',
 'IND': 'Independent school',
 'INDSPEC': 'Independent special school',
 'MODFC': 'College funded by Ministry of Defence',
 'NMSS': 'Non-maintained special school',
 'VA': 'Voluntary aided school',
 'VC': 'Voluntary controlled school'}

And, while we have the abbreviations available I'll store the missing value types for reference later on if needed.

In [34]:
missing_types = {}
for i, r in abbr_df[45:51].iterrows():
    missing_types[r['label']] = r['expanded']

missing_types

{'NEW': 'New institution',
 nan: 'Not applicable: figures are either not available for the year in question, or the data field is not applicable to this school or college',
 'NE': 'No entries',
 'SUPP': "Indicates that a school or college's figures have been suppressed because there are 5 or fewer pupils in the cohort",
 'LOWCOV': 'Low coverage: indicates that a schoolâs Progress 8 or value added measures have been suppressed because coverage is less than 50% of the cohort',
 'NP': 'Not published - for example we do not publish Progress 8 data for independent schools and independent special schools, or breakdowns by disadvantaged and non-disadvantaged pupils for independent schools, independent special schools and non-maintained special schools.'}

I can now delete the abbr_df as it won't be needed.

In [35]:
del abbr_df

## Importing the KS4 Metadata file

In order to analyse the data we need to be able to reference the columns and the codes they represent.  I'll import the KS4_meta.csv file into the database and use it to help me understand the data in the KS4 results dataset.

In [36]:
!head -5 data/2015-2016/ks4_meta.csv

372,TAVENT_GNFSM6CLA1A_15_PTQ_EE,Average number of GCSE entries per non-disadvantaged pupil in 2015,,,,Yes,,,

In [37]:
!wc -l data/2015-2016/ks4_meta.csv

0 data/2015-2016/ks4_meta.csv

0 lines.. I'll try loding directly into Mongo

In [38]:
!/usr/bin/mongoimport --port 27351 --drop --db schools_db --collection ks4_meta \
    --type csv --headerline --ignoreBlanks \
    --file data/2015-2016/ks4_meta.csv

2018-06-01T07:16:19.208+0000	Failed: fields cannot be identical: '' and ''
2018-06-01T07:16:19.208+0000	imported 0 documents

Clearly there is an issue with the import.  I'll try importing it into a dataframe.

In [39]:
ks4_meta_df = pd.read_csv('data/2015-2016/ks4_meta.csv')
ks4_meta_df.head()

,Column,Metafile heading,Metafile description,Methodology changes,Null field for special schools,Null field for local authority records,Null field for National (all schools) records,Null field for National (maintained schools) records,Unnamed: 8,Unnamed: 9
0,1,RECTYPE,Record type (1=mainstream school; 2=special sc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,ALPHAIND,Alphabetic sorting index,NaN,NaN,Yes,Yes,Yes,NaN,NaN
2,3,LEA,Local authority code (see separate list of loc...,NaN,NaN,NaN,Yes,Yes,NaN,NaN
3,4,ESTAB,Establishment number,NaN,NaN,Yes,Yes,Yes,NaN,NaN
4,5,URN,School Unique Reference Number,NaN,NaN,Yes,Yes,Yes,NaN,NaN

That imported ok.  But there are a few extra columns for my needs (I only need it to look up the description for a given term)

In [40]:
# reduce the dataframe to the columns of interest
ks4_meta_df = ks4_meta_df[['Metafile heading', 'Metafile description']]
# relabel them to match my target format
ks4_meta_df.columns = ['label', 'expanded']
# check it looks ok
ks4_meta_df

,label,expanded
0,RECTYPE,Record type (1=mainstream school; 2=special sc...
1,ALPHAIND,Alphabetic sorting index
2,LEA,Local authority code (see separate list of loc...
3,ESTAB,Establishment number
4,URN,School Unique Reference Number
5,SCHNAME,School name
6,SCHNAME_AC,School now known as (used if the school has co...
7,ADDRESS1,School address (1)
8,ADDRESS2,School address (2)
9,ADDRESS3,School address (3)
10,TOWN,School town
11,PCODE,School postcode
12,TELNUM,School telephone number
13,CONTFLAG,Contingency flag - school results 'significant...
14,ICLOSE,Closed school flag (0=open; 1=closed)
15,NFTYPE,School type (see separate list of abbreviation...
16,RELDENOM,School religious character
17,ADMPOL,School admissions policy (self-declared by sch...
18,EGENDER,School gender of entry
19,FEEDER,Indicates whether school is a feeder school fo...
20,TABKS2,Indicates whether school is published in the p...
21,TAB1618,Indicates whether school is published in the s...
22,AGERANGE,Age range
23,CONFEXAM,Indicates whether the school has checked its r...
24,TOTPUPS,Number of pupils on roll (all ages)
25,NUMBOYS,Total boys on roll (including part-time pupils)
26,NUMGIRLS,Total girls on roll (including part-time pupils)
27,TPUP,Number of pupils at the end of key stage 4
28,BPUP,Number of boys at the end of key stage 4
29,PBPUP,Percentage of pupils at the end of key stage 4...
...,...,...
342,TNOTFSMCLA_14,Number of non-disadvantaged pupils at the end ...
343,PTNOTFSMCLA_14,Percentage of pupils at the end of key stage 4...
344,TFSM6CLA1A_15,Number of disadvantaged pupils at the end of k...
345,PTFSM6CLA1A_15,Percentage of pupils at the end of key stage 4...
346,TNOTFSM6CLA1A_15,Number of non-disadvantaged pupils at the end ...
347,PTNOTFSM6CLA1A_15,Percentage of pupils at the end of key stage 4...
348,TAVENT_E_3NG_PTQ_EE,Average number of GCSE and equivalents entries...
349,TAVENT_E_3NG_LO_PTQ_EE,Average number of GCSE and equivalents entries...
350,TAVENT_E_3NG_AV_PTQ_EE,Average number of GCSE and equivalents entries...
351,TAVENT_E_3NG_HI_PTQ_EE,Average number of GCSE and equivalents entries...
352,TAVENT_E_3NG_FSM6CLA1A_PTQ_EE,Average number of GCSE and equivalents entries...
353,TAVENT_E_3NG_NFSM6CLA1A_PTQ_EE,Average number of GCSE and equivalents entries...
354,TAVENT_EFSM_13,Average number of GCSE and equivalents entries...
355,TAVENT_ENFSM_13,Average number of GCSE and equivalents entries...
356,TAVENT_EFSM_14_PTQ,Average number of GCSE and equivalents entries...
357,TAVENT_ENFSM_14_PTQ,Average number of GCSE and equivalents entries...
358,TAVENT_EFSM6CLA1A_15_PTQ_EE,Average number of GCSE and equivalents entries...
359,TAVENT_ENFSM6CLA1A_15_PTQ_EE,Average number of GCSE and equivalents entries...
360,TAVENT_G_PTQ_EE,Average number of GCSE entries per pupil
361,TAVENT_GLO_PTQ_EE,Average number of GCSE entries per pupil with ...
362,TAVENT_GAV_PTQ_EE,Average number of GCSE entries per pupil with ...
363,TAVENT_GHI_PTQ_EE,Average number of GCSE entries per pupil with ...
364,TAVENT_GFSM6CLA1A_PTQ_EE,Average number of GCSE entries per disadvantag...
365,TAVENT_GNFSM6CLA1A_PTQ_EE,Average number of GCSE entries per non-disadva...
366,TAVENT_GFSM_13,Average number of GCSE entries per disadvantag...
367,TAVENT_GNFSM_13,Average number of GCSE entries per non-disadva...
368,TAVENT_GFSM_14_PTQ,Average number of GCSE entries per disadvantag...
369,TAVENT_GNFSM_14_PTQ,Average number of GCSE entries per non-disadva...
370,TAVENT_GFSM6CLA1A_15_PTQ_EE,Average number of GCSE entries per disadvantag...
371,TAVENT_GNFSM6CLA1A_15_PTQ_EE,Average number of GCSE entries per non-disadva...

In [41]:
# set up a reference to the db.collection 
ks4_meta = db.ks4_meta

In [42]:
ks4_meta.insert_many(ks4_meta_df.to_dict('records'))
# snippet reference is from:
# https://stackoverflow.com/questions/33979983/insert-rows-from-pandas-dataframe-into-mongodb-collection-as-individual-document

In [43]:
ks4_meta.find_one({'label': 'NFTYPE'})

{'_id': ObjectId('5b10f2c30fd01f08fa649335'),
 'expanded': 'School type (see separate list of abbreviations used in the tables)',
 'label': 'NFTYPE'}

I want to add the codes from the abbreviations dictionary to this document since it is one of the backdones to my investigation.

In [44]:
ks4_meta.update_one({'label': 'NFTYPE'}, 
                    {'$set': {'codes': nftypes}})

ks4_meta.find_one({'label': 'NFTYPE'})

{'_id': ObjectId('5b10f2c30fd01f08fa649335'),
 'codes': {'AC': 'Sponsored academy',
  'AC1619': 'Academy 16-19 sponsor led',
  'ACC': 'Academy converter - mainstream',
  'ACC1619': 'Academy 16-19 converter',
  'ACCS': 'Academy converter - special school',
  'ACS': 'Sponsored special academy',
  'CTC': 'City technology college',
  'CY': 'Community school',
  'CYS': 'Community special school',
  'F': 'Free school - mainstream',
  'F1619': 'Free school - 16-19',
  'FD': 'Foundation school',
  'FDS': 'Foundation special school',
  'FESI': 'Further Education Sector Institution',
  'FS': 'Free school - special',
  'FSS': 'Studio school',
  'FUTC': 'UTC (university technical college)',
  'IND': 'Independent school',
  'INDSPEC': 'Independent special school',
  'MODFC': 'College funded by Ministry of Defence',
  'NMSS': 'Non-maintained special school',
  'VA': 'Voluntary aided school',
  'VC': 'Voluntary controlled school'},
 'expanded': 'School type (see separate list of abbreviations used in the tables)',
 'label': 'NFTYPE'}

I'll do the same for the `RECTYPE` label by splitting the description.

In [45]:
# select the correct document
r = ks4_meta.find_one({'label': 'RECTYPE'})

# checks that we haven't already updated the document
# then if not splits the description string, adding a code key
# to reference each school type
if 'codes' not in r.keys():
    expanded = r['expanded']
    e = expanded[:11]
    codelist = expanded[13:-1].split('; ')
    keys = [c[:1] for c in codelist]
    values = [c[2:] for c in codelist]
    codes = (dict(list(zip(keys, values))))
    ks4_meta.update_one({'_id': r['_id']},
                        {'$set': {'expanded': e,
                                  'codes': codes}})

# check that it was processed correctly
ks4_meta.find_one({'label': 'RECTYPE'})

{'_id': ObjectId('5b10f2c30fd01f08fa649326'),
 'codes': {'1': 'mainstream school',
  '2': 'special school',
  '4': 'local authority',
  '5': 'National (all schools)',
  '7': 'National (maintained schools)'},
 'expanded': 'Record type',
 'label': 'RECTYPE'}

Great.  That is most of the cleaning I need to do for the ks4_meta file.  If I were to be doing a different investigation I would consider merging in the LEA data here, but we already have it stored from earlier on (importing ks2) as a dataframe which we can reference if needed.

Great.  Now in the tm351 module materials we had some handy collections provided by the module team that enabled us to quickly look up the labels and codes of a given accident.  I'll borrow that idea here for my purposes.  Because, I will need to do the same for the KS2 dataset, I'll wrap them in a function.

In [46]:
# code adapted from the p14 accidents dataset notebooks

def expanded_label(meta):
    # Load the expanded names of keys and human-readable codes into memory
    expanded_name = collections.defaultdict(str)
    for e in meta.find({'expanded': {"$exists": True}}):
        expanded_name[e['label']] = e['expanded']

    label_of = collections.defaultdict(str)
    for l in meta.find({'codes': {"$exists": True}}):
        for c in l['codes']:
            try:
                label_of[l['label'], int(c)] = l['codes'][c]
            except ValueError: 
                label_of[l['label'], c] = l['codes'][c]
    # return both as a tuple
    return (expanded_name, label_of)

In [47]:
# Set up the expanded_name and label_of for ks4_meta
ks4_expanded_name, ks4_label_of = expanded_label(ks4_meta)

In [48]:
# test it works
[(c, ks4_label_of['RECTYPE', c]) for k, c in ks4_label_of if k == 'RECTYPE']

[(2, 'special school'),
 (4, 'local authority'),
 (1, 'mainstream school'),
 (5, 'National (all schools)'),
 (7, 'National (maintained schools)')]

In [49]:
ks4_expanded_name['NFTYPE']

'School type (see separate list of abbreviations used in the tables)'

In [50]:
ks4_label_of['NFTYPE', 'AC']

'Sponsored academy'

Great that all is working, I can now delete the ks4_meta_df, as the information is stored.

In [51]:
del ks4_meta_df

I'll quickly repeat the same steps for KS2_meta data to include the codes.

In [52]:
# relabel the columns of ks2cols
ks2cols.columns = ['not_needed', 'label', 'expanded']

# create a collection in the database
ks2_meta = db.ks2_meta

In [53]:
# store them into the database
ks2_meta.insert_many(ks2cols[['label', 'expanded']].to_dict('records'))

In [54]:
ks2_meta.find_one()

{'_id': ObjectId('5b10f2c30fd01f08fa64949a'),
 'expanded': 'Record type (1=mainstream school; 2=special school; 3=Local Authority; 4=National (all schools); 5=National (maintained schools))',
 'label': 'RECTYPE'}

In [55]:
# repeat the splitting of the `RECTYPE`
# select the correct document
r = ks2_meta.find_one({'label': 'RECTYPE'})

# checks that we haven't already updated the document
# then if not splits the description string, adding a code key
# to reference each school type
if 'codes' not in r.keys():
    expanded = r['expanded']
    e = expanded[:11]
    codelist = expanded[13:-1].split('; ')
    keys = [c[:1] for c in codelist]
    values = [c[2:] for c in codelist]
    codes = (dict(list(zip(keys, values))))
    ks2_meta.update_one({'_id': r['_id']},
                        {'$set': {'expanded': e,
                                  'codes': codes}})

# check that it was processed correctly
ks2_meta.find_one({'label': 'RECTYPE'})

{'_id': ObjectId('5b10f2c30fd01f08fa64949a'),
 'codes': {'1': 'mainstream school',
  '2': 'special school',
  '3': 'Local Authority',
  '4': 'National (all schools)',
  '5': 'National (maintained schools)'},
 'expanded': 'Record type',
 'label': 'RECTYPE'}

In [56]:
# And add the nftype to the meta collection
ks2_meta.update_one({'label': 'NFTYPE'}, 
                    {'$set': {'codes': nftypes}})

ks2_meta.find_one({'label': 'NFTYPE'})

{'_id': ObjectId('5b10f2c30fd01f08fa6494a9'),
 'codes': {'AC': 'Sponsored academy',
  'AC1619': 'Academy 16-19 sponsor led',
  'ACC': 'Academy converter - mainstream',
  'ACC1619': 'Academy 16-19 converter',
  'ACCS': 'Academy converter - special school',
  'ACS': 'Sponsored special academy',
  'CTC': 'City technology college',
  'CY': 'Community school',
  'CYS': 'Community special school',
  'F': 'Free school - mainstream',
  'F1619': 'Free school - 16-19',
  'FD': 'Foundation school',
  'FDS': 'Foundation special school',
  'FESI': 'Further Education Sector Institution',
  'FS': 'Free school - special',
  'FSS': 'Studio school',
  'FUTC': 'UTC (university technical college)',
  'IND': 'Independent school',
  'INDSPEC': 'Independent special school',
  'MODFC': 'College funded by Ministry of Defence',
  'NMSS': 'Non-maintained special school',
  'VA': 'Voluntary aided school',
  'VC': 'Voluntary controlled school'},
 'expanded': 'School type',
 'label': 'NFTYPE'}

In [57]:
# finally, set up the expanded_name and label_of for ks4_meta
ks2_expanded_name, ks2_label_of = expanded_label(ks2_meta)

check they work ok

In [58]:
# test it works
[(c, ks2_label_of['RECTYPE', c]) for k, c in ks4_label_of if k == 'RECTYPE']

[(2, 'special school'),
 (4, 'National (all schools)'),
 (1, 'mainstream school'),
 (5, 'National (maintained schools)'),
 (7, '')]

In [59]:
ks2_label_of['NFTYPE', 'IND']

'Independent school'

In [60]:
ks2_expanded_name['TELIG']

'Published eligible pupil number'

Great that is all the meta data handled, and we can now go about importing the KS4 data into the database and cleaning it.

In [61]:
# delete the ks2cols dataframe as we don't need it anymore
del ks2cols

## Importing the KS4 dataset

Before I import the data I will have another quick look at the file.

In [62]:
! head -5 'data/2015-2016/england_ks4final.csv'

To restate what was noted earlier there appears to be a great number of columns, and a large number of missing values.  How many rows are there?

In [63]:
!wc -l 'data/2015-2016/england_ks4final.csv'

5489 data/2015-2016/england_ks4final.csv

Let's carry out similar steps to those we carried out in importing the ks2 data.  Again this is going to be adapted from the TMA02-Q2

In [64]:
ks4_df = pd.read_csv('data/2015-2016/england_ks4final.csv')
ks4_df.head()

/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,RECTYPE,ALPHAIND,LEA,ESTAB,URN,SCHNAME,SCHNAME_AC,ADDRESS1,ADDRESS2,ADDRESS3,...,TAVENT_GAV_PTQ_EE,TAVENT_GHI_PTQ_EE,TAVENT_GFSM6CLA1A_PTQ_EE,TAVENT_GNFSM6CLA1A_PTQ_EE,TAVENT_GFSM_13,TAVENT_GNFSM_13,TAVENT_GFSM_14_PTQ,TAVENT_GNFSM_14_PTQ,TAVENT_GFSM6CLA1A_15_PTQ_EE,TAVENT_GNFSM6CLA1A_15_PTQ_EE
0,1,11828,201,6007,100003,City of London School,,Queen Victoria Street,,,...,NP,NP,NP,NP,NaN,NaN,NaN,NaN,NaN,NaN
1,1,11830,201,6005,100001,City of London School for Girls,,St Giles' Terrace,Barbican,,...,NP,NP,NP,NP,NaN,NaN,NaN,NaN,NaN,NaN
2,4,,201,,,,,,,,...,,,,,,,,,,
3,1,368,202,4285,100053,Acland Burghley School,,Burghley Road,,,...,8.9,9.8,8.4,9.5,8.1,9.8,9,10.2,8.4,10.6
4,1,9318,202,4611,100054,The Camden School for Girls,,Sandall Road,,,...,8.2,10.2,7.8,9.8,8.6,9.3,7.3,8.6,7.5,8.9

A straight import gives an error (`DtypeWarning`).  Let's look at the file using the tools learned in p2 of the tm351 materials.

In [65]:
# let's quickly look at the file using command line
!file 'data/2015-2016/england_ks4final.csv'

data/2015-2016/england_ks4final.csv: UTF-8 Unicode (with BOM) text, with very long lines, with CRLF line terminators

In [66]:
# and check it using chardet
import chardet

# open the file and read the contents in as a byte object
testfile = open('data/2015-2016/england_ks4final.csv', 'rb').read()

# detect the file encoding
chardet.detect(testfile)

{'confidence': 1.0, 'encoding': 'UTF-8-SIG'}

ks4_df = pd.read_csv('data/2015-2016/england_ks4final.csv', encoding='UTF-8-SIG')
ks4_df.head()

In [67]:
ks4_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5489 entries, 0 to 5488
Columns: 372 entries, RECTYPE to TAVENT_GNFSM6CLA1A_15_PTQ_EE
dtypes: int64(1), object(371)
memory usage: 15.6+ MB

In [68]:
ks4_df.describe()

           RECTYPE
count  5489.000000
mean      1.292403
std       0.617070
min       1.000000
25%       1.000000
50%       1.000000
75%       1.000000
max       7.000000

In [69]:
ks4_df.dtypes

RECTYPE                            int64
ALPHAIND                          object
LEA                               object
ESTAB                             object
URN                               object
SCHNAME                           object
SCHNAME_AC                        object
ADDRESS1                          object
ADDRESS2                          object
ADDRESS3                          object
TOWN                              object
PCODE                             object
TELNUM                            object
CONTFLAG                          object
ICLOSE                            object
NFTYPE                            object
RELDENOM                          object
ADMPOL                            object
EGENDER                           object
FEEDER                            object
TABKS2                            object
TAB1618                           object
AGERANGE                          object
CONFEXAM                          object
TOTPUPS                           object
NUMBOYS                           object
NUMGIRLS                          object
TPUP                              object
BPUP                              object
PBPUP                             object
                                   ...
TNOTFSMCLA_14                     object
PTNOTFSMCLA_14                    object
TFSM6CLA1A_15                     object
PTFSM6CLA1A_15                    object
TNOTFSM6CLA1A_15                  object
PTNOTFSM6CLA1A_15                 object
TAVENT_E_3NG_PTQ_EE               object
TAVENT_E_3NG_LO_PTQ_EE            object
TAVENT_E_3NG_AV_PTQ_EE            object
TAVENT_E_3NG_HI_PTQ_EE            object
TAVENT_E_3NG_FSM6CLA1A_PTQ_EE     object
TAVENT_E_3NG_NFSM6CLA1A_PTQ_EE    object
TAVENT_EFSM_13                    object
TAVENT_ENFSM_13                   object
TAVENT_EFSM_14_PTQ                object
TAVENT_ENFSM_14_PTQ               object
TAVENT_EFSM6CLA1A_15_PTQ_EE       object
TAVENT_ENFSM6CLA1A_15_PTQ_EE      object
TAVENT_G_PTQ_EE                   object
TAVENT_GLO_PTQ_EE                 object
TAVENT_GAV_PTQ_EE                 object
TAVENT_GHI_PTQ_EE                 object
TAVENT_GFSM6CLA1A_PTQ_EE          object
TAVENT_GNFSM6CLA1A_PTQ_EE         object
TAVENT_GFSM_13                    object
TAVENT_GNFSM_13                   object
TAVENT_GFSM_14_PTQ                object
TAVENT_GNFSM_14_PTQ               object
TAVENT_GFSM6CLA1A_15_PTQ_EE       object
TAVENT_GNFSM6CLA1A_15_PTQ_EE      object
Length: 372, dtype: object

Most of the columns are mixed with an 'object' datatype.

In [70]:
ks4_dt_df = pd.DataFrame()
for col in ks4_df.columns:
    ks4_dt_df[col] = pd.to_numeric(ks4_df[col], errors='ignore')

ks4_dt_df.head()

,RECTYPE,ALPHAIND,LEA,ESTAB,URN,SCHNAME,SCHNAME_AC,ADDRESS1,ADDRESS2,ADDRESS3,...,TAVENT_GAV_PTQ_EE,TAVENT_GHI_PTQ_EE,TAVENT_GFSM6CLA1A_PTQ_EE,TAVENT_GNFSM6CLA1A_PTQ_EE,TAVENT_GFSM_13,TAVENT_GNFSM_13,TAVENT_GFSM_14_PTQ,TAVENT_GNFSM_14_PTQ,TAVENT_GFSM6CLA1A_15_PTQ_EE,TAVENT_GNFSM6CLA1A_15_PTQ_EE
0,1,11828,201,6007,100003,City of London School,,Queen Victoria Street,,,...,NP,NP,NP,NP,NaN,NaN,NaN,NaN,NaN,NaN
1,1,11830,201,6005,100001,City of London School for Girls,,St Giles' Terrace,Barbican,,...,NP,NP,NP,NP,NaN,NaN,NaN,NaN,NaN,NaN
2,4,,201,,,,,,,,...,,,,,,,,,,
3,1,368,202,4285,100053,Acland Burghley School,,Burghley Road,,,...,8.9,9.8,8.4,9.5,8.1,9.8,9,10.2,8.4,10.6
4,1,9318,202,4611,100054,The Camden School for Girls,,Sandall Road,,,...,8.2,10.2,7.8,9.8,8.6,9.3,7.3,8.6,7.5,8.9

In [71]:
ks4_dt_df.dtypes

RECTYPE                            int64
ALPHAIND                          object
LEA                               object
ESTAB                             object
URN                               object
SCHNAME                           object
SCHNAME_AC                        object
ADDRESS1                          object
ADDRESS2                          object
ADDRESS3                          object
TOWN                              object
PCODE                             object
TELNUM                            object
CONTFLAG                          object
ICLOSE                            object
NFTYPE                            object
RELDENOM                          object
ADMPOL                            object
EGENDER                           object
FEEDER                            object
TABKS2                            object
TAB1618                           object
AGERANGE                          object
CONFEXAM                          object
TOTPUPS                           object
NUMBOYS                           object
NUMGIRLS                          object
TPUP                              object
BPUP                              object
PBPUP                             object
                                   ...
TNOTFSMCLA_14                     object
PTNOTFSMCLA_14                    object
TFSM6CLA1A_15                     object
PTFSM6CLA1A_15                    object
TNOTFSM6CLA1A_15                  object
PTNOTFSM6CLA1A_15                 object
TAVENT_E_3NG_PTQ_EE               object
TAVENT_E_3NG_LO_PTQ_EE            object
TAVENT_E_3NG_AV_PTQ_EE            object
TAVENT_E_3NG_HI_PTQ_EE            object
TAVENT_E_3NG_FSM6CLA1A_PTQ_EE     object
TAVENT_E_3NG_NFSM6CLA1A_PTQ_EE    object
TAVENT_EFSM_13                    object
TAVENT_ENFSM_13                   object
TAVENT_EFSM_14_PTQ                object
TAVENT_ENFSM_14_PTQ               object
TAVENT_EFSM6CLA1A_15_PTQ_EE       object
TAVENT_ENFSM6CLA1A_15_PTQ_EE      object
TAVENT_G_PTQ_EE                   object
TAVENT_GLO_PTQ_EE                 object
TAVENT_GAV_PTQ_EE                 object
TAVENT_GHI_PTQ_EE                 object
TAVENT_GFSM6CLA1A_PTQ_EE          object
TAVENT_GNFSM6CLA1A_PTQ_EE         object
TAVENT_GFSM_13                    object
TAVENT_GNFSM_13                   object
TAVENT_GFSM_14_PTQ                object
TAVENT_GNFSM_14_PTQ               object
TAVENT_GFSM6CLA1A_15_PTQ_EE       object
TAVENT_GNFSM6CLA1A_15_PTQ_EE      object
Length: 372, dtype: object

I'm not getting very far here.  I'll try and follow the steps from Q2. If after that I have still made no progress I think that the most efficient way to get to the bottom of it will be to take a look at the file in OpenRefine to clean the mixed datatypes and determine what to do with the missing data.

In [72]:
leas_df

     LEA                       LA Name  REGION   REGION NAME
0    841                    Darlington       1  North East A
1    840                 County Durham       1  North East A
2    805                    Hartlepool       1  North East A
3    806                 Middlesbrough       1  North East A
4    807          Redcar and Cleveland       1  North East A
5    808              Stockton-on-Tees       1  North East A
6    390                     Gateshead       3  North East B
7    391           Newcastle upon Tyne       3  North East B
8    392                North Tyneside       3  North East B
9    929                Northumberland       3  North East B
10   393                South Tyneside       3  North East B
11   394                    Sunderland       3  North East B
12   889         Blackburn with Darwen       6  North West A
13   890                     Blackpool       6  North West A
14   909                       Cumbria       6  North West A
15   888                    Lancashire       6  North West A
16   350                        Bolton       7  North West B
17   351                          Bury       7  North West B
18   352                    Manchester       7  North West B
19   353                        Oldham       7  North West B
20   354                      Rochdale       7  North West B
21   355                       Salford       7  North West B
22   356                     Stockport       7  North West B
23   357                      Tameside       7  North West B
24   358                      Trafford       7  North West B
25   359                         Wigan       7  North West B
26   895                 Cheshire East       9  North West C
27   896       Cheshire West & Chester       9  North West C
28   876                        Halton       9  North West C
29   340                      Knowsley       9  North West C
..   ...                           ...     ...           ...
122  871                        Slough      36  South East A
123  869                West Berkshire      36  South East A
124  868        Windsor and Maidenhead      36  South East A
125  872                     Wokingham      36  South East A
126  850                     Hampshire      37  South East B
127  921                 Isle of Wight      37  South East B
128  851                    Portsmouth      37  South East B
129  852                   Southampton      37  South East B
130  936                        Surrey      38  South East C
131  938                   West Sussex      38  South East C
132  846             Brighton and Hove      39  South East D
133  845                   East Sussex      39  South East D
134  886                          Kent      39  South East D
135  887                        Medway      39  South East D
136  837                   Bournemouth      43  South West A
137  908                      Cornwall      43  South West A
138  878                         Devon      43  South West A
139  835                        Dorset      43  South West A
140  420               Isles of Scilly      43  South West A
141  879                      Plymouth      43  South West A
142  836                         Poole      43  South West A
143  933                      Somerset      43  South West A
144  880                        Torbay      43  South West A
145  800  Bath and North East Somerset      45  South West B
146  801              Bristol, City of      45  South West B
147  916               Gloucestershire      45  South West B
148  802                North Somerset      45  South West B
149  803         South Gloucestershire      45  South West B
150  866                       Swindon      45  South West B
151  865                     Wiltshire      45  South West B

[152 rows x 4 columns]

I'll find out which columns have percentages in them.

In [73]:
# Look through the meta file and get the columns that are percentages.
percent_cols_list = [(l, ks4_expanded_name[l]) 
                     for l in ks4_expanded_name 
                     if 'percent' in ks4_expanded_name[l].lower()]
percent_cols_list

[('PTEBACC_ELO_PTQ_EE',
  'Percentage of pupils with low prior attainment with entries in all English Baccalaureate subject areas'),
 ('PTEBACENG_LL_PTQ_EE',
  'Percentage of pupils achieving the English Baccalaureate English subject area '),
 ('P8MEACOV',
  'Percentage of pupils at the end of key stage 4 included in Progress 8 measure'),
 ('PTEBACCAV_PTQ_EE',
  'Percentage of pupils with middle prior attainment achieving the English Baccalaureate'),
 ('PTL2BASICS_13',
  'Percentage of pupils achieving grades A*-C in both English and mathematics GCSEs in 2013'),
 ('PTEBACC_E_13',
  'Percentage of pupils entering all English Baccalaureate subject areas in 2013'),
 ('PTFSM6CLA1ABASICS_15_PTQ_EE',
  'Percentage of disadvantaged pupils achieving grades A*-C in both English and mathematics GCSEs in 2015'),
 ('PBPUP', 'Percentage of pupils at the end of key stage 4 who are boys'),
 ('PTANYQ_PTQ_EE', 'Percentage of pupils achieving any qualifications'),
 ('PTEBACHUM_PTQ_EE',
  'Percentage of entered pupils achieving the English Baccalaureate Humanities subject area'),
 ('PTFSMBASICS_14_PTQ',
  'Percentage of disadvantaged pupils achieving grades A*-C in both English and mathematics GCSEs in 2014'),
 ('PTEBACC_NFSM6CLA1A_PTQ_EE',
  'Percentage of non-disadvantaged pupils achieving the English Baccalaureate'),
 ('PTL2BASICS_14_PTQ',
  'Percentage of pupils achieving grades A*-C in both English and mathematics GCSEs in 2014'),
 ('PTEBACHUMAG_PTQ_EE',
  'Percentage of entered pupils achieving the English Baccalaureate Humanities subject area at grades A*-G'),
 ('PTEBACLAN_E_PTQ_EE',
  'Percentage of pupils entering the English Baccalaureate Language subject area'),
 ('PTEBACC_ENMOB_PTQ_EE',
  'Percentage of non-mobile pupils with entries in all English Baccalaureate subject areas'),
 ('PTEBACC_FSM6CLA1A_15_PTQ_EE',
  'Percentage of disadvantaged pupils achieving the English Baccalaureate in 2015'),
 ('PTAC5EM_PTQ_EE',
  'Percentage of pupils achieving 5+ A*-C or equivalents including A*-C in both English and mathematics GCSEs'),
 ('PTEBACMAT_PTQ_EE',
  'Percentage of pupils achieving the English Baccalaureate Maths subject area'),
 ('PTFSMCLA_13',
  'Percentage of pupils at the end of key stage 4 who were disadvantaged in 2013'),
 ('PGEBACC_PTQ_EE', 'Percentage of girls achieving the English Baccalaureate'),
 ('PBEBACC_E_PTQ_EE',
  'Percentage of boys with entries in all English Baccalaureate subject areas'),
 ('PTPRIORHI',
  'Percentage of pupils at the end of key stage 4 with high prior attainment at the end of key stage 2'),
 ('PTEBACC_NFSM6CLA1A_15_PTQ_EE',
  'Percentage of non-disadvantaged pupils achieving the English Baccalaureate in 2015'),
 ('PTEBACC_E_PTQ_EE',
  'Percentage of key stage 4 pupils with entries in all English Baccalaureate subject areas'),
 ('PTEBACC_ENFSM_13',
  'Percentage of non-disadvantaged pupils with entries in all English Baccalaureate subject areas in 2013'),
 ('PTEBACC_13',
  'Percentage of pupils achieving the English Baccalaureate in 2013'),
 ('PGPUP', 'Percentage of pupils at the end key stage 4 who are girls'),
 ('PTEBACC_E_14_PTQ',
  'Percentage of pupils entering all English Baccalaureate subject areas in 2014'),
 ('PTBASICS_LL_LO_PTQ_EE',
  'Percentage of pupils in low prior attainment band achieving grades A*-C in both English and mathematics GCSEs'),
 ('PTtripleSci_E',
  'Percentage of pupils entering biology, chemistry and physics'),
 ('PTPRIORAV',
  'Percentage of pupils at the end of key stage 4 with middle prior attainment at the end of key stage 2'),
 ('PTFSMBASICS_13',
  'Percentage of disadvantaged pupils achieving grades A*-C in both English and mathematics GCSEs in 2013'),
 ('PTEBACCAG_PTQ_EE',
  'Percentage of pupils achieving the English Baccalaureate at grades A*-G'),
 ('PTEBACC_E_15_PTQ_EE',
  'Percentage of pupils entering all English Baccalaureate subject areas in 2015'),
 ('PTEBACC_EFSM_14_PTQ',
  'Percentage of disadvantaged pupils entering all English Baccalaureate subject areas in 2014'),
 ('PTEBACC_ENFSM6CLA1A_PTQ_EE',
  'Percentage of non-disadvantaged pupils with entries in all English Baccalaureate subject areas'),
 ('PTNOTFSM6CLA1A',
  'Percentage of pupils at the end of key stage 4 who are not disadvantaged'),
 ('PTEBACC_ENFSM6CLA1A_15_PTQ_EE',
  'Percentage of non-disadvantaged pupils entering all English Baccalaureate subject areas in 2015'),
 ('PTNOTFSMBASICS_14_PTQ',
  'Percentage of non-disadvantaged pupils achieving grades A*-C in both English and mathematics GCSEs in 2014'),
 ('PTEBACC_EHI_PTQ_EE',
  'Percentage of pupils with high prior attainment with entries in all English Baccalaureate subject areas'),
 ('PTEALGRP1',
  'Percentage of pupils at the end of key stage 4 with English as their first language'),
 ('PTNOTFSM6CLA1ABASICS_15_PTQ_EE',
  'Percentage of non-disadvantaged pupils achieving grades A*-C in both English and mathematics GCSEs in 2015'),
 ('PTEBACLANAG_PTQ_EE',
  'Percentage of entered pupils achieving the English Baccalaureate Language subject area at grade A*-G'),
 ('PTNOTFSMBASICS_13',
  'Percentage of non-disadvantaged pupils achieving grades A*-C in both English and mathematics GCSEs in 2013'),
 ('PTEBACC_EFSM6CLA1A_15_PTQ_EE',
  'Percentage of disadvantaged pupils entering all English Baccalaureate subject areas in 2015'),
 ('PTEBACC_EFSM6CLA1A_PTQ_EE',
  'Percentage of disadvantaged pupils with entries in all English Baccalaureate subject areas'),
 ('PTEBACC_FSM_13',
  'Percentage of disadvantaged pupils achieving the English Baccalaureate in 2013'),
 ('AC5EM14_PTQ',
  'Percentage of pupils achieving 5+ A*-C or equivalents including A*-C in both English and mathematics GCSEs - 2014'),
 ('PTEBACCNMOB_PTQ_EE',
  'Percentage of non-mobile pupils achieving the English Baccalaureate'),
 ('PTEBACCHI_PTQ_EE',
  'Percentage of pupils with high prior attainment achieving the English Baccalaureate'),
 ('PTEBACC_ENFSM_14_PTQ',
  'Percentage of non-disadvantaged pupils entering all English Baccalaureate subject areas in 2014'),
 ('PTFSMCLA_14',
  'Percentage of pupils at the end of key stage 4 who were disadvantaged in 2014'),
 ('PTEBACC_EEAL_PTQ_EE',
  'Percentage of pupils for whom English is an additional language with entries in all English Baccalaureate subject areas'),
 ('PTEBACC_PTQ_EE',
  'Percentage of key stage 4 pupils achieving the English Baccalaureate'),
 ('PTL2BASICS_15_PTQ_EE',
  'Percentage of pupils achieving grades A*-C in both English and mathematics GCSEs in 2015'),
 ('PTEALGRP2',
  'Percentage of pupils at the end of key stage 4 with English as additional language (EAL)'),
 ('PTmultiLan_E', 'Percentage of pupils entering more than one language'),
 ('AC5EM15_PTQ_EE',
  'Percentage of pupils achieving 5+ A*-C or equivalents including A*-C in both English and mathematics GCSEs - 2015'),
 ('PTEBACC_NFSM_14_PTQ',
  'Percentage  non-disadvantaged pupils achieving the English Baccalaureate in 2014'),
 ('PTL2BASICS_LL_PTQ_EE',
  'Percentage of pupils achieving grades A*-C in both English and mathematics GCSEs'),
 ('PSENAPK4',
  'Percentage of pupils at the end of key stage 4 with special educational needs (SEN) without a statement or Education, health and care (EHC) plan'),
 ('PGEBACC_E_PTQ_EE',
  'Percentage of girls with entries in all English Baccalaureate subject areas'),
 ('PTNOTFSM6CLA1ABASICS_LL_PTQ_EE',
  'Percentage of non-disadvantaged pupils achieving grades A*-C in both English and mathematics GCSEs'),
 ('PTEBAC2SCI_PTQ_EE',
  'Percentage of entered pupils achieving the English Baccalaureate Science subject area'),
 ('PTNOTFSM6CLA1A_15',
  'Percentage of pupils at the end of key stage 4 who were not disadvantaged in 2015'),
 ('PTL2BASICS_LL_EAL_PTQ_EE',
  'Percentage of pupils for whom English is an additional language achieving grades A*-C in both English and mathematics GCSEs'),
 ('PTBASICS_LL_HI_PTQ_EE',
  'Percentage pupils in high prior attainment band achieving grades A*-C in both English and mathematics GCSEs'),
 ('PBL2BASICS_LL_PTQ_EE',
  'Percentage of boys achieving grades A*-C in both English and mathematics GCSEs'),
 ('PTNMOB',
  'Percentage of pupils at the end of key stage 4 who are non-mobile'),
 ('PTEBACC_EFSM_13',
  'Percentage of disadvantaged pupils with entries in all English Baccalaureate subject areas in 2013'),
 ('PTEBACC_15_PTQ_EE',
  'Percentage of pupils achieving the English Baccalaureate in 2015'),
 ('PTEBACC_14_PTQ',
  'Percentage of pupils achieving the English Baccalaureate in 2014'),
 ('PTEBAC2SCI_E_PTQ_EE',
  'Percentage of pupils entering the English Baccalaureate Science subject area'),
 ('PTL2BASICS_LL_NMOB_PTQ_EE',
  'Percentage of non-mobile pupils achieving grades A*-C in both English and mathematics GCSEs'),
 ('PTEALGRP3',
  'Percentage of pupils at the end of key stage 4 whose first language is unclassified'),
 ('PTEBACC_EAV_PTQ_EE',
  'Percentage of pupils with middle prior attainment with entries in all English Baccalaureate subject areas'),
 ('PTNOTFSMCLA_14',
  'Percentage of pupils at the end of key stage 4 who were not disadvantaged in 2014'),
 ('PTFSM6CLA1A_15',
  'Percentage of pupils at the end of key stage 4 who were disadvantaged in 2015'),
 ('PTL2BASICS_3YR_PTQ_EE',
  'Three year percentage of pupils achieving A*-C in both English and mathematics GCSEs over 2014, 2015 and 2016'),
 ('PTEBACC_NFSM_13',
  'Percentage of non-disadvantaged pupils achieving the English Baccalaureate in 2013'),
 ('PTEBACLAN_PTQ_EE',
  'Percentage of entered pupils achieving the English Baccalaureate Language subject area'),
 ('PTEBACCEAL_PTQ_EE',
  'Percentage of pupils for whom English is an additional language achieving the English Baccalaureate'),
 ('PTFSM6CLA1A',
  'Percentage of pupils at the end of key stage 4 who are disadvantaged'),
 ('PTEBACC_FSM6CLA1A_PTQ_EE',
  'Percentage of disadvantaged pupils achieving the English Baccalaureate'),
 ('PTPRIORLO',
  'Percentage of pupils at the end of key stage 4 with low prior attainment at the end of key stage 2'),
 ('PTBASICS_LL_AV_PTQ_EE',
  'Percentage pupils in middle prior attainment band achieving grades A*-C in both English and mathematics GCSEs'),
 ('PBEBACC_PTQ_EE', 'Percentage of boys achieving the English Baccalaureate'),
 ('AC5EM16_PTQ_EE',
  'Percentage of pupils achieving 5+ A*-C or equivalents including A*-C in both English and mathematics GCSEs - 2016'),
 ('AC5EM13',
  'Percentage of pupils achieving 5+ A*-C or equivalents including A*-C in both English and mathematics GCSEs - 2013'),
 ('PSENSE4',
  'Percentage of pupils at the end of key stage 4 with special educational needs (SEN) with a statement or Education, health and care (EHC) plan'),
 ('PTEBACHUM_E_PTQ_EE',
  'Percentage of pupils entering the English Baccalaureate Humanities subject area'),
 ('PGL2BASICS_LL_PTQ_EE',
  'Percentage of girls achieving grades A*-C in both English and mathematics GCSEs'),
 ('PTEBACENG_E_PTQ_EE',
  'Percentage of pupils entering the English Baccalaureate English subject area'),
 ('PTEBACC_FSM_14_PTQ',
  'Percentage of disadvantaged pupils achieving the English Baccalaureate in 2014'),
 ('PTEBACENGAG_LL_PTQ_EE',
  'Percentage of pupils achieving the English Baccalaureate English subject area at grade A*-G'),
 ('PTEBAC2SCIAG_PTQ_EE',
  'Percentage of entered pupils achieving the English Baccalaureate Science subject area at grades A*-G'),
 ('PTFSM6CLA1ABASICS_LL_PTQ_EE',
  'Percentage of disadvantaged pupils achieving grades A*-C in both English and mathematics GCSEs'),
 ('PTEBACMATAG_PTQ_EE',
  'Percentage of pupils achieving the English Baccalaureate Maths subject area at grade A*-G'),
 ('PTEBACMAT_E_PTQ_EE',
  'Percentage of pupils entering the English Baccalaureate Maths subject area'),
 ('PTNOTFSMCLA_13',
  'Percentage of pupils at the end of key stage 4 who were not disadvantaged in 2013'),
 ('PTEBACCLO_PTQ_EE',
  'Percentage of pupils with low prior attainment achieving the English Baccalaureate')]

In [74]:
# Save the column headings to a list
percent_cols = [p[0] for p in percent_cols_list]
percent_cols

['PTEBACC_ELO_PTQ_EE',
 'PTEBACENG_LL_PTQ_EE',
 'P8MEACOV',
 'PTEBACCAV_PTQ_EE',
 'PTL2BASICS_13',
 'PTEBACC_E_13',
 'PTFSM6CLA1ABASICS_15_PTQ_EE',
 'PBPUP',
 'PTANYQ_PTQ_EE',
 'PTEBACHUM_PTQ_EE',
 'PTFSMBASICS_14_PTQ',
 'PTEBACC_NFSM6CLA1A_PTQ_EE',
 'PTL2BASICS_14_PTQ',
 'PTEBACHUMAG_PTQ_EE',
 'PTEBACLAN_E_PTQ_EE',
 'PTEBACC_ENMOB_PTQ_EE',
 'PTEBACC_FSM6CLA1A_15_PTQ_EE',
 'PTAC5EM_PTQ_EE',
 'PTEBACMAT_PTQ_EE',
 'PTFSMCLA_13',
 'PGEBACC_PTQ_EE',
 'PBEBACC_E_PTQ_EE',
 'PTPRIORHI',
 'PTEBACC_NFSM6CLA1A_15_PTQ_EE',
 'PTEBACC_E_PTQ_EE',
 'PTEBACC_ENFSM_13',
 'PTEBACC_13',
 'PGPUP',
 'PTEBACC_E_14_PTQ',
 'PTBASICS_LL_LO_PTQ_EE',
 'PTtripleSci_E',
 'PTPRIORAV',
 'PTFSMBASICS_13',
 'PTEBACCAG_PTQ_EE',
 'PTEBACC_E_15_PTQ_EE',
 'PTEBACC_EFSM_14_PTQ',
 'PTEBACC_ENFSM6CLA1A_PTQ_EE',
 'PTNOTFSM6CLA1A',
 'PTEBACC_ENFSM6CLA1A_15_PTQ_EE',
 'PTNOTFSMBASICS_14_PTQ',
 'PTEBACC_EHI_PTQ_EE',
 'PTEALGRP1',
 'PTNOTFSM6CLA1ABASICS_15_PTQ_EE',
 'PTEBACLANAG_PTQ_EE',
 'PTNOTFSMBASICS_13',
 'PTEBACC_EFSM6CLA1A_15_PTQ_EE',
 'PTEBACC_EFSM6CLA1A_PTQ_EE',
 'PTEBACC_FSM_13',
 'AC5EM14_PTQ',
 'PTEBACCNMOB_PTQ_EE',
 'PTEBACCHI_PTQ_EE',
 'PTEBACC_ENFSM_14_PTQ',
 'PTFSMCLA_14',
 'PTEBACC_EEAL_PTQ_EE',
 'PTEBACC_PTQ_EE',
 'PTL2BASICS_15_PTQ_EE',
 'PTEALGRP2',
 'PTmultiLan_E',
 'AC5EM15_PTQ_EE',
 'PTEBACC_NFSM_14_PTQ',
 'PTL2BASICS_LL_PTQ_EE',
 'PSENAPK4',
 'PGEBACC_E_PTQ_EE',
 'PTNOTFSM6CLA1ABASICS_LL_PTQ_EE',
 'PTEBAC2SCI_PTQ_EE',
 'PTNOTFSM6CLA1A_15',
 'PTL2BASICS_LL_EAL_PTQ_EE',
 'PTBASICS_LL_HI_PTQ_EE',
 'PBL2BASICS_LL_PTQ_EE',
 'PTNMOB',
 'PTEBACC_EFSM_13',
 'PTEBACC_15_PTQ_EE',
 'PTEBACC_14_PTQ',
 'PTEBAC2SCI_E_PTQ_EE',
 'PTL2BASICS_LL_NMOB_PTQ_EE',
 'PTEALGRP3',
 'PTEBACC_EAV_PTQ_EE',
 'PTNOTFSMCLA_14',
 'PTFSM6CLA1A_15',
 'PTL2BASICS_3YR_PTQ_EE',
 'PTEBACC_NFSM_13',
 'PTEBACLAN_PTQ_EE',
 'PTEBACCEAL_PTQ_EE',
 'PTFSM6CLA1A',
 'PTEBACC_FSM6CLA1A_PTQ_EE',
 'PTPRIORLO',
 'PTBASICS_LL_AV_PTQ_EE',
 'PBEBACC_PTQ_EE',
 'AC5EM16_PTQ_EE',
 'AC5EM13',
 'PSENSE4',
 'PTEBACHUM_E_PTQ_EE',
 'PGL2BASICS_LL_PTQ_EE',
 'PTEBACENG_E_PTQ_EE',
 'PTEBACC_FSM_14_PTQ',
 'PTEBACENGAG_LL_PTQ_EE',
 'PTEBAC2SCIAG_PTQ_EE',
 'PTFSM6CLA1ABASICS_LL_PTQ_EE',
 'PTEBACMATAG_PTQ_EE',
 'PTEBACMAT_E_PTQ_EE',
 'PTNOTFSMCLA_13',
 'PTEBACCLO_PTQ_EE']

In [75]:
# int columns
int_col_list = [(l, ks4_expanded_name[l])
                for l in ks4_expanded_name 
                if 'number' in ks4_expanded_name[l].lower()]
int_col_list

[('TEBACLAN_E_PTQ_EE',
  'Number of pupils entering the English Baccalaureate Language subject area'),
 ('P8PUP_LO',
  'Number of pupils with low prior attainment included in Progress 8 measure'),
 ('TEALGRP3',
  'Number of pupils at the end of key stage 4 whose first language is unclassified'),
 ('P8PUP_EAL',
  'Number of pupils for whom English is an additional language included in Progress 8 measure'),
 ('TAVENT_GAV_PTQ_EE',
  'Average number of GCSE entries per pupil with middle prior attainment'),
 ('TFSMCLA_14',
  'Number of disadvantaged pupils at the end of key stage 4 in 2014'),
 ('BPUP', 'Number of boys at the end of key stage 4'),
 ('TAVENT_E_3NG_LO_PTQ_EE',
  'Average number of GCSE and equivalents entries per pupil with low prior attainment'),
 ('TEBACMAT_PTQ_EE',
  'Number of pupils achieving the English Baccalaureate Maths subject area'),
 ('TAVENT_ENFSM_14_PTQ',
  'Average number of GCSE and equivalents entries per non-disadvantaged pupil in 2014'),
 ('TAVENT_E_3NG_HI_PTQ_EE',
  'Average number of GCSE and equivalents entries per pupil with high prior attainment'),
 ('TAVENT_ENFSM_13',
  'Average number of GCSE and equivalents entries per non-disadvantaged pupil in 2013'),
 ('TAVENT_GHI_PTQ_EE',
  'Average number of GCSE entries per pupil with high prior attainment'),
 ('TEALGRP1',
  'Number of pupils at the end of key stage 4 with English as their first language'),
 ('TAVENT_GNFSM_14_PTQ',
  'Average number of GCSE entries per non-disadvantaged pupil in 2014'),
 ('TBASICS_LL_LO_PTQ_EE',
  'Number of pupils in low prior attainment band achieving grades A*-C in both English and mathematics GCSEs'),
 ('TEBACC_EAV_PTQ_EE',
  'Number of pupils with middle prior attainment with entries in all English Baccalaureate subject areas'),
 ('P8PUP_FSM6CLA1A', 'Number of disadvantaged pupils in Progress 8 measure'),
 ('TAVENT_E_3NG_AV_PTQ_EE',
  'Average number of GCSE and equivalents entries per pupil with middle prior attainment'),
 ('TAVENT_GLO_PTQ_EE',
  'Average number of GCSE entries per pupil with low prior attainment'),
 ('P8PUP', 'Number of pupils included in Progress 8 measure'),
 ('TEALGRP2',
  'Number of pupils at the end of key stage 4 with English as additional language (EAL)'),
 ('TNOTFSMCLA_14',
  'Number of non-disadvantaged pupils at the end of key stage 4 in 2014'),
 ('TEBAC2SCI_PTQ_EE',
  'Number of pupils achieving the English Baccalaureate Science subject area'),
 ('TBASICS_LL_AV_PTQ_EE',
  'Number of pupils in middle prior attainment band achieving grades A*-C in both English and mathematics GCSEs'),
 ('TEBAC2SCI_E_PTQ_EE',
  'Number of pupils entering the English Baccalaureate Science subject area'),
 ('TPUP', 'Number of pupils at the end of key stage 4'),
 ('SENAPK4',
  'Number of pupils at the end of key stage 4 with special educational needs (SEN) without a statement or Education, health and care (EHC) plan'),
 ('TAVENT_G_PTQ_EE', 'Average number of GCSE entries per pupil'),
 ('TEBACHUMAG_PTQ_EE',
  'Number of pupils achieving the English Baccalaureate Humanities subject area at grade A*-G'),
 ('TFSM6CLA1A', 'Number of disadvantaged pupils at the end of key stage 4'),
 ('TPRIORHI',
  'Number of pupils at the end of key stage 4 with high prior attainment at the end of key stage 2'),
 ('TEBACCAG_PTQ_EE',
  'Number of pupils achieving the English Baccalaureate at grades A*-G'),
 ('ESTAB', 'Establishment number'),
 ('TEBACC_E_PTQ_EE',
  'Number of key stage 4 pupils with entries in all English Baccalaureate subject areas'),
 ('TOTPUPS', 'Number of pupils on roll (all ages)'),
 ('TAVENT_GNFSM_13',
  'Average number of GCSE entries per non-disadvantaged pupil in 2013'),
 ('TAVENT_EFSM_13',
  'Average number of GCSE and equivalents entries per disadvantaged pupil in 2013'),
 ('P8PUP_NFSM6CLA1A',
  'Number of non-disadvantaged pupils in Progress 8 measure'),
 ('TELNUM', 'School telephone number'),
 ('TPRIORLO',
  'Number of pupils at the end of key stage 4 with low prior attainment at the end of key stage 2'),
 ('TAVENT_E_3NG_PTQ_EE',
  'Average number of GCSE and equivalents entries per pupil'),
 ('TNOTFSM6CLA1A_15',
  'Number of non-disadvantaged pupils at the end of key stage 4 in 2015'),
 ('TEBACENGAG_LL_PTQ_EE',
  'Number of pupils achieving the English Baccalaureate English subject area at grade A*-G'),
 ('TEBACMAT_E_PTQ_EE',
  'Number of pupils entering the English Baccalaureate Maths subject area'),
 ('TAVENT_GFSM6CLA1A_PTQ_EE',
  'Average number of GCSE entries per disadvantaged pupil'),
 ('TFSM6CLA1A_15',
  'Number of disadvantaged pupils at the end of key stage 4 in 2015'),
 ('TPRIORAV',
  'Number of pupils at the end of key stage 4 with middle prior attainment at the end of key stage 2'),
 ('TAVENT_E_3NG_FSM6CLA1A_PTQ_EE',
  'Average number of GCSE and equivalents entries per disadvantaged pupil'),
 ('TBASICS_LL_HI_PTQ_EE',
  'Number of pupils in high prior attainment band achieving grades A*-C in both English and mathematics GCSEs'),
 ('URN', 'School Unique Reference Number'),
 ('TAVENT_GNFSM6CLA1A_15_PTQ_EE',
  'Average number of GCSE entries per non-disadvantaged pupil in 2015'),
 ('P8PUP_GIRLS', 'Number of girls included in Progress 8 measure'),
 ('TEBACC_EHI_PTQ_EE',
  'Number of pupils with high prior attainment with entries in all English Baccalaureate subject areas'),
 ('P8PUP_NMOB', 'Number of non-mobile pupils included in Progress 8 measure'),
 ('TEBACHUM_E_PTQ_EE',
  'Number of pupils entering the English Baccalaureate Humanities subject area'),
 ('P8PUP_BOYS', 'Number of boys included in Progress 8 measure'),
 ('TEBACENG_E_PTQ_EE',
  'Number of pupils entering the English Baccalaureate English subject area'),
 ('TEBACC_ELO_PTQ_EE',
  'Number of pupils with low prior attainment with entries in all English Baccalaureate subject areas'),
 ('TNMOB', 'Number of pupils at the end of key stage 4 who are non-mobile'),
 ('TAVENT_EFSM6CLA1A_15_PTQ_EE',
  'Average number of GCSE and equivalents entries per disadvantaged pupil in 2015'),
 ('P8PUP_HI',
  'Number of pupils with high prior attainment included in Progress 8 measure'),
 ('TEBACLAN_PTQ_EE',
  'Number of pupils achieving the English Baccalaureate Language subject area'),
 ('TEBACENG_LL_PTQ_EE',
  'Number of pupils achieving EBacc English subject area'),
 ('TEBACLANAG_PTQ_EE',
  'Number of pupils achieving the English Baccalaureate Language subject area at grade A*-G'),
 ('TAVENT_GFSM_13',
  'Average number of GCSE entries per disadvantaged pupil in 2013'),
 ('TAVENT_ENFSM6CLA1A_15_PTQ_EE',
  'Average number of GCSE and equivalents entries per non-disadvantaged pupil in 2015'),
 ('TAVENT_GNFSM6CLA1A_PTQ_EE',
  'Average number of GCSE entries per non-disadvantaged pupil'),
 ('TEBACHUM_PTQ_EE',
  'Number of pupils achieving the English Baccalaureate Humanities subject area'),
 ('TEBACMATAG_PTQ_EE',
  'Number of pupils achieving the English Baccalaureate Maths subject area at grade A*-G'),
 ('TEBAC2SCIAG_PTQ_EE',
  'Number of pupils achieving the English Baccalaureate Science subject area at grades A*-G'),
 ('TNOTFSM6CLA1A',
  'Number of non-disadvantaged pupils at the end of key stage 4'),
 ('TAVENT_GFSM6CLA1A_15_PTQ_EE',
  'Average number of GCSE entries per disadvantaged pupil in 2015'),
 ('GPUP', 'Number of girls at the end of key stage 4'),
 ('TNOTFSMCLA_13',
  'Number of non-disadvantaged pupils at the end of key stage 4 in 2013'),
 ('TAVENT_E_3NG_NFSM6CLA1A_PTQ_EE',
  'Average number of GCSE and equivalents entries per non-disadvantaged pupil'),
 ('P8PUP_AV',
  'Number of pupils with middle prior attainment included in Progress 8 measure'),
 ('TAVENT_GFSM_14_PTQ',
  'Average number of GCSE entries per disadvantaged pupil in 2014'),
 ('TAVENT_EFSM_14_PTQ',
  'Average number of GCSE and equivalents entries per disadvantaged pupil in 2014'),
 ('SENSE4',
  'Number of pupils at the end of key stage 4 with special educational needs (SEN) with a statement or Education, health and care (EHC) plan'),
 ('P8PUP_15',
  'Number of pupils included in Progress 8 measure - 2015 opt-in schools only'),
 ('TFSMCLA_13',
  'Number of disadvantaged pupils at the end of key stage 4 in 2013')]

In [76]:
# again, save out just the column labels
# Save just the column headings
int_cols = [i[0] for i in int_col_list]
int_cols

['TEBACLAN_E_PTQ_EE',
 'P8PUP_LO',
 'TEALGRP3',
 'P8PUP_EAL',
 'TAVENT_GAV_PTQ_EE',
 'TFSMCLA_14',
 'BPUP',
 'TAVENT_E_3NG_LO_PTQ_EE',
 'TEBACMAT_PTQ_EE',
 'TAVENT_ENFSM_14_PTQ',
 'TAVENT_E_3NG_HI_PTQ_EE',
 'TAVENT_ENFSM_13',
 'TAVENT_GHI_PTQ_EE',
 'TEALGRP1',
 'TAVENT_GNFSM_14_PTQ',
 'TBASICS_LL_LO_PTQ_EE',
 'TEBACC_EAV_PTQ_EE',
 'P8PUP_FSM6CLA1A',
 'TAVENT_E_3NG_AV_PTQ_EE',
 'TAVENT_GLO_PTQ_EE',
 'P8PUP',
 'TEALGRP2',
 'TNOTFSMCLA_14',
 'TEBAC2SCI_PTQ_EE',
 'TBASICS_LL_AV_PTQ_EE',
 'TEBAC2SCI_E_PTQ_EE',
 'TPUP',
 'SENAPK4',
 'TAVENT_G_PTQ_EE',
 'TEBACHUMAG_PTQ_EE',
 'TFSM6CLA1A',
 'TPRIORHI',
 'TEBACCAG_PTQ_EE',
 'ESTAB',
 'TEBACC_E_PTQ_EE',
 'TOTPUPS',
 'TAVENT_GNFSM_13',
 'TAVENT_EFSM_13',
 'P8PUP_NFSM6CLA1A',
 'TELNUM',
 'TPRIORLO',
 'TAVENT_E_3NG_PTQ_EE',
 'TNOTFSM6CLA1A_15',
 'TEBACENGAG_LL_PTQ_EE',
 'TEBACMAT_E_PTQ_EE',
 'TAVENT_GFSM6CLA1A_PTQ_EE',
 'TFSM6CLA1A_15',
 'TPRIORAV',
 'TAVENT_E_3NG_FSM6CLA1A_PTQ_EE',
 'TBASICS_LL_HI_PTQ_EE',
 'URN',
 'TAVENT_GNFSM6CLA1A_15_PTQ_EE',
 'P8PUP_GIRLS',
 'TEBACC_EHI_PTQ_EE',
 'P8PUP_NMOB',
 'TEBACHUM_E_PTQ_EE',
 'P8PUP_BOYS',
 'TEBACENG_E_PTQ_EE',
 'TEBACC_ELO_PTQ_EE',
 'TNMOB',
 'TAVENT_EFSM6CLA1A_15_PTQ_EE',
 'P8PUP_HI',
 'TEBACLAN_PTQ_EE',
 'TEBACENG_LL_PTQ_EE',
 'TEBACLANAG_PTQ_EE',
 'TAVENT_GFSM_13',
 'TAVENT_ENFSM6CLA1A_15_PTQ_EE',
 'TAVENT_GNFSM6CLA1A_PTQ_EE',
 'TEBACHUM_PTQ_EE',
 'TEBACMATAG_PTQ_EE',
 'TEBAC2SCIAG_PTQ_EE',
 'TNOTFSM6CLA1A',
 'TAVENT_GFSM6CLA1A_15_PTQ_EE',
 'GPUP',
 'TNOTFSMCLA_13',
 'TAVENT_E_3NG_NFSM6CLA1A_PTQ_EE',
 'P8PUP_AV',
 'TAVENT_GFSM_14_PTQ',
 'TAVENT_EFSM_14_PTQ',
 'SENSE4',
 'P8PUP_15',
 'TFSMCLA_13']

In [77]:
# remind myself of the missing type codes
missing_types

{'NEW': 'New institution',
 nan: 'Not applicable: figures are either not available for the year in question, or the data field is not applicable to this school or college',
 'NE': 'No entries',
 'SUPP': "Indicates that a school or college's figures have been suppressed because there are 5 or fewer pupils in the cohort",
 'LOWCOV': 'Low coverage: indicates that a schoolâs Progress 8 or value added measures have been suppressed because coverage is less than 50% of the cohort',
 'NP': 'Not published - for example we do not publish Progress 8 data for independent schools and independent special schools, or breakdowns by disadvantaged and non-disadvantaged pupils for independent schools, independent special schools and non-maintained special schools.'}

Create the percent converter as in the Q2b-pd import method.  Giving a negative value of -1 for missing data and a negative value of -2 for Not Published data. This will make it easier to filter the query results later.  The reason I have given NP a -2 is that I want to separate these data points as I may want to look at them in more detail.

In [78]:
def ks4_p2f(x):
    if x.strip('%').isnumeric():
        return float(x.strip('%'))/100
    elif x in ['SUPP', 'NEW', 'LOWCOV', 'NA', 'NE' ' ']:
        return -1
    elif x == 'NP':
        return -2
    else:
        return x

In [79]:
percent_converters = {c: ks4_p2f for c in percent_cols}

Read in the file to a dataframe

In [80]:
ks4_df = pd.read_csv('data/2015-2016/england_ks4final.csv',
                     na_values=['SUPP', 'NEW', 'LOWCOV', 'NA', ''],
                     converters=percent_converters)

/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (2,24) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Still showing the error for the data types.  I will continue walking through the cleaning steps from tma02-q2.  For our questions will focus on only mainstream schools we can drop those that are not of `RECTYPE` == 1

In [81]:
ks4_df = ks4_df[ks4_df['RECTYPE'] == 1]

Convert everything to numbers, if possible.

In [82]:
ks4_df = ks4_df.apply(pd.to_numeric, errors='ignore')

Merge the LEA data into the school data.

In [83]:
ks4_df = pd.merge(ks4_df, leas_df, on=['LEA'])
ks4_df.head().T

,0,1,2,3,4
RECTYPE,1,1,1,1,1
ALPHAIND,11828,11830,368,9318,10054
LEA,201,201,202,202,202
ESTAB,6007,6005,4285,4611,6000
URN,100003,100001,100053,100054,137333
SCHNAME,City of London School,City of London School for Girls,Acland Burghley School,The Camden School for Girls,CATS College London
SCHNAME_AC,,,,,
ADDRESS1,Queen Victoria Street,St Giles' Terrace,Burghley Road,Sandall Road,43-45 Bloomsbury Square & 2 Southampton Place
ADDRESS2,,Barbican,,,
ADDRESS3,,,,,
TOWN,London,London,London,London,London
PCODE,EC4V 3AL,EC2Y 8BB,NW5 1UJ,NW5 2DB,WC1A 2RA
TELNUM,0207 4890291,0207 8475500,0207 4858515,0207 4853414,0207 8411580
CONTFLAG,0,0,0,0,0
ICLOSE,0,0,0,0,0
NFTYPE,IND,IND,CY,VA,IND
RELDENOM,None,None,Does not apply,None,None
ADMPOL,,,COMP,COMP,
EGENDER,BOYS,GIRLS,MIXED,GIRLS,MIXED
FEEDER,0,0,1,0,0
TABKS2,0,0,0,0,0
TAB1618,1,1,1,1,1
AGERANGE,10-18,7-18,11-18,11-18,15-24
CONFEXAM,,,,,
TOTPUPS,918,730,974,1006,255
NUMBOYS,918,NaN,628,NaN,128
NUMGIRLS,NaN,730,346,849,127
TPUP,139,90,172,111,11
BPUP,139,NaN,109,NaN,9
PBPUP,1,-1,0.63,-1,0.82
...,...,...,...,...,...
PTFSM6CLA1A_15,-1,-1,0.56,0.41,-1
TNOTFSM6CLA1A_15,NaN,NaN,75,65,NaN
PTNOTFSM6CLA1A_15,-1,-1,0.44,0.59,-1
TAVENT_E_3NG_PTQ_EE,5.6,4.2,9.1,9.3,0.7
TAVENT_E_3NG_LO_PTQ_EE,NP,NP,6.9,7.1,NP
TAVENT_E_3NG_AV_PTQ_EE,NP,NP,9.1,8.6,NP
TAVENT_E_3NG_HI_PTQ_EE,NP,NP,9.9,10.3,NP
TAVENT_E_3NG_FSM6CLA1A_PTQ_EE,NP,NP,8.7,8.2,NP
TAVENT_E_3NG_NFSM6CLA1A_PTQ_EE,NP,NP,9.6,10,NP
TAVENT_EFSM_13,NaN,NaN,8.7,9.3,NaN
TAVENT_ENFSM_13,NaN,NaN,9.9,9.8,NaN
TAVENT_EFSM_14_PTQ,NaN,NaN,9.2,7.5,NaN
TAVENT_ENFSM_14_PTQ,NaN,NaN,10.3,8.7,NaN
TAVENT_EFSM6CLA1A_15_PTQ_EE,NaN,NaN,9.7,7.9,NaN
TAVENT_ENFSM6CLA1A_15_PTQ_EE,NaN,NaN,11.5,9,NaN
TAVENT_G_PTQ_EE,5.3,3.9,8.8,9,0.6
TAVENT_GLO_PTQ_EE,NP,NP,6.1,6.6,NP
TAVENT_GAV_PTQ_EE,NP,NP,8.9,8.2,NP
TAVENT_GHI_PTQ_EE,NP,NP,9.8,10.2,NP
TAVENT_GFSM6CLA1A_PTQ_EE,NP,NP,8.4,7.8,NP
TAVENT_GNFSM6CLA1A_PTQ_EE,NP,NP,9.5,9.8,NP
TAVENT_GFSM_13,NaN,NaN,8.1,8.6,NaN
TAVENT_GNFSM_13,NaN,NaN,9.8,9.3,NaN
TAVENT_GFSM_14_PTQ,NaN,NaN,9,7.3,NaN
TAVENT_GNFSM_14_PTQ,NaN,NaN,10.2,8.6,NaN
TAVENT_GFSM6CLA1A_15_PTQ_EE,NaN,NaN,8.4,7.5,NaN
TAVENT_GNFSM6CLA1A_15_PTQ_EE,NaN,NaN,10.6,8.9,NaN
LA Name,City of London,City of London,Camden,Camden,Camden
REGION,32,32,31,31,31
REGION NAME,London East,London East,London Central,London Central,London Central

That is looking better I'll now import these into mongodb

In [84]:
# create a collection in the database
ks4 = db.ks4

In [85]:
# insert the cleaned dataframe to the database
ks4.insert_many(ks4_df.to_dict('records'))

In [86]:
# check that the correct number of documents were included
len(ks4_df), ks4.find().count()

(4196, 4196)

In [87]:
ks4.find_one()

{'AC5EM13': 0.0,
 'AC5EM14_PTQ': 0.0,
 'AC5EM15_PTQ_EE': 0.0,
 'AC5EM16_PTQ_EE': 0.0,
 'ADDRESS1': 'Queen Victoria Street',
 'ADDRESS2': ' ',
 'ADDRESS3': ' ',
 'ADMPOL': ' ',
 'AGERANGE': '10-18',
 'ALPHAIND': 11828,
 'ATT8SCR': '42.1',
 'ATT8SCREBAC': '22.2',
 'ATT8SCREBAC_FSM6CLA1A': 'NP',
 'ATT8SCREBAC_NFSM6CLA1A': 'NP',
 'ATT8SCRENG': '7.3',
 'ATT8SCRENG_FSM6CLA1A': 'NP',
 'ATT8SCRENG_NFSM6CLA1A': 'NP',
 'ATT8SCRMAT': '0',
 'ATT8SCRMAT_FSM6CLA1A': 'NP',
 'ATT8SCRMAT_NFSM6CLA1A': 'NP',
 'ATT8SCROPEN': '12.6',
 'ATT8SCROPENG': '10.4',
 'ATT8SCROPENG_FSM6CLA1A': 'NP',
 'ATT8SCROPENG_NFSM6CLA1A': 'NP',
 'ATT8SCROPENNG': '2.2',
 'ATT8SCROPENNG_FSM6CLA1A': 'NP',
 'ATT8SCROPENNG_NFSM6CLA1A': 'NP',
 'ATT8SCROPEN_FSM6CLA1A': 'NP',
 'ATT8SCROPEN_NFSM6CLA1A': 'NP',
 'ATT8SCR_15': nan,
 'ATT8SCR_AV': 'NP',
 'ATT8SCR_BOYS': '42.1',
 'ATT8SCR_EAL': 'NP',
 'ATT8SCR_FSM6CLA1A': 'NP',
 'ATT8SCR_GIRLS': nan,
 'ATT8SCR_HI': 'NP',
 'ATT8SCR_LO': 'NP',
 'ATT8SCR_NFSM6CLA1A': 'NP',
 'ATT8SCR_NMOB': 'NP',
 'BPUP': '139',
 'CONFEXAM': ' ',
 'CONTFLAG': 0,
 'DIFFN_ATT8': 'NP',
 'DIFFN_P8MEA': 'NP',
 'EGENDER': 'BOYS',
 'ESTAB': 6007,
 'FEEDER': 0,
 'GPUP': nan,
 'HUMVACOV_PTQ_EE': 'NP',
 'HUMVALOW_AV_PTQ_EE': 'NP',
 'HUMVALOW_FSM6CLA1A_PTQ_EE': 'NP',
 'HUMVALOW_HI_PTQ_EE': 'NP',
 'HUMVALOW_LO_PTQ_EE': 'NP',
 'HUMVALOW_NFSM6CLA1A_PTQ_EE': 'NP',
 'HUMVALOW_PTQ_EE': 'NP',
 'HUMVAMEA_AV_PTQ_EE': 'NP',
 'HUMVAMEA_FSM6CLA1A_PTQ_EE': 'NP',
 'HUMVAMEA_HI_PTQ_EE': 'NP',
 'HUMVAMEA_LO_PTQ_EE': 'NP',
 'HUMVAMEA_NFSM6CLA1A_PTQ_EE': 'NP',
 'HUMVAMEA_PTQ_EE': 'NP',
 'HUMVAUPP_AV_PTQ_EE': 'NP',
 'HUMVAUPP_FSM6CLA1A_PTQ_EE': 'NP',
 'HUMVAUPP_HI_PTQ_EE': 'NP',
 'HUMVAUPP_LO_PTQ_EE': 'NP',
 'HUMVAUPP_NFSM6CLA1A_PTQ_EE': 'NP',
 'HUMVAUPP_PTQ_EE': 'NP',
 'ICLOSE': 0,
 'KS2APS': 'NP',
 'LA Name': 'City of London',
 'LANVACOV_PTQ_EE': 'NP',
 'LANVALOW_AV_PTQ_EE': 'NP',
 'LANVALOW_FSM6CLA1A_PTQ_EE': 'NP',
 'LANVALOW_HI_PTQ_EE': 'NP',
 'LANVALOW_LO_PTQ_EE': 'NP',
 'LANVALOW_NFSM6CLA1A_PTQ_EE': 'NP',
 'LANVALOW_PTQ_EE': 'NP',
 'LANVAMEA_AV_PTQ_EE': 'NP',
 'LANVAMEA_FSM6CLA1A_PTQ_EE': 'NP',
 'LANVAMEA_HI_PTQ_EE': 'NP',
 'LANVAMEA_LO_PTQ_EE': 'NP',
 'LANVAMEA_NFSM6CLA1A_PTQ_EE': 'NP',
 'LANVAMEA_PTQ_EE': 'NP',
 'LANVAUPP_AV_PTQ_EE': 'NP',
 'LANVAUPP_FSM6CLA1A_PTQ_EE': 'NP',
 'LANVAUPP_HI_PTQ_EE': 'NP',
 'LANVAUPP_LO_PTQ_EE': 'NP',
 'LANVAUPP_NFSM6CLA1A_PTQ_EE': 'NP',
 'LANVAUPP_PTQ_EE': 'NP',
 'LEA': 201,
 'NFTYPE': 'IND',
 'NUMBOYS': '918',
 'NUMGIRLS': nan,
 'P8CILOW': 'NP',
 'P8CILOW_15': nan,
 'P8CILOW_AV': 'NP',
 'P8CILOW_BOYS': 'NP',
 'P8CILOW_EAL': 'NP',
 'P8CILOW_FSM6CLA1A': 'NP',
 'P8CILOW_GIRLS': nan,
 'P8CILOW_HI': 'NP',
 'P8CILOW_LO': 'NP',
 'P8CILOW_NFSM6CLA1A': 'NP',
 'P8CILOW_NMOB': 'NP',
 'P8CIUPP': 'NP',
 'P8CIUPP_15': nan,
 'P8CIUPP_AV': 'NP',
 'P8CIUPP_BOYS': 'NP',
 'P8CIUPP_EAL': 'NP',
 'P8CIUPP_FSM6CLA1A': 'NP',
 'P8CIUPP_GIRLS': nan,
 'P8CIUPP_HI': 'NP',
 'P8CIUPP_LO': 'NP',
 'P8CIUPP_NFSM6CLA1A': 'NP',
 'P8CIUPP_NMOB': 'NP',
 'P8MEA': 'NP',
 'P8MEACOV': -2,
 'P8MEAEBAC': 'NP',
 'P8MEAEBAC_CILOW': 'NP',
 'P8MEAEBAC_CILOW_FSM6CLA1A': 'NP',
 'P8MEAEBAC_CILOW_NFSM6CLA1A': 'NP',
 'P8MEAEBAC_CIUPP': 'NP',
 'P8MEAEBAC_CIUPP_FSM6CLA1A': 'NP',
 'P8MEAEBAC_CIUPP_NFSM6CLA1A': 'NP',
 'P8MEAEBAC_FSM6CLA1A': 'NP',
 'P8MEAEBAC_NFSM6CLA1A': 'NP',
 'P8MEAENG': 'NP',
 'P8MEAENG_CILOW': 'NP',
 'P8MEAENG_CILOW_FSM6CLA1A': 'NP',
 'P8MEAENG_CILOW_NFSM6CLA1A': 'NP',
 'P8MEAENG_CIUPP': 'NP',
 'P8MEAENG_CIUPP_FSM6CLA1A': 'NP',
 'P8MEAENG_CIUPP_NFSM6CLA1A': 'NP',
 'P8MEAENG_FSM6CLA1A': 'NP',
 'P8MEAENG_NFSM6CLA1A': 'NP',
 'P8MEAMAT': 'NP',
 'P8MEAMAT_CILOW': 'NP',
 'P8MEAMAT_CILOW_FSM6CLA1A': 'NP',
 'P8MEAMAT_CILOW_NFSM6CLA1A': 'NP',
 'P8MEAMAT_CIUPP': 'NP',
 'P8MEAMAT_CIUPP_FSM6CLA1A': 'NP',
 'P8MEAMAT_CIUPP_NFSM6CLA1A': 'NP',
 'P8MEAMAT_FSM6CLA1A': 'NP',
 'P8MEAMAT_NFSM6CLA1A': 'NP',
 'P8MEAOPEN': 'NP',
 'P8MEAOPEN_CILOW': 'NP',
 'P8MEAOPEN_CILOW_FSM6CLA1A': 'NP',
 'P8MEAOPEN_CILOW_NFSM6CLA1A': 'NP',
 'P8MEAOPEN_CIUPP': 'NP',
 'P8MEAOPEN_CIUPP_FSM6CLA1A': 'NP',
 'P8MEAOPEN_CIUPP_NFSM6CLA1A': 'NP',
 'P8MEAOPEN_FSM6CLA1A': 'NP',
 'P8MEAOPEN_NFSM6CLA1A': 'NP',
 'P8MEA_15': nan,
 'P8MEA_AV': 'NP',
 'P8MEA_BOYS': 'NP',
 'P8MEA_EAL': 'NP',
 'P8MEA_FSM6CLA1A': 'NP',
 'P8MEA_GIRLS': nan,
 'P8MEA_HI': 'NP',
 'P8MEA_LO': 'NP',
 'P8MEA_NFSM6CLA1A': 'NP',
 'P8MEA_NMOB': 'NP',
 'P8PUP': 'NP',
 'P8PUP_15': nan,
 'P8PUP_AV': 'NP',
 'P8PUP_BOYS': 'NP',
 'P8PUP_EAL': 'NP',
 'P8PUP_FSM6CLA1A': 'NP',
 'P8PUP_GIRLS': nan,
 'P8PUP_HI': 'NP',
 'P8PUP_LO': 'NP',
 'P8PUP_NFSM6CLA1A': 'NP',
 'P8PUP_NMOB': 'NP',
 'PBEBACC_E_PTQ_EE': 0.0,
 'PBEBACC_PTQ_EE': 0.0,
 'PBL2BASICS_LL_PTQ_EE': 0.0,
 'PBPUP': 1.0,
 'PCODE': 'EC4V 3AL',
 'PGEBACC_E_PTQ_EE': 'NE',
 'PGEBACC_PTQ_EE': 'NE',
 'PGL2BASICS_LL_PTQ_EE': 'NE',
 'PGPUP': -1,
 'PSENAPK4': -1,
 'PSENSE4': -1,
 'PTAC5EM_PTQ_EE': 0.0,
 'PTANYQ_PTQ_EE': 1.0,
 'PTBASICS_LL_AV_PTQ_EE': -2,
 'PTBASICS_LL_HI_PTQ_EE': -2,
 'PTBASICS_LL_LO_PTQ_EE': -2,
 'PTEALGRP1': -2,
 'PTEALGRP2': -2,
 'PTEALGRP3': -2,
 'PTEBAC2SCIAG_PTQ_EE': 'NE',
 'PTEBAC2SCI_E_PTQ_EE': 0.0,
 'PTEBAC2SCI_PTQ_EE': 'NE',
 'PTEBACCAG_PTQ_EE': 0.0,
 'PTEBACCAV_PTQ_EE': -2,
 'PTEBACCEAL_PTQ_EE': -2,
 'PTEBACCHI_PTQ_EE': -2,
 'PTEBACCLO_PTQ_EE': -2,
 'PTEBACCNMOB_PTQ_EE': -2,
 'PTEBACC_13': 0.0,
 'PTEBACC_14_PTQ': 0.0,
 'PTEBACC_15_PTQ_EE': 0.0,
 'PTEBACC_EAV_PTQ_EE': -2,
 'PTEBACC_EEAL_PTQ_EE': -2,
 'PTEBACC_EFSM6CLA1A_15_PTQ_EE': -1,
 'PTEBACC_EFSM6CLA1A_PTQ_EE': -2,
 'PTEBACC_EFSM_13': -1,
 'PTEBACC_EFSM_14_PTQ': -1,
 'PTEBACC_EHI_PTQ_EE': -2,
 'PTEBACC_ELO_PTQ_EE': -2,
 'PTEBACC_ENFSM6CLA1A_15_PTQ_EE': -1,
 'PTEBACC_ENFSM6CLA1A_PTQ_EE': -2,
 'PTEBACC_ENFSM_13': -1,
 'PTEBACC_ENFSM_14_PTQ': -1,
 'PTEBACC_ENMOB_PTQ_EE': -2,
 'PTEBACC_E_13': 0.0,
 'PTEBACC_E_14_PTQ': 0.0,
 'PTEBACC_E_15_PTQ_EE': 0.0,
 'PTEBACC_E_PTQ_EE': 0.0,
 'PTEBACC_FSM6CLA1A_15_PTQ_EE': -1,
 'PTEBACC_FSM6CLA1A_PTQ_EE': -2,
 'PTEBACC_FSM_13': -1,
 'PTEBACC_FSM_14_PTQ': -1,
 'PTEBACC_NFSM6CLA1A_15_PTQ_EE': -1,
 'PTEBACC_NFSM6CLA1A_PTQ_EE': -2,
 'PTEBACC_NFSM_13': -1,
 'PTEBACC_NFSM_14_PTQ': -1,
 'PTEBACC_PTQ_EE': 0.0,
 'PTEBACENGAG_LL_PTQ_EE': 0.0,
 'PTEBACENG_E_PTQ_EE': 0.0,
 'PTEBACENG_LL_PTQ_EE': 0.0,
 'PTEBACHUMAG_PTQ_EE': 1.0,
 'PTEBACHUM_E_PTQ_EE': 0.97,
 'PTEBACHUM_PTQ_EE': 1.0,
 'PTEBACLANAG_PTQ_EE': 1.0,
 'PTEBACLAN_E_PTQ_EE': 1.0,
 'PTEBACLAN_PTQ_EE': 1.0,
 'PTEBACMATAG_PTQ_EE': 0.0,
 'PTEBACMAT_E_PTQ_EE': 0.0,
 'PTEBACMAT_PTQ_EE': 0.0,
 'PTFSM6CLA1A': -2,
 'PTFSM6CLA1ABASICS_15_PTQ_EE': -1,
 'PTFSM6CLA1ABASICS_LL_PTQ_EE': -2,
 'PTFSM6CLA1A_15': -1,
 'PTFSMBASICS_13': -1,
 'PTFSMBASICS_14_PTQ': -1,
 'PTFSMCLA_13': -1,
 'PTFSMCLA_14': -1,
 'PTL2BASICS_13': 0.0,
 'PTL2BASICS_14_PTQ': 0.0,
 'PTL2BASICS_15_PTQ_EE': 0.0,
 'PTL2BASICS_3YR_PTQ_EE': 0.0,
 'PTL2BASICS_LL_EAL_PTQ_EE': -2,
 'PTL2BASICS_LL_NMOB_PTQ_EE': -2,
 'PTL2BASICS_LL_PTQ_EE': 0.0,
 'PTNMOB': -2,
 'PTNOTFSM6CLA1A': -2,
 'PTNOTFSM6CLA1ABASICS_15_PTQ_EE': -1,
 'PTNOTFSM6CLA1ABASICS_LL_PTQ_EE': -2,
 'PTNOTFSM6CLA1A_15': -1,
 'PTNOTFSMBASICS_13': -1,
 'PTNOTFSMBASICS_14_PTQ': -1,
 'PTNOTFSMCLA_13': -1,
 'PTNOTFSMCLA_14': -1,
 'PTPRIORAV': -2,
 'PTPRIORHI': -2,
 'PTPRIORLO': -2,
 'PTmultiLan_E': 0.68,
 'PTtripleSci_E': 0.0,
 'RECTYPE': 1,
 'REGION': 32,
 'REGION NAME': 'London East',
 'RELDENOM': 'None',
 'SCHNAME': 'City of London School',
 'SCHNAME_AC': ' ',
 'SCIVACOV_PTQ_EE': 'NP',
 'SCIVALOW_AV_PTQ_EE': 'NP',
 'SCIVALOW_FSM6CLA1A_PTQ_EE': 'NP',
 'SCIVALOW_HI_PTQ_EE': 'NP',
 'SCIVALOW_LO_PTQ_EE': 'NP',
 'SCIVALOW_NFSM6CLA1A_PTQ_EE': 'NP',
 'SCIVALOW_PTQ_EE': 'NP',
 'SCIVAMEA_AV_PTQ_EE': 'NP',
 'SCIVAMEA_FSM6CLA1A_PTQ_EE': 'NP',
 'SCIVAMEA_HI_PTQ_EE': 'NP',
 'SCIVAMEA_LO_PTQ_EE': 'NP',
 'SCIVAMEA_NFSM6CLA1A_PTQ_EE': 'NP',
 'SCIVAMEA_PTQ_EE': 'NP',
 'SCIVAUPP_AV_PTQ_EE': 'NP',
 'SCIVAUPP_FSM6CLA1A_PTQ_EE': 'NP',
 'SCIVAUPP_HI_PTQ_EE': 'NP',
 'SCIVAUPP_LO_PTQ_EE': 'NP',
 'SCIVAUPP_NFSM6CLA1A_PTQ_EE': 'NP',
 'SCIVAUPP_PTQ_EE': 'NP',
 'SENAPK4': nan,
 'SENSE4': nan,
 'TAB1618': 1,
 'TABKS2': 0,
 'TAVENT_EFSM6CLA1A_15_PTQ_EE': nan,
 'TAVENT_EFSM_13': nan,
 'TAVENT_EFSM_14_PTQ': nan,
 'TAVENT_ENFSM6CLA1A_15_PTQ_EE': nan,
 'TAVENT_ENFSM_13': nan,
 'TAVENT_ENFSM_14_PTQ': nan,
 'TAVENT_E_3NG_AV_PTQ_EE': 'NP',
 'TAVENT_E_3NG_FSM6CLA1A_PTQ_EE': 'NP',
 'TAVENT_E_3NG_HI_PTQ_EE': 'NP',
 'TAVENT_E_3NG_LO_PTQ_EE': 'NP',
 'TAVENT_E_3NG_NFSM6CLA1A_PTQ_EE': 'NP',
 'TAVENT_E_3NG_PTQ_EE': '5.6',
 'TAVENT_GAV_PTQ_EE': 'NP',
 'TAVENT_GFSM6CLA1A_15_PTQ_EE': nan,
 'TAVENT_GFSM6CLA1A_PTQ_EE': 'NP',
 'TAVENT_GFSM_13': nan,
 'TAVENT_GFSM_14_PTQ': nan,
 'TAVENT_GHI_PTQ_EE': 'NP',
 'TAVENT_GLO_PTQ_EE': 'NP',
 'TAVENT_GNFSM6CLA1A_15_PTQ_EE': nan,
 'TAVENT_GNFSM6CLA1A_PTQ_EE': 'NP',
 'TAVENT_GNFSM_13': nan,
 'TAVENT_GNFSM_14_PTQ': nan,
 'TAVENT_G_PTQ_EE': '5.3',
 'TBASICS_LL_AV_PTQ_EE': 'NP',
 'TBASICS_LL_HI_PTQ_EE': 'NP',
 'TBASICS_LL_LO_PTQ_EE': 'NP',
 'TEALGRP1': 'NP',
 'TEALGRP2': 'NP',
 'TEALGRP3': 'NP',
 'TEBAC2SCIAG_PTQ_EE': 'NE',
 'TEBAC2SCI_E_PTQ_EE': '0',
 'TEBAC2SCI_PTQ_EE': 'NE',
 'TEBACCAG_PTQ_EE': '0',
 'TEBACC_EAV_PTQ_EE': 'NP',
 'TEBACC_EHI_PTQ_EE': 'NP',
 'TEBACC_ELO_PTQ_EE': 'NP',
 'TEBACC_E_PTQ_EE': '0',
 'TEBACENGAG_LL_PTQ_EE': '0',
 'TEBACENG_E_PTQ_EE': '0',
 'TEBACENG_LL_PTQ_EE': '0',
 'TEBACHUMAG_PTQ_EE': '135',
 'TEBACHUM_E_PTQ_EE': '135',
 'TEBACHUM_PTQ_EE': '135',
 'TEBACLANAG_PTQ_EE': '139',
 'TEBACLAN_E_PTQ_EE': '139',
 'TEBACLAN_PTQ_EE': '139',
 'TEBACMATAG_PTQ_EE': '0',
 'TEBACMAT_E_PTQ_EE': '0',
 'TEBACMAT_PTQ_EE': '0',
 'TELNUM': '0207 4890291',
 'TFSM6CLA1A': 'NP',
 'TFSM6CLA1A_15': nan,
 'TFSMCLA_13': nan,
 'TFSMCLA_14': nan,
 'TNMOB': 'NP',
 'TNOTFSM6CLA1A': 'NP',
 'TNOTFSM6CLA1A_15': nan,
 'TNOTFSMCLA_13': nan,
 'TNOTFSMCLA_14': nan,
 'TOTATT8': '5849',
 'TOTATT8EBAC': '3085.3',
 'TOTATT8ENG': '1012',
 'TOTATT8MAT': '0',
 'TOTATT8OPEN': '1751.8',
 'TOTATT8OPENG': '1452.5',
 'TOTATT8OPENNG': '299.3',
 'TOTPUPS': '918',
 'TOWN': 'London',
 'TPRIORAV': 'NP',
 'TPRIORHI': 'NP',
 'TPRIORLO': 'NP',
 'TPUP': '139',
 'URN': 100003,
 '_id': ObjectId('5b10f2c70fd01f08fa64959d')}

This is an independent school since they don't need to publish their data there are a lot of missing values.  This is something we will need to be mindful of when carrying out the analysis.  Although the percentages have been handled, there are still a number of other measures that are still showing 'NP'.  Since the majority of the measures I will be looking at will be percentages, instead of working through every single measure I will determine those I want to use in my investigation and then clean those as needed.

In [88]:
ks4_expanded_name['P8MEA_AV']

'Progress 8 measure - pupils with middle prior attainment'

In [89]:
ks4.find({'NFTYPE': 'IND'}).count()

882

In [90]:
nftypes

{'AC': 'Sponsored academy',
 'AC1619': 'Academy 16-19 sponsor led',
 'ACC': 'Academy converter - mainstream',
 'ACC1619': 'Academy 16-19 converter',
 'ACCS': 'Academy converter - special school',
 'ACS': 'Sponsored special academy',
 'CTC': 'City technology college',
 'CY': 'Community school',
 'CYS': 'Community special school',
 'F': 'Free school - mainstream',
 'F1619': 'Free school - 16-19',
 'FD': 'Foundation school',
 'FDS': 'Foundation special school',
 'FESI': 'Further Education Sector Institution',
 'FS': 'Free school - special',
 'FSS': 'Studio school',
 'FUTC': 'UTC (university technical college)',
 'IND': 'Independent school',
 'INDSPEC': 'Independent special school',
 'MODFC': 'College funded by Ministry of Defence',
 'NMSS': 'Non-maintained special school',
 'VA': 'Voluntary aided school',
 'VC': 'Voluntary controlled school'}

In [91]:
ks4.find({'NFTYPE': 'CY'}).count()

541

Good things look they are clean enough to start working on the investigation.

# Q1 - Keystage 4 Investigation.  Does the type of school impact the results students acheive at keystage 4?
<a name="q1"></a>

## Basic stats of the dataset

In [92]:
ks4.find().count()

4196

So there are a large number of documents in the dataset (after taking out the non-mainstream schools)

The first thing I need to decide before I can analyse the data is to decide what I mean by 'good performance' and once that is ascertained which of the many data points I will use as measures to base my comparison of school types on.

For a long time the standard measure of successful schools was the percentage of pupils achieving grades A*-C in Maths and English.  This has changed recently with the government introducing new metrics the 'Progress 8' and 'Achievement 8' and the introduction of the English Baccalaurette which includes English, Maths, Sciences (incl. computer science, history/geograghy a modern/ancient foreign language).  So, I will try to look at these as the success measure of a school, and if possible combine them.

So the first step I need to take is to identify the keys for the data I want to query.

In [93]:
# print all the keys and values of the meta data
# to help choose the columns I will use
for d in ks4_meta.find():
    print(d['label'], ':', d['expanded'], '\n')

RECTYPE : Record type

ALPHAIND : Alphabetic sorting index

LEA : Local authority code (see separate list of local authorities and their codes)

ESTAB : Establishment number

URN : School Unique Reference Number

SCHNAME : School name

SCHNAME_AC : School now known as (used if the school has converted to an academy on or after 12 Sept 2015)

ADDRESS1 : School address (1)

ADDRESS2 : School address (2)

ADDRESS3 : School address (3)

TOWN : School town

PCODE : School postcode

TELNUM : School telephone number

CONTFLAG : Contingency flag - school results 'significantly affected'. This field is zero for all schools.

ICLOSE : Closed school flag (0=open; 1=closed)

NFTYPE : School type (see separate list of abbreviations used in the tables)

RELDENOM : School religious character

ADMPOL : School admissions policy (self-declared by schools on Edubase)

EGENDER : School gender of entry

FEEDER : Indicates whether school is a feeder school for sixth form centre/consortia (0=No; 1=Yes)

TABKS2 : Indicates whether school is published in the primary school (key stage 2) performance tables (0=No; 1=Yes)

TAB1618 : Indicates whether school is published in the school and college (16-18) performance tables (0=No; 1=Yes)

AGERANGE : Age range

CONFEXAM : Indicates whether the school has checked its results (R=No; blank=Yes)

TOTPUPS : Number of pupils on roll (all ages)

NUMBOYS : Total boys on roll (including part-time pupils)

NUMGIRLS : Total girls on roll (including part-time pupils)

TPUP : Number of pupils at the end of key stage 4

BPUP : Number of boys at the end of key stage 4

PBPUP : Percentage of pupils at the end of key stage 4 who are boys

GPUP : Number of girls at the end of key stage 4

PGPUP : Percentage of pupils at the end key stage 4 who are girls

KS2APS : Key stage 2 Average Points Score of the cohort at the end of key stage 4

TPRIORLO : Number of pupils at the end of key stage 4 with low prior attainment at the end of key stage 2

PTPRIORLO : Percentage of pupils at the end of key stage 4 with low prior attainment at the end of key stage 2

TPRIORAV : Number of pupils at the end of key stage 4 with middle prior attainment at the end of key stage 2

PTPRIORAV : Percentage of pupils at the end of key stage 4 with middle prior attainment at the end of key stage 2

TPRIORHI : Number of pupils at the end of key stage 4 with high prior attainment at the end of key stage 2

PTPRIORHI : Percentage of pupils at the end of key stage 4 with high prior attainment at the end of key stage 2

TFSM6CLA1A : Number of disadvantaged pupils at the end of key stage 4

PTFSM6CLA1A : Percentage of pupils at the end of key stage 4 who are disadvantaged

TNOTFSM6CLA1A : Number of non-disadvantaged pupils at the end of key stage 4

PTNOTFSM6CLA1A : Percentage of pupils at the end of key stage 4 who are not disadvantaged

TEALGRP2 : Number of pupils at the end of key stage 4 with English as additional language (EAL)

PTEALGRP2 : Percentage of pupils at the end of key stage 4 with English as additional language (EAL)

TEALGRP1 : Number of pupils at the end of key stage 4 with English as their first language

PTEALGRP1 : Percentage of pupils at the end of key stage 4 with English as their first language

TEALGRP3 : Number of pupils at the end of key stage 4 whose first language is unclassified

PTEALGRP3 : Percentage of pupils at the end of key stage 4 whose first language is unclassified

TNMOB : Number of pupils at the end of key stage 4 who are non-mobile

PTNMOB : Percentage of pupils at the end of key stage 4 who are non-mobile

SENSE4 : Number of pupils at the end of key stage 4 with special educational needs (SEN) with a statement or Education, health and care (EHC) plan

PSENSE4 : Percentage of pupils at the end of key stage 4 with special educational needs (SEN) with a statement or Education, health and care (EHC) plan

SENAPK4 : Number of pupils at the end of key stage 4 with special educational needs (SEN) without a statement or Education, health and care (EHC) plan

PSENAPK4 : Percentage of pupils at the end of key stage 4 with special educational needs (SEN) without a statement or Education, health and care (EHC) plan

TOTATT8 : Total sum of Attainment 8 scores

ATT8SCR : Average Attainment 8 score per pupil

TOTATT8ENG : Total sum of Attainment 8 scores for English element

ATT8SCRENG : Average Attainment 8 score per pupil for English element

TOTATT8MAT : Total sum of Attainment 8 scores for mathematics element

ATT8SCRMAT : Average Attainment 8 score per pupil for mathematics element

TOTATT8EBAC : Total sum of Attainment 8 scores for EBacc element

ATT8SCREBAC : Average Attainment 8 score per pupil for EBacc element

TOTATT8OPEN : Total sum of Attainment 8 scores for open element

ATT8SCROPEN : Average Attainment 8 score per pupil for open element

TOTATT8OPENG : Total sum of Attainment 8 scores for open element - GCSE only

ATT8SCROPENG : Average Attainment 8 score per pupil for open element - GCSE only

TOTATT8OPENNG : Total sum of Attainment 8 scores for open element - non-GCSE only

ATT8SCROPENNG : Average Attainment 8 score per pupil for open element - non-GCSE only

P8PUP : Number of pupils included in Progress 8 measure

P8MEACOV : Percentage of pupils at the end of key stage 4 included in Progress 8 measure

P8MEA : Progress 8 measure

P8CILOW : Lower 95% confidence interval for Progress 8 measure

P8CIUPP : Upper 95% confidence interval for Progress 8 measure

P8MEAENG : Progress 8 measure for English element

P8MEAENG_CILOW : Lower 95% confidence interval for Progress 8 English element

P8MEAENG_CIUPP : Upper 95% confidence interval for Progress 8 English element

P8MEAMAT : Progress 8 measure for mathematics element

P8MEAMAT_CILOW : Lower 95% confidence interval for Progress 8 maths element

P8MEAMAT_CIUPP : Upper 95% confidence interval for Progress 8 maths element

P8MEAEBAC : Progress 8 measure for EBacc element

P8MEAEBAC_CILOW : Lower 95% confidence interval for Progress 8 EBacc element

P8MEAEBAC_CIUPP : Upper 95% confidence interval for Progress 8 EBacc element

P8MEAOPEN : Progress 8 measure for open element

P8MEAOPEN_CILOW : Lower 95% confidence interval for Progress 8 open element

P8MEAOPEN_CIUPP : Upper 95% confidence interval for Progress 8 open element

PTL2BASICS_LL_PTQ_EE : Percentage of pupils achieving grades A*-C in both English and mathematics GCSEs

PTL2BASICS_3YR_PTQ_EE : Three year percentage of pupils achieving A*-C in both English and mathematics GCSEs over 2014, 2015 and 2016

TEBACC_E_PTQ_EE : Number of key stage 4 pupils with entries in all English Baccalaureate subject areas

PTEBACC_E_PTQ_EE : Percentage of key stage 4 pupils with entries in all English Baccalaureate subject areas

PTEBACC_PTQ_EE : Percentage of key stage 4 pupils achieving the English Baccalaureate

TEBACENG_E_PTQ_EE : Number of pupils entering the English Baccalaureate English subject area

PTEBACENG_E_PTQ_EE : Percentage of pupils entering the English Baccalaureate English subject area

TEBACMAT_E_PTQ_EE : Number of pupils entering the English Baccalaureate Maths subject area

PTEBACMAT_E_PTQ_EE : Percentage of pupils entering the English Baccalaureate Maths subject area

TEBAC2SCI_E_PTQ_EE : Number of pupils entering the English Baccalaureate Science subject area

PTEBAC2SCI_E_PTQ_EE : Percentage of pupils entering the English Baccalaureate Science subject area

TEBACHUM_E_PTQ_EE : Number of pupils entering the English Baccalaureate Humanities subject area

PTEBACHUM_E_PTQ_EE : Percentage of pupils entering the English Baccalaureate Humanities subject area

TEBACLAN_E_PTQ_EE : Number of pupils entering the English Baccalaureate Language subject area

PTEBACLAN_E_PTQ_EE : Percentage of pupils entering the English Baccalaureate Language subject area

PTEBACENG_LL_PTQ_EE : Percentage of pupils achieving the English Baccalaureate English subject area

PTEBACMAT_PTQ_EE : Percentage of pupils achieving the English Baccalaureate Maths subject area

PTEBAC2SCI_PTQ_EE : Percentage of entered pupils achieving the English Baccalaureate Science subject area

PTEBACHUM_PTQ_EE : Percentage of entered pupils achieving the English Baccalaureate Humanities subject area

PTEBACLAN_PTQ_EE : Percentage of entered pupils achieving the English Baccalaureate Language subject area

SCIVACOV_PTQ_EE : Coverage of the English Baccalaureate Science Value Added indicators of those who entered for science

HUMVACOV_PTQ_EE : Coverage of the English Baccalaureate Humanities Value Added indicators of those who entered for humanities

LANVACOV_PTQ_EE : Coverage of the English Baccalaureate Language Value Added indicators of those who entered for languages

SCIVAMEA_PTQ_EE : English Baccalaureate Science Value Added measure

SCIVALOW_PTQ_EE : English Baccalaureate Science Value Added lower 95% confidence limit

SCIVAUPP_PTQ_EE : English Baccalaureate Science Value Added upper 95% confidence limit

HUMVAMEA_PTQ_EE : English Baccalaureate Humanities Value Added measure

HUMVALOW_PTQ_EE : English Baccalaureate Humanities Value Added lower 95% confidence limit

HUMVAUPP_PTQ_EE : English Baccalaureate Humanities Value Added upper 95% confidence limit

LANVAMEA_PTQ_EE : English Baccalaureate Languages Value Added measure

LANVALOW_PTQ_EE : English Baccalaureate Languages Value Added lower 95% confidence limit

LANVAUPP_PTQ_EE : English Baccalaureate Languages Value Added upper 95% confidence limit

TEBACENG_LL_PTQ_EE : Number of pupils achieving EBacc English subject area

TEBACMAT_PTQ_EE : Number of pupils achieving the English Baccalaureate Maths subject area

TEBAC2SCI_PTQ_EE : Number of pupils achieving the English Baccalaureate Science subject area

TEBACHUM_PTQ_EE : Number of pupils achieving the English Baccalaureate Humanities subject area

TEBACLAN_PTQ_EE : Number of pupils achieving the English Baccalaureate Language subject area

TEBACCAG_PTQ_EE : Number of pupils achieving the English Baccalaureate at grades A*-G

PTEBACCAG_PTQ_EE : Percentage of pupils achieving the English Baccalaureate at grades A*-G

TEBACENGAG_LL_PTQ_EE : Number of pupils achieving the English Baccalaureate English subject area at grade A*-G

PTEBACENGAG_LL_PTQ_EE : Percentage of pupils achieving the English Baccalaureate English subject area at grade A*-G

TEBACMATAG_PTQ_EE : Number of pupils achieving the English Baccalaureate Maths subject area at grade A*-G

PTEBACMATAG_PTQ_EE : Percentage of pupils achieving the English Baccalaureate Maths subject area at grade A*-G

TEBAC2SCIAG_PTQ_EE : Number of pupils achieving the English Baccalaureate Science subject area at grades A*-G

PTEBAC2SCIAG_PTQ_EE : Percentage of entered pupils achieving the English Baccalaureate Science subject area at grades A*-G

TEBACHUMAG_PTQ_EE : Number of pupils achieving the English Baccalaureate Humanities subject area at grade A*-G

PTEBACHUMAG_PTQ_EE : Percentage of entered pupils achieving the English Baccalaureate Humanities subject area at grades A*-G

TEBACLANAG_PTQ_EE : Number of pupils achieving the English Baccalaureate Language subject area at grade A*-G

PTEBACLANAG_PTQ_EE : Percentage of entered pupils achieving the English Baccalaureate Language subject area at grade A*-G

ATT8SCR_FSM6CLA1A : Average Attainment 8 score per disadvantaged pupil

P8PUP_FSM6CLA1A : Number of disadvantaged pupils in Progress 8 measure

P8MEA_FSM6CLA1A : Progress 8 measure - disadvantaged pupils

P8CILOW_FSM6CLA1A : Progress 8 lower 95% confidence interval - disadvantaged pupils

P8CIUPP_FSM6CLA1A : Progress 8 upper 95% confidence interval - disadvantaged pupils

ATT8SCR_NFSM6CLA1A : Average Attainment 8 score per non-disadvantaged pupil

P8PUP_NFSM6CLA1A : Number of non-disadvantaged pupils in Progress 8 measure

P8MEA_NFSM6CLA1A : Progress 8 measure - non-disadvantaged pupils

P8CILOW_NFSM6CLA1A : Progress 8 lower 95% confidence interval - non-disadvantaged pupils

P8CIUPP_NFSM6CLA1A : Progress 8 upper 95% confidence interval - non-disadvantaged pupils

ATT8SCRENG_FSM6CLA1A : Average Attainment 8 score per disadvantaged pupil for English element

P8MEAENG_FSM6CLA1A : Progress 8 measure for English element - disadvantaged pupils

P8MEAENG_CILOW_FSM6CLA1A : Lower 95% confidence interval for Progress 8 English element for disadvantaged pupils

P8MEAENG_CIUPP_FSM6CLA1A : Upper 95% confidence interval for Progress 8 English element for disadvantaged pupils

ATT8SCRMAT_FSM6CLA1A : Average Attainment 8 score per disadvantaged pupil for mathematics element

P8MEAMAT_FSM6CLA1A : Progress 8 measure for maths element - disadvantaged pupils

P8MEAMAT_CILOW_FSM6CLA1A : Lower 95% confidence interval for Progress 8 maths element for disadvantaged pupils

P8MEAMAT_CIUPP_FSM6CLA1A : Upper 95% confidence interval for Progress 8 maths element for disadvantaged pupils

ATT8SCREBAC_FSM6CLA1A : Average Attainment 8 score per disadvantaged pupil for EBacc element

P8MEAEBAC_FSM6CLA1A : Progress 8 measure for EBacc element - disadvantaged pupils

P8MEAEBAC_CILOW_FSM6CLA1A : Lower 95% confidence interval for Progress 8 EBacc element for disadvantaged pupils

P8MEAEBAC_CIUPP_FSM6CLA1A : Upper 95% confidence interval for Progress 8 EBacc element for disadvantaged pupils

ATT8SCROPEN_FSM6CLA1A : Average Attainment 8 score per disadvantaged pupil for open element

P8MEAOPEN_FSM6CLA1A : Progress 8 measure for open element - disadvantaged pupils

P8MEAOPEN_CILOW_FSM6CLA1A : Lower 95% confidence interval for Progress 8 open element for disadvantaged pupils

P8MEAOPEN_CIUPP_FSM6CLA1A : Upper 95% confidence interval for Progress 8 open element for disadvantaged pupils

ATT8SCRENG_NFSM6CLA1A : Average Attainment 8 score per non-disadvantaged pupil for English element

P8MEAENG_NFSM6CLA1A : Progress 8 measure for English element - non-disadvantaged pupils

P8MEAENG_CILOW_NFSM6CLA1A : Lower 95% confidence interval for Progress 8 English element for non-disadvantaged pupils

P8MEAENG_CIUPP_NFSM6CLA1A : Upper 95% confidence interval for Progress 8 English element for non-disadvantaged pupils

ATT8SCRMAT_NFSM6CLA1A : Average Attainment 8 score per non-disadvantaged pupil for mathematics element

P8MEAMAT_NFSM6CLA1A : Progress 8 measure for maths element - non-disadvantaged pupils

P8MEAMAT_CILOW_NFSM6CLA1A : Lower 95% confidence interval for Progress 8 maths element for non-disadvantaged pupils

P8MEAMAT_CIUPP_NFSM6CLA1A : Upper 95% confidence interval for Progress 8 maths element for non-disadvantaged pupils

ATT8SCREBAC_NFSM6CLA1A : Average Attainment 8 score per non-disadvantaged pupil for EBacc element

P8MEAEBAC_NFSM6CLA1A : Progress 8 measure for EBacc element - non-disadvantaged pupils

P8MEAEBAC_CILOW_NFSM6CLA1A : Lower 95% confidence interval for Progress 8 EBacc element for non-disadvantaged pupils

P8MEAEBAC_CIUPP_NFSM6CLA1A : Upper 95% confidence interval for Progress 8 EBacc element for non-disadvantaged pupils

ATT8SCROPEN_NFSM6CLA1A : Average Attainment 8 score per non-disadvantaged pupil for open element

P8MEAOPEN_NFSM6CLA1A : Progress 8 measure for open element - non-disadvantaged pupils

P8MEAOPEN_CILOW_NFSM6CLA1A : Lower 95% confidence interval for Progress 8 open element for non-disadvantaged pupils

P8MEAOPEN_CIUPP_NFSM6CLA1A : Upper 95% confidence interval for Progress 8 open element for non-disadvantaged pupils

ATT8SCROPENG_FSM6CLA1A : Average Attainment 8 score per disadvantaged pupil for open element - GCSE only

ATT8SCROPENNG_FSM6CLA1A : Average Attainment 8 score per disadvantaged pupil for open element - non-GCSE only

ATT8SCROPENG_NFSM6CLA1A : Average Attainment 8 score per non-disadvantaged pupil for open element - GCSE only

ATT8SCROPENNG_NFSM6CLA1A : Average Attainment 8 score per non-disadvantaged pupil for open element - non-GCSE only

DIFFN_ATT8 : Difference between Attainment 8 for disadvantaged pupils in school/LA and non-disadvantaged pupils nationally

DIFFN_P8MEA : Difference between Progress 8 measure for disadvantaged pupils in school/LA and non-disadvantaged pupils nationally

ATT8SCR_LO : Average Attainment 8 score per pupil with low prior attainment

P8PUP_LO : Number of pupils with low prior attainment included in Progress 8 measure

P8MEA_LO : Progress 8 measure - pupils with low prior attainment

P8CILOW_LO : Progress 8 lower 95% confidence interval - pupils with low prior attainment

P8CIUPP_LO : Progress 8 upper 95% confidence interval - pupils with low prior attainment

ATT8SCR_AV : Average Attainment 8 score per pupil with middle prior attainment

P8PUP_AV : Number of pupils with middle prior attainment included in Progress 8 measure

P8MEA_AV : Progress 8 measure - pupils with middle prior attainment

P8CILOW_AV : Progress 8 lower 95% confidence interval - pupils with middle prior attainment

P8CIUPP_AV : Progress 8 upper 95% confidence interval - pupils with middle prior attainment

ATT8SCR_HI : Average Attainment 8 score per pupil with high prior attainment

P8PUP_HI : Number of pupils with high prior attainment included in Progress 8 measure

P8MEA_HI : Progress 8 measure - pupils with high prior attainment

P8CILOW_HI : Progress 8 lower 95% confidence interval - pupils with high prior attainment

P8CIUPP_HI : Progress 8 upper 95% confidence interval - pupils with high prior attainment

ATT8SCR_EAL : Average Attainment 8 score per pupil for whom English is an additional language

P8PUP_EAL : Number of pupils for whom English is an additional language included in Progress 8 measure

P8MEA_EAL : Progress 8 measure - pupils for whom English is an additional language

P8CILOW_EAL : Progress 8 lower 95% confidence interval - pupils for whom English is an additional language

P8CIUPP_EAL : Progress 8 upper 95% confidence interval - pupils for whom English is an additional language

ATT8SCR_GIRLS : Average Attainment 8 score per girl

P8PUP_GIRLS : Number of girls included in Progress 8 measure

P8MEA_GIRLS : Progress 8 measure - girls

P8CILOW_GIRLS : Progress 8 lower 95% confidence interval - girls

P8CIUPP_GIRLS : Progress 8 upper 95% confidence interval - girls

ATT8SCR_BOYS : Average Attainment 8 score per boy

P8PUP_BOYS : Number of boys included in Progress 8 measure

P8MEA_BOYS : Progress 8 measure - boys

P8CILOW_BOYS : Progress 8 lower 95% confidence interval - boys

P8CIUPP_BOYS : Progress 8 upper 95% confidence interval - boys

ATT8SCR_NMOB : Average Attainment 8 score per non-mobile pupil

P8PUP_NMOB : Number of non-mobile pupils included in Progress 8 measure

P8MEA_NMOB : Progress 8 measure - non-mobile pupils

P8CILOW_NMOB : Progress 8 lower 95% confidence interval - non-mobile pupils

P8CIUPP_NMOB : Progress 8 upper 95% confidence interval - non-mobile pupils

ATT8SCR_15 : Average Attainment 8 score per pupil  - 2015 opt-in schools only

P8PUP_15 : Number of pupils included in Progress 8 measure - 2015 opt-in schools only

P8MEA_15 : Progress 8 measure - 2015 opt-in schools only

P8CILOW_15 : Progress 8 lower 95% confidence interval - 2015 opt-in schools only

P8CIUPP_15 : Progress 8 upper 95% confidence interval - 2015 opt-in schools only

TEBACC_ELO_PTQ_EE : Number of pupils with low prior attainment with entries in all English Baccalaureate subject areas

PTEBACC_ELO_PTQ_EE : Percentage of pupils with low prior attainment with entries in all English Baccalaureate subject areas

PTEBACCLO_PTQ_EE : Percentage of pupils with low prior attainment achieving the English Baccalaureate

TEBACC_EAV_PTQ_EE : Number of pupils with middle prior attainment with entries in all English Baccalaureate subject areas

PTEBACC_EAV_PTQ_EE : Percentage of pupils with middle prior attainment with entries in all English Baccalaureate subject areas

PTEBACCAV_PTQ_EE : Percentage of pupils with middle prior attainment achieving the English Baccalaureate

TEBACC_EHI_PTQ_EE : Number of pupils with high prior attainment with entries in all English Baccalaureate subject areas


Looking through these it is clear that I will need to be selective in choosing measures.  There are thousands of ways to subdivide this dataset and investigate it.  I will be focusing on the Average numbers for the whole school, for every student.  There will of course be cases where this skews the results.

For instance, at schools with many disadvantaged students the average scores could be affected and without looking including measures the results can not be fully comprehensive.  That said it is beyond the scope of this project to examine every single possible facet of the dataset.

In [94]:
test = pd.DataFrame(list(ks4.find({}, {'ATT8SCR':1, '_id': 0})))
test.count()

ATT8SCR    4126
dtype: int64

### Descriptive analysis

<a name='todo'></a>

# todo

### Choosing the measures I will use to compare the schools

### What flaws are there in the data/subset of data that could impact findings

### Carry out some analysis resulting in a few plots that convey findings

### Run some statistical tests

### Summarise findings

#  Q2 - Keystage 2 and 4 Investigation.  Do schools that perform well at KS2 deliver as good or better results at KS4.
<a name="q2"></a>

The first thing I need to decide before I can analyse the data is to decide what I mean by 'good performance' and which measures I will use to compare

### Descriptive analysis

### Choosing the measures I will use to compare the schools

### What flaws are there in the data/subset of data that could impact findings

### Carry out some analysis resulting in a few plots that convey findings

### Run some statistical tests

### Summarise findings

<a name="machine_learning"></a>

# Machine Learning.

Two main chances to implement it as I see it.
- it can be used to fill in missing values
- it can be used to predict what a schools results will be at ks4
- it could be used to cluster groups.

# Cleanup/remove the database
<a name="cleanup"></a>

Uncomment the lines below to remove the MongoDB created in the investigation.

In [95]:
# uncomment to remove the database if needed
client.drop_database('schools_db')
client.database_names()

['accidents', 'admin', 'local']