# Pandas Library

In [2]:
# first we need to import pandas.  Convention is variable pd
import pandas as pd

# make a list and dict to use pandas on
simple_list = ['apples', 'oranges', 'bananas', 'pears']

In [8]:
# print out list
print('First list item (simple_list[0]) is {0}'.format(simple_list[0]))
print('Third list item (simple_list[2]) is {0}'.format(simple_list[2]))
print('Last list item (simple_list[-1]) is {0}'.format(simple_list[-1]))
print('2nd last list item (simple_list[-2]) is {0}'.format(simple_list[-2]))

First list item (simple_list[0]) is apples
Third list item (simple_list[2]) is bananas
Last list item (simple_list[-1]) is pears
2nd last list item (simple_list[-2]) is bananas

Make a simple dictionary

In [9]:
simple_dict = {1:'one', 2:'two', 4:'four', 3:'three'}
print("Item with key (index) '4' has value: {}".format(simple_dict[4]))

Item with key (index) '4' has value: four

We can iterate through all keys using for loop

In [10]:
for key in simple_dict:
    print(simple_dict[key])

one
two
three
four

<span style="color:#3388CC">
Indigo note.
</span>

Or we can use _list comprehension_<span style="color:#3A9C35">
Kuma
</span>
iterm

test

In [14]:
print(list(simple_dict.keys()))
print(list(simple_dict.values()))

[1, 2, 3, 4]
['one', 'two', 'three', 'four']

we can use a list or dict comprehension to filter the contents of an object according to a test condition.

In [15]:
[simple_dict[k] for k in simple_dict if k>2]

['three', 'four']

Simple way to reverse a dictionary using zip()

In [24]:
# zip into a collection of tuples
alt_dict = zip(simple_dict.values(), simple_dict.keys())
for e in alt_dict:
    print(e)

('one', 1)
('two', 2)
('three', 3)
('four', 4)

In [28]:
# concise method:
alternative_dict = dict(zip(simple_dict.values(), simple_dict.keys()))

print(alternative_dict)

{'four': 4, 'two': 2, 'one': 1, 'three': 3}

## Pandas Series and Dataframes

In [30]:
pd.Series( ['one', 'two', 'three', 'four'] )

0      one
1      two
2    three
3     four
dtype: object

In [31]:
# we can simplify the creation of a Series by importingi it from pandas directly
from pandas import Series
simple_series = Series( [101, 102, 103, 104])
simple_series

0    101
1    102
2    103
3    104
dtype: int64

In [32]:
simple_series[1]

102

In [33]:
simple_series[[1, 0, 3]]

1    102
0    101
3    104
dtype: int64

In [34]:
myindex_series = Series( ['apple', 'orange', 'pear', 'plum'],
                       index=['one', 'two', 'three', 'four'])
print(myindex_series.index)
myindex_series

Index(['one', 'two', 'three', 'four'], dtype='object')

one       apple
two      orange
three      pear
four       plum
dtype: object

## Investigating a file

### Take a peak at the firs few lines of a file

In [3]:
!ls 'TM351_part_02_notebooks/data/iwCouncilSpending/'

csvFromWeb.csv	PUBLISHED FORMAT - NOV 2013.csv  sample1.csv  sample2.csv

In [4]:
!head -n 5 TM351_part_02_notebooks/data/iwCouncilSpending/PUBLISHED\ FORMAT\ -\ NOV\ 2013.csv

###Â get a line count
using th -l switch to count lines

This line count is the upper bound as some data may be split over several lines

In [7]:
!wc -l 'TM351_part_02_notebooks/data/iwCouncilSpending/PUBLISHED FORMAT - NOV 2013.csv'

11413 TM351_part_02_notebooks/data/iwCouncilSpending/PUBLISHED FORMAT - NOV 2013.csv

### We can also peak at last few lines
this is useful to check whether there is any blank lines at tthe end of a file

In [8]:
!tail -n 6 'TM351_part_02_notebooks/data/iwCouncilSpending/PUBLISHED FORMAT - NOV 2013.csv'

## Reading in CSV files

_pandas_ provides utilities for reading and writing CSV files so we will use it

In [9]:
import pandas as pd

In [14]:
pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/sample1.csv')

,Capital or Revenue,Directorate,Transaction Number,Date,Service Area,Expenses Type,Amount,Supplier Name
0,Revenue,Community Wellbeing & Social Care,5105636098,13.11.2013,Public Libraries Central,Marketing Costs,200.00,REDACTED PERSONAL DATA
1,Revenue,Community Wellbeing & Social Care,5105635705,08.11.2013,Drug Misuse - Adults,Charges from Independent Providers,120.00,REDACTED PERSONAL DATA
2,Revenue,Childrens Services,5105637261,20.11.2013,Thompson House Tuition Centre (PRU),Professional Services,240.00,* M BOWDERY T/A SPOTLIGHT BOUTIQUE
3,Revenue,Community Wellbeing & Social Care,5105637069,27.11.2013,Safeguarding Adults,Professional Services,"5,285.00",REDACTED PERSONAL DATA
4,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
5,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
6,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
7,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
8,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA

### be careful of encodings

In [15]:
#pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/sample2.csv')
import chardet
testfile = open('TM351_part_02_notebooks/data/iwCouncilSpending/sample2.csv', 'rb').read()
chardet.detect(testfile)

{'confidence': 0.73, 'encoding': 'windows-1252'}

In [16]:
pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/sample2.csv', encoding='windows-1252')

,Revenue,Community Wellbeing & Social Care,GPC,23.11.2013,Training - Childrens,Licences,28.96,SURVEYMONKEY.COM
0,Revenue,Community Wellbeing & Social Care,GPC,27.11.2013,Workforce Development - Early Years,Postage,6.95,POST OFFICE COUNTERS
1,Revenue,Resources,GPC,27.11.2013,Organisational Development â Leadership,Professional Services,28.90,WWW.PRINTEDPAPERPRODUCTS.CO.UK
2,Revenue,Community Wellbeing & Social Care,GPC,27.11.2013,Hub Coordinators,Travel Expenses,25.00,STAGECOACH SOUTH
3,Revenue,Community Wellbeing & Social Care,GPC,27.11.2013,Workforce Development - Westridge Centre,Catering Purchases,30.58,TESCO STORE 5567
4,Revenue,Economy & Environment,GPC,31.10.2013,Play Development,Operational Equipment,127.99,GLENWAY PRODUCTS LTD
5,Revenue,Economy & Environment,GPC,04.11.2013,Play Development,Operational Equipment,91.99,GREENHAM TRADING LTD
6,Revenue,Economy & Environment,GPC,06.11.2013,Play Development,Travel Expenses,470.70,WIGHTLINK
7,Revenue,Economy & Environment,GPC,13.11.2013,Play Development,Operational Equipment,108.42,WWW.SPORTSFRONT.CO.UK
8,Revenue,Economy & Environment,GPC,14.11.2013,Sports Development - Admin,Training,12.50,WWW.RFU.COM

### read in n lines of a file

In [48]:
sample2 = pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/sample2.csv', encoding='windows-1252', nrows=3)

In [49]:
origNames =  sample2.columns.values.tolist()
origNames

['Revenue',
 'Community Wellbeing & Social Care',
 'GPC',
 '23.11.2013',
 'Training - Childrens',
 'Licences',
 '28.96',
 'SURVEYMONKEY.COM']

###Â read file in as chunks

In [25]:
chunks = pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/sample2.csv',encoding='windows-1252',chunksize=4)

In [26]:
for chunk in chunks:
    print("New chunk...")
    print(chunk[['Revenue', 'Licences']])

New chunk...
   Revenue               Licences
0  Revenue                Postage
1  Revenue  Professional Services
2  Revenue        Travel Expenses
3  Revenue     Catering Purchases
New chunk...
   Revenue               Licences
4  Revenue  Operational Equipment
5  Revenue  Operational Equipment
6  Revenue        Travel Expenses
7  Revenue  Operational Equipment
New chunk...
   Revenue  Licences
8  Revenue  Training

### import a csv from a url

In [32]:
url = 'http://www.iwight.com/documentlibrary/download/november-2013-transparency-data-csv'

import requests
resp = requests.get(url)
resp.content[:103]

b'Capital or Revenue,Directorate,Transaction Number,Date,Service Area,Expenses Type,Amount,Supplier Name\r'

In [33]:
# b shows it is a byte object now use chardet to detect
import chardet
chardet.detect(resp.content)

{'confidence': 0.73, 'encoding': 'windows-1252'}

In [35]:
csvfromweb = pd.read_csv(url, encoding = 'windows-1252')
csvfromweb.head(5)

,Capital or Revenue,Directorate,Transaction Number,Date,Service Area,Expenses Type,Amount,Supplier Name
0,Revenue,Community Wellbeing & Social Care,5105636098,13.11.2013,Public Libraries Central,Marketing Costs,200.00,REDACTED PERSONAL DATA
1,Revenue,Community Wellbeing & Social Care,5105635705,08.11.2013,Drug Misuse - Adults,Charges from Independent Providers,120.00,REDACTED PERSONAL DATA
2,Revenue,Childrens Services,5105637261,20.11.2013,Thompson House Tuition Centre (PRU),Professional Services,240.00,* M BOWDERY T/A SPOTLIGHT BOUTIQUE
3,Revenue,Community Wellbeing & Social Care,5105637069,27.11.2013,Safeguarding Adults,Professional Services,"5,285.00",REDACTED PERSONAL DATA
4,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA

## Write DF to CSV files

In [37]:
csvfromweb.to_csv('TM351_part_02_notebooks/data/iwCouncilSpending/csvfromweb_a.csv')
# chow first few lines to prove written
pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/csvfromweb_a.csv', nrows=5)

,Unnamed: 0,Capital or Revenue,Directorate,Transaction Number,Date,Service Area,Expenses Type,Amount,Supplier Name
0,0,Revenue,Community Wellbeing & Social Care,5105636098,13.11.2013,Public Libraries Central,Marketing Costs,200.00,REDACTED PERSONAL DATA
1,1,Revenue,Community Wellbeing & Social Care,5105635705,08.11.2013,Drug Misuse - Adults,Charges from Independent Providers,120.00,REDACTED PERSONAL DATA
2,2,Revenue,Childrens Services,5105637261,20.11.2013,Thompson House Tuition Centre (PRU),Professional Services,240.00,* M BOWDERY T/A SPOTLIGHT BOUTIQUE
3,3,Revenue,Community Wellbeing & Social Care,5105637069,27.11.2013,Safeguarding Adults,Professional Services,"5,285.00",REDACTED PERSONAL DATA
4,4,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA

Files without header rows or index

In [41]:
csvfromweb.to_csv('TM351_part_02_notebooks/data/iwCouncilSpending/csvfromweb_unheaded.csv', index=False, header=False)
pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/csvfromweb_unheaded.csv', header=None)

,0,1,2,3,4,5,6,7
0,Revenue,Community Wellbeing & Social Care,5105636098,13.11.2013,Public Libraries Central,Marketing Costs,200.00,REDACTED PERSONAL DATA
1,Revenue,Community Wellbeing & Social Care,5105635705,08.11.2013,Drug Misuse - Adults,Charges from Independent Providers,120.00,REDACTED PERSONAL DATA
2,Revenue,Childrens Services,5105637261,20.11.2013,Thompson House Tuition Centre (PRU),Professional Services,240.00,* M BOWDERY T/A SPOTLIGHT BOUTIQUE
3,Revenue,Community Wellbeing & Social Care,5105637069,27.11.2013,Safeguarding Adults,Professional Services,"5,285.00",REDACTED PERSONAL DATA
4,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
5,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
6,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
7,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
8,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA
9,Revenue,Childrens Services,5105634118,06.11.2013,Duty and Assessment 2,Professional Services,216.90,REDACTED PERSONAL DATA
10,Revenue,Childrens Services,5105636630,13.11.2013,Youth- Newport,General Materials,495.00,REDACTED PERSONAL DATA
11,Revenue,Childrens Services,5105634014,01.11.2013,Pupils with statements - Non-Maintained Schools,Office Equipment,826.50,REDACTED PERSONAL DATA
12,Revenue,Childrens Services,5105634012,01.11.2013,Pupils with statements - Non-Maintained Schools,Transport of Clients,383.50,REDACTED PERSONAL DATA
13,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,120.00,REDACTED PERSONAL DATA
14,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,50.00,REDACTED PERSONAL DATA
15,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,120.00,REDACTED PERSONAL DATA
16,Revenue,Economy & Environment,5105638339,27.11.2013,Love Lane Primary School PO31 7ET,Security of Buildings,30.00,REDACTED PERSONAL DATA
17,Revenue,Economy & Environment,5105638339,27.11.2013,Love Lane Primary School PO31 7ET,Security of Buildings,25.00,REDACTED PERSONAL DATA
18,Revenue,Economy & Environment,5105638339,27.11.2013,Love Lane Primary School PO31 7ET,Security of Buildings,310.00,REDACTED PERSONAL DATA
19,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,65.00,REDACTED PERSONAL DATA
20,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,310.00,REDACTED PERSONAL DATA
21,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,155.00,REDACTED PERSONAL DATA
22,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,25.00,REDACTED PERSONAL DATA
23,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,60.00,REDACTED PERSONAL DATA
24,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,80.00,REDACTED PERSONAL DATA
25,Revenue,Economy & Environment,5105638339,27.11.2013,Old Cowes Enterprise College,Security of Buildings,620.00,REDACTED PERSONAL DATA
26,Revenue,Resources,5105637961,22.11.2013,Capital Receipts,Capital Contractor Payments,100.00,REDACTED PERSONAL DATA
27,Revenue,Resources,5105637961,22.11.2013,Capital Receipts,Capital Contractor Payments,80.00,REDACTED PERSONAL DATA
28,Revenue,Resources,5105637961,22.11.2013,Capital Receipts,Capital Contractor Payments,100.00,REDACTED PERSONAL DATA
29,Revenue,Resources,5105637961,22.11.2013,Capital Receipts,Capital Contractor Payments,100.00,REDACTED PERSONAL DATA
...,...,...,...,...,...,...,...,...
11382,Revenue,Community Wellbeing & Social Care,GPC,11.11.2013,Workforce Development - Westridge Centre,Catering Purchases,18.05,TESCO STORE 5567
11383,Revenue,Childrens Services,GPC,11.11.2013,Adult Social Care - Workforce Development,Training,5.10,HUNTINGTONS DISEASE ASSOCIATION
11384,Revenue,Community Wellbeing & Social Care,GPC,12.11.2013,Governors Support,Travel Expenses,48.70,WWW.WIGHTLINK.CO.UK
11385,Revenue,Childrens Services,GPC,12.11.2013,LSCB (Local Safeguarding Childrens Board),Travel Expenses,47.60,STAGECOACH SOUTH
11386,Revenue,Community Wellbeing & Social Care,GPC,13.11.2013,Workforce Development - Westridge Centre,Catering Purchases,8.50,TESCO STORE 5567
11387,Revenue,Community Wellbeing & Social Care,GPC,13.11.2013,Workforce Development - Westridge Centre,Catering Purchases,4.00,TESCO STORE 5567
11388,Revenue,Community Wellbeing & Social Care,GPC,14.11.2013,Workforce Development - Westridge Centre,Catering Purchases,39.81,TESCO STORE 5567
11389,Revenue,Community Wellbeing & Social Care,GPC,19.11.2013,Personal & Community Development Learning,General Materials,9.99,AMAZON MARKTEPLACE
11390,Revenue,Community Wellbeing & Social Care,GPC,19.11.2013,Workforce Development - Westridge Centre,Catering Purchases,34.21,TESCO STORE 5567
11391,Revenue,Community Wellbeing & Social Care,GPC,20.11.2013,Personal & Community Development Learning,General Materials,3.96,AMAZON MARKTEPLACE
11392,Revenue,Community Wellbeing & Social Care,GPC,21.11.2013,Personal & Community Development Learning,General Materials,7.07,AMAZON MARKTEPLACE
11393,Revenue,Childrens Services,GPC,21.11.2013,Adult Social Care - Workforce Development,Travel Expenses,48.70,WWW.WIGHTLINK.CO.UK
11394,Revenue,Community Wellbeing & Social Care,GPC,21.11.2013,Workforce Development - Early Years,Travel Expenses,32.00,RED FUNNEL BOOKIT
11395,Revenue,Community Wellbeing & Social Care,GPC,21.11.2013,Workforce Development - Early Years,Travel Expenses,157.80,STAGECOACH SOUTH
11396,Revenue,Community Wellbeing & Social Care,GPC,21.11.2013,Workforce Development - Westridge Centre,Catering Purchases,4.00,TESCO STORE 5567
11397,Revenue,Community Wellbeing & Social Care,GPC,23.11.2013,Workforce Development - Westridge Centre,Licences,28.99,SURVEYMONKEY.COM
11398,Revenue,Community Wellbeing & Social Care,GPC,23.11.2013,Workforce Development Schools,Licences,28.99,SURVEYMONKEY.COM
11399,Revenue,Community Wellbeing & Social Care,GPC,23.11.2013,Core Programmes,Licences,28.99,SURVEYMONKEY.COM
11400,Revenue,Community Wellbeing & Social Care,GPC,23.11.2013,Workforce Development - Early Years,Licences,28.99,SURVEYMONKEY.COM
11401,Revenue,Childrens Services,GPC,23.11.2013,Adult Social Care - Workforce Development,Licences,28.99,SURVEYMONKEY.COM
11402,Revenue,Community Wellbeing & Social Care,GPC,23.11.2013,Training - Childrens,Licences,28.96,SURVEYMONKEY.COM
11403,Revenue,Community Wellbeing & Social Care,GPC,27.11.2013,Workforce Development - Early Years,Postage,6.95,POST OFFICE COUNTERS
11404,Revenue,Resources,GPC,27.11.2013,Organisational Development â Leadership,Professional Services,28.90,WWW.PRINTEDPAPERPRODUCTS.CO.UK
11405,Revenue,Community Wellbeing & Social Care,GPC,27.11.2013,Hub Coordinators,Travel Expenses,25.00,STAGECOACH SOUTH
11406,Revenue,Community Wellbeing & Social Care,GPC,27.11.2013,Workforce Development - Westridge Centre,Catering Purchases,30.58,TESCO STORE 5567
11407,Revenue,Economy & Environment,GPC,31.10.2013,Play Development,Operational Equipment,127.99,GLENWAY PRODUCTS LTD
11408,Revenue,Economy & Environment,GPC,04.11.2013,Play Development,Operational Equipment,91.99,GREENHAM TRADING LTD
11409,Revenue,Economy & Environment,GPC,06.11.2013,Play Development,Travel Expenses,470.70,WIGHTLINK
11410,Revenue,Economy & Environment,GPC,13.11.2013,Play Development,Operational Equipment,108.42,WWW.SPORTSFRONT.CO.UK
11411,Revenue,Economy & Environment,GPC,14.11.2013,Sports Development - Admin,Training,12.50,WWW.RFU.COM

get original column names

In [51]:
origNames = csvfromweb.columns.values.tolist()
origNames

['Capital or Revenue',
 'Directorate',
 'Transaction Number',
 'Date',
 'Service Area',
 'Expenses Type',
 'Amount',
 'Supplier Name']

In [54]:
pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/csvfromweb_unheaded.csv', nrows=5, header=None, names=origNames)

,Capital or Revenue,Directorate,Transaction Number,Date,Service Area,Expenses Type,Amount,Supplier Name
0,Revenue,Community Wellbeing & Social Care,5105636098,13.11.2013,Public Libraries Central,Marketing Costs,200.00,REDACTED PERSONAL DATA
1,Revenue,Community Wellbeing & Social Care,5105635705,08.11.2013,Drug Misuse - Adults,Charges from Independent Providers,120.00,REDACTED PERSONAL DATA
2,Revenue,Childrens Services,5105637261,20.11.2013,Thompson House Tuition Centre (PRU),Professional Services,240.00,* M BOWDERY T/A SPOTLIGHT BOUTIQUE
3,Revenue,Community Wellbeing & Social Care,5105637069,27.11.2013,Safeguarding Adults,Professional Services,"5,285.00",REDACTED PERSONAL DATA
4,Revenue,Community Wellbeing & Social Care,5105637605,22.11.2013,Leaseholds by LA,Accommodation Costs - Leaseholder Payments,695.89,REDACTED PERSONAL DATA

read in only certain columns

In [57]:
tmp = pd.read_csv('TM351_part_02_notebooks/data/iwCouncilSpending/sample1.csv', nrows=3, usecols=['Date','Expenses Type','Amount'])
tmp

         Date                       Expenses Type  Amount
0  13.11.2013                     Marketing Costs   200.0
1  08.11.2013  Charges from Independent Providers   120.0
2  20.11.2013               Professional Services   240.0